/* ============ IELTS PRO · Practice content (ORIGINAL material, exam-format inspired) ============ */
/* Reading passages · A = Academic, G = General Training */
const IELTS_READ = [
  { id: 'ra1', type: 'A', level: 'B2', topic: 'Urban design', title: 'The Science of Cool Cities', src: 'Adapted from an original academic-style article',
    paras: [
      'A. On a July afternoon, the tarmac of a city car park can reach 60°C while a leafy park two streets away stays ten degrees cooler. This contrast — the urban heat island — arises because cities replace vegetation with materials that absorb heat by day and release it slowly at night. The effect is strongest in dense districts with little shade, and it pushes up air-conditioning use, which in turn releases yet more heat into the streets.',
      'B. The cheapest remedy is also the oldest: trees. A mature broadleaf tree can transpire hundreds of litres of water a day, cooling its surroundings like a natural air-conditioner, while its canopy blocks solar radiation before it reaches asphalt. Studies in temperate cities suggest street trees can lower peak surface temperatures by five to eight degrees. The catch is time — a sapling needs a decade to deliver that service — and water, which arid cities may not have.',
      'C. Engineering offers faster fixes. Cool roofs painted white reflect up to 80 per cent of sunlight, and “green roofs” planted with sedum insulate buildings while absorbing storm water. Permeable pavements store less heat than concrete and let rain soak through, recharging groundwater. In Singapore, planners have gone further, weaving elevated gardens through the downtown so that office workers walk in shade most of the day.',
      'D. Yet technology alone cannot out-design a poorly built city. Heat deaths cluster among elderly residents in top-floor flats without cross-ventilation, close to bus stops and far from parks. Researchers therefore argue for “heat equity”: mapping where vulnerable people live and planting, painting and ventilating there first. The science of cool cities, in other words, is as much about who is protected as about what is built.'
    ],
    heads: ['i. Faster technological fixes', 'ii. A pattern of unequal risk', 'iii. Why cities overheat', 'iv. The limits of planting alone', 'v. Cooling with living infrastructure'],
    vocab: [{ w: 'transpire', d: 'to release water vapour' }, { w: 'canopy', d: 'the leafy cover of a tree' }, { w: 'permeable', d: 'allowing liquid to pass through' }, { w: 'cross-ventilation', d: 'airflow passing through a space' }],
    qs: [
      { t: 'heads', q: 'Choose the correct heading for Paragraph A.', opts: ['i', 'ii', 'iii', 'iv', 'v'], a: 2, exp: 'Paragraph A explains WHY cities overheat: heat-absorbing materials replacing vegetation.' },
      { t: 'heads', q: 'Choose the correct heading for Paragraph B.', opts: ['i', 'ii', 'iii', 'iv', 'v'], a: 4, exp: 'Paragraph B is about trees — cooling with living infrastructure.' },
      { t: 'heads', q: 'Choose the correct heading for Paragraph D.', opts: ['i', 'ii', 'iii', 'iv', 'v'], a: 1, exp: 'Paragraph D describes unequal heat risk among vulnerable residents.' },
      { t: 'tf', q: 'Urban surfaces cool quickly after sunset.', a: 'FALSE', exp: 'The passage says heat-absorbing materials “release it slowly at night”.' },
      { t: 'tf', q: 'Trees deliver immediate cooling as soon as they are planted.', a: 'FALSE', exp: '“a sapling needs a decade to deliver that service”.' },
      { t: 'tf', q: 'Cool roofs can reflect most of the sunlight that hits them.', a: 'TRUE', exp: '“reflect up to 80 per cent of sunlight”.' },
      { t: 'gap', q: 'Complete the summary (ONE WORD): Street trees cool by __________ water and by blocking radiation.', accept: 'transpiring', exp: '“can transpire hundreds of litres of water a day”.' },
      { t: 'gap', q: 'Permeable pavements help to recharge __________. (ONE WORD)', accept: 'groundwater', exp: '“let rain soak through, recharging groundwater”.' },
      { t: 'mc', q: 'What is the writer’s main point in Paragraph D?', opts: ['Technology has solved urban heat.', 'Protection should prioritise vulnerable people.', 'Air-conditioning should be banned.', 'Parks are a waste of money.'], a: 1, exp: 'The paragraph argues for “heat equity” — protecting vulnerable residents first.' },
      { t: 'short', q: 'In which paragraph does the writer mention a city that built elevated gardens? (letter)', accept: 'c', exp: 'Paragraph C: “In Singapore… elevated gardens through the downtown”.' }
    ] },
  { id: 'ra2', type: 'A', level: 'B1+', topic: 'Food systems', title: 'Pollinators on Your Plate', src: 'Adapted from an original academic-style article',
    paras: [
      'A. Roughly three out of four crops that we grow for food depend, to some degree, on animal pollinators — bees above all, but also butterflies, hoverflies, birds and bats. When a pollinator visits a flower, it moves pollen and the plant can set seed and fruit. Remove the visitors and yields fall, sometimes to zero. The UN Food and Agriculture Organization estimates that pollinator-dependent crops supply a large share of the vitamins and minerals in the global diet.',
      'B. Bee numbers, however, are under pressure from several directions at once. Intensive farming removes hedgerows and wildflowers that feed insects between crop blooms. Certain insecticides can disorient bees even in small doses. A parasitic mite that arrived in Europe in the twentieth century has since spread through managed hives worldwide, and warming winters disturb the timing between flowers and their pollinators.',
      'C. The consequences are not abstract. In parts of China, pear farmers now pollinate blossom by hand, dipping feather dusters into jars of pollen — slow, costly work that children once did and adults now perform. In the United States, commercial hives travel thousands of kilometres on trucks to meet the almond bloom, an extraordinary logistics operation that exists only because local wild bees can no longer do the job alone.',
      'D. Solutions exist, and they are less dramatic than the problem. Planting flower strips beside fields, rotating crops with nitrogen-fixing plants, timing pesticide sprays to evenings when bees are inactive, and leaving field margins unmown all measurably raise pollinator numbers. What they require is not new technology but coordination — between farmers who bear the cost, consumers who buy the produce and governments that set the rules.'
    ],
    heads: ['i. A worldwide logistics workaround', 'ii. Why fruits need animals', 'iii. Cheap fixes that need teamwork', 'iv. Pressures on pollinators'],
    vocab: [{ w: 'pollinator', d: 'an animal that moves pollen' }, { w: 'mite', d: 'a tiny parasite' }, { w: 'bloom', d: 'the flowering of a plant' }, { w: 'field margin', d: 'the unfarmed edge of a field' }],
    qs: [
      { t: 'heads', q: 'Choose the correct heading for Paragraph A.', opts: ['i', 'ii', 'iii', 'iv'], a: 1, exp: 'Paragraph A explains why fruits need animal pollinators.' },
      { t: 'heads', q: 'Choose the correct heading for Paragraph C.', opts: ['i', 'ii', 'iii', 'iv'], a: 0, exp: 'Hand pollination and trucked hives = worldwide logistics workaround.' },
      { t: 'tf', q: 'All food crops depend on animal pollinators.', a: 'FALSE', exp: 'The text says “three out of four” and “to some degree” — not all.' },
      { t: 'tf', q: 'A parasitic mite has spread through managed bee colonies.', a: 'TRUE', exp: '“has since spread through managed hives worldwide”.' },
      { t: 'mc', q: 'Why do US hives travel by truck?', opts: ['Because bees fly too slowly', 'Because wild bees can no longer pollinate the almonds alone', 'Because almonds grow only in China', 'To protect bees from mites'], a: 1, exp: '“exists only because local wild bees can no longer do the job alone”.' },
      { t: 'gap', q: 'Complete: Farmers in China pollinate pear blossom by hand using __________. (TWO WORDS)', accept: 'feather dusters', exp: '“dipping feather dusters into jars of pollen”.' },
      { t: 'gap', q: 'Spraying pesticides in the __________ reduces harm to bees. (ONE WORD)', accept: ['evening', 'evenings'], exp: '“timing pesticide sprays to evenings when bees are inactive”.' },
      { t: 'short', q: 'What do the solutions in Paragraph D mainly require, according to the writer? (ONE WORD)', accept: ['coordination', 'co-ordination'], exp: '“What they require is not new technology but coordination”.' }
    ] },
  { id: 'rg1', type: 'G', level: 'B1', topic: 'Workplace', title: 'Notices: Staff Training & Library Rules', src: 'Original General Training Section 1 texts',
    paras: [
      'NOTICE A — Riverside Logistics, Staff Training Day. All warehouse staff will attend a safety training day on Friday 14 March. Morning shift: training 9:00–12:00, lunch provided. Afternoon shift: training 13:00–16:00, snacks provided. Attendance is compulsory and will be recorded. If you cannot attend because of illness or approved leave, contact HR before Wednesday 12 March to rebook. Parking will be unavailable on site; please use the free shuttle from the sports centre car park, which runs every 15 minutes from 8:15. No public questions will be answered on the day — all queries must go through HR in advance.',
      'NOTICE B — City Central Library: Membership Rules. Membership is free for residents; non-residents pay £12 per year. Up to six items may be borrowed for three weeks; renewals are possible twice unless another member has reserved the item. Laptops may be borrowed for four hours with a valid photo ID and are for in-library use only. A fine of 20p per day applies to overdue books, with a maximum of £8 per item. Children under 12 must be accompanied by an adult. The reading rooms close ten minutes before the building.',
    ],
    qs: [
      { t: 'tf', q: 'Attendance at the training day is optional for warehouse staff.', a: 'FALSE', exp: '“Attendance is compulsory and will be recorded”.' },
      { t: 'tf', q: 'Staff who are on approved leave must rebook through HR before 12 March.', a: 'TRUE', exp: '“contact HR before Wednesday 12 March to rebook”.' },
      { t: 'tf', q: 'Parking is free at the warehouse on 14 March.', a: 'FALSE', exp: 'Parking is unavailable; a shuttle is offered instead.' },
      { t: 'tf', q: 'HR will answer questions about training on the day itself.', a: 'FALSE', exp: '“No public questions will be answered on the day”.' },
      { t: 'short', q: 'How often does the shuttle bus run? (use a number + minutes)', accept: ['every 15 minutes', '15 minutes'], exp: '“runs every 15 minutes from 8:15”.' },
      { t: 'tf', q: 'Non-residents pay a yearly fee for library membership.', a: 'TRUE', exp: '“non-residents pay £12 per year”.' },
      { t: 'short', q: 'How many items can a member borrow at once?', accept: ['six', '6'], exp: '“Up to six items may be borrowed”.' },
      { t: 'short', q: 'What is the maximum fine per overdue item? (in £)', accept: ['£8', '8', 'eight'], exp: '“a maximum of £8 per item”.' },
      { t: 'tf', q: 'Borrowed laptops may be taken home overnight.', a: 'FALSE', exp: '“for in-library use only”.' }
    ] },
  { id: 'rg2', type: 'G', level: 'B2', topic: 'Workplace', title: 'Flexible Working: An Employee Guide', src: 'Original General Training-style document',
    paras: [
      'A. Flexible working covers more than working from home. It includes compressed weeks (full hours over fewer days), staggered start times, job-sharing between two employees, and annualised hours where you work more in busy seasons and less in quiet ones. Since 2023, employees in the UK have had the right to request flexible arrangements from day one of a job, although employers can still refuse for business reasons.',
      'B. Before you apply, prepare the business case. Identify the impact on colleagues: who covers the phone at 9 a.m. if you start later? Propose a trial period of three months with clear success measures — customer response times, project deadlines — and offer to review after the trial. Managers approve requests that are specific and reversible far more often than vague ones.',
      'C. Compressed weeks suit people with long commutes: a four-day week of ten-hour days removes one commute and often one day of childcare costs. The trade-off is fatigue — ten-hour days erode concentration, and meetings scheduled late in the day tend to run over. Ask whether your role has fixed-time duties, such as opening the office or end-of-day banking, that cannot be compressed.',
      'D. Job-sharing works best when partners communicate in writing. Keep a shared handover document, agree one joint weekly meeting with your manager, and decide in advance who owns which tasks so customers always know whom to contact. Many job-sharers find the arrangement expands their careers rather than limiting them, because each partner brings a different strength to the role.'
    ],
    heads: ['i. Splitting one role between two people', 'ii. Longer days, fewer of them', 'iii. How to build your request', 'iv. What flexible working includes'],
    vocab: [{ w: 'compressed week', d: 'full hours worked in fewer days' }, { w: 'annualised hours', d: 'hours averaged over a year' }, { w: 'handover', d: 'transfer of work from one person to another' }],
    qs: [
      { t: 'heads', q: 'Choose the correct heading for Paragraph A.', opts: ['i', 'ii', 'iii', 'iv'], a: 3, exp: 'Paragraph A defines the range of flexible arrangements.' },
      { t: 'heads', q: 'Choose the correct heading for Paragraph C.', opts: ['i', 'ii', 'iii', 'iv'], a: 1, exp: 'Compressed weeks = longer days, fewer of them.' },
      { t: 'tf', q: 'UK employees can request flexible working only after two years in a job.', a: 'FALSE', exp: '“from day one of a job”.' },
      { t: 'tf', q: 'Employers must accept every flexible-working request.', a: 'FALSE', exp: '“employers can still refuse for business reasons”.' },
      { t: 'gap', q: 'Complete: Propose a trial of __________ months with clear success measures. (NUMBER in words)', accept: ['three', '3'], exp: '“a trial period of three months”.' },
      { t: 'mc', q: 'What is the main downside of compressed weeks mentioned in the text?', opts: ['Higher travel costs', 'Fatigue and weaker concentration', 'Childcare costs rise', 'Fixed-time duties'], a: 1, exp: '“ten-hour days erode concentration”.' },
      { t: 'gap', q: 'Job-sharers should keep a shared __________ document. (ONE WORD)', accept: ['handover', 'hand-over'], exp: '“Keep a shared handover document”.' },
      { t: 'short', q: 'How often should job-sharers meet their manager jointly? (ONE WORD)', accept: ['weekly', 'once a week'], exp: '“agree one joint weekly meeting with your manager”.' }
    ] }
];
/* Listening · TTS-read original scripts */
const IELTS_LISTEN = [
  { id: 'l1', part: 'Part 1', level: 'B1', title: 'Joining the University Sports Centre', az: 'Universitet idiom mərkəzinə qeydiyyat',
    script: 'ASSISTANT: Good morning — University Sports Centre. How can I help? | MARCO: Hi, I’m a new student and I’d like to join the gym. | ASSISTANT: Of course. Can I take your name? | MARCO: Marco Petrenko — P-E-T-R-E-N-K-O. | ASSISTANT: Thank you, Marco. And your student number? | MARCO: It’s S-2-0-4-1-1-7. | ASSISTANT: Great. We have two membership options: off-peak, which is £18 a month for weekdays before four, or full access at £26. | MARCO: I have most classes in the morning, so afternoons are fine. Off-peak, please. | ASSISTANT: Perfect. The off-peak membership includes the gym and the swimming pool, but court bookings cost extra — £4 per hour. | MARCO: And can I bring a guest sometimes? | ASSISTANT: Guests are welcome on Sundays for £6, but not on weekdays, I’m afraid. | MARCO: OK. When does the gym close? | ASSISTANT: Weekdays we close at ten, at weekends at eight. | MARCO: And is there a joining fee? | ASSISTANT: No joining fee this month — there’s a free induction session with a trainer instead. Would Wednesday at five suit you? | MARCO: Wednesday works. Thank you!',
    vocab: [{ w: 'off-peak', d: 'outside the busiest hours' }, { w: 'induction', d: 'an introduction session' }, { w: 'membership', d: 'being a member' }],
    qs: [
      { t: 'gap', q: 'Surname: __________', accept: 'petrenko', exp: 'Spelled out letter by letter: P-E-T-R-E-N-K-O.' },
      { t: 'gap', q: 'Student number: S-__________', accept: ['204117', '2 0 4 1 1 7'], exp: 'S-2-0-4-1-1-7.' },
      { t: 'gap', q: 'Membership type: __________ (one word)', accept: ['off-peak', 'offpeak'], exp: 'Marco chooses off-peak because classes end before four.' },
      { t: 'gap', q: 'Monthly cost: £__________', accept: ['18', '18.00', 'eighteen'], exp: 'Off-peak is £18 a month.' },
      { t: 'mc', q: 'Court bookings cost extra. How much per hour?', opts: ['£4', '£6', '£26', 'free'], a: 0, exp: '“court bookings cost extra — £4 per hour”.' },
      { t: 'mc', q: 'When can Marco bring a guest?', opts: ['Any weekday', 'Sundays only', 'Weekends only before noon', 'Never'], a: 1, exp: '“Guests are welcome on Sundays for £6”.' },
      { t: 'gap', q: 'Weekend closing time: __________ (number + o’clock)', accept: ['eight', '8', '8 o’clock', '8 oclock'], exp: '“at weekends at eight”.' },
      { t: 'short', q: 'What free session is included this month?', accept: ['induction', 'induction session', 'free induction'], exp: '“a free induction session with a trainer”.' }
    ] },
  { id: 'l2', part: 'Part 2', level: 'B2', title: 'Community Centre Open Day', az: 'İcmas mərkəzinin açıq günü',
    script: 'Welcome, everyone, to the annual open day for the Northgate Community Centre. Let me walk you through what’s new this year. The centre reopened in January after a nine-month refurbishment. The main hall now seats two hundred — double the previous capacity — and the floor has been sprung for dance classes, which is a big upgrade from concrete. Upstairs, the old storage rooms have become a recording studio, bookable by the hour at student rates. Outside, the car park has shrunk: forty spaces instead of sixty-five, because half the site became a community garden. Volunteers will grow vegetables there, and local schools will use it for science lessons. Now, timings: the centre opens at seven in the morning on weekdays and closes at ten; at weekends it’s nine to six. The café, run by a local charity, keeps shorter hours — ten to four only. Membership costs thirty pounds a year for adults, and under-sixteens join free with a guardian. Finally, please note that the centre is closed on bank holidays, but the garden stays open all year round.',
    vocab: [{ w: 'refurbishment', d: 'renovation' }, { w: 'sprung floor', d: 'a floor that absorbs impact for dance' }, { w: 'guardian', d: 'an adult responsible for a child' }],
    qs: [
      { t: 'mc', q: 'How long was the centre closed for refurbishment?', opts: ['Four months', 'Six months', 'Nine months', 'A year'], a: 2, exp: '“after a nine-month refurbishment”.' },
      { t: 'mc', q: 'What change was made to the main hall?', opts: ['It was made smaller', 'It got a sprung floor and doubled capacity', 'It became a studio', 'It closed for the year'], a: 1, exp: '“seats two hundred — double… the floor has been sprung”.' },
      { t: 'mc', q: 'Why did the car park get smaller?', opts: ['Part of the site became a garden', 'It was sold to a school', 'Flooding damaged it', 'The council took it over'], a: 0, exp: '“half the site became a community garden”.' },
      { t: 'mc', q: 'What are the weekend opening hours?', opts: ['7 a.m.–10 p.m.', '9 a.m.–6 p.m.', '10 a.m.–4 p.m.', '9 a.m.–10 p.m.'], a: 1, exp: '“at weekends it’s nine to six”.' },
      { t: 'match', q: 'Match: MAIN HALL', opts: ['sprung dance floor', 'bookable studio', 'forty spaces', 'run by a charity'], a: 0, exp: 'The main hall floor was “sprung for dance classes”.' },
      { t: 'match', q: 'Match: UPSTAIRS', opts: ['sprung dance floor', 'bookable studio', 'forty spaces', 'run by a charity'], a: 1, exp: '“a recording studio, bookable by the hour”.' },
      { t: 'match', q: 'Match: CAFÉ', opts: ['sprung dance floor', 'bookable studio', 'forty spaces', 'run by a charity'], a: 3, exp: '“The café, run by a local charity”.' },
      { t: 'gap', q: 'Adult membership costs £__________ a year.', accept: ['30', 'thirty'], exp: '“thirty pounds a year for adults”.' },
      { t: 'short', q: 'What stays open on bank holidays?', accept: ['the garden', 'garden', 'community garden'], exp: '“the garden stays open all year round”.' }
    ] },
  { id: 'l3', part: 'Part 3', level: 'B2+', title: 'Seminar: Reducing Food Waste on Campus', az: 'Seminar: kampusda yeyinti tullantıları',
    script: 'PROFESSOR: So, Aisha, Dan — your project on dining-hall waste. Aisha, you measured the trays. What did you find? | AISHA: The headline number is that about a fifth of the food served came back uneaten — but that hides huge variation. Pasta days were fine; curry days lost almost a third. | DAN: And portion size matters more than people assume. When the canteen switched to smaller bowls on one line, waste fell by a quarter without anyone complaining. | PROFESSOR: Interesting. What about the composting side? | AISHA: Composting works, but it’s the last resort in the hierarchy — better to prevent waste first, then donate surplus, then compost. | DAN: The charity link-up helped with that. Surplus sandwiches go to a shelter now, though we had to solve the labelling problem — dates printed in English only confused some staff. | PROFESSOR: What would you recommend to the university? | AISHA: Campaigns alone don’t work — posters had zero measurable effect. Pricing does: a small deposit on trays, refunded when returned, cut waste fastest. | DAN: And scheduling. Long queues at one o’clock mean the kitchen over-cooks. Splitting lunch into two sittings would fix it at source. | PROFESSOR: A promising pair of recommendations. Bring the data to the facilities committee.',
    vocab: [{ w: 'surplus', d: 'extra amount left over' }, { w: 'hierarchy', d: 'an ordered ranking' }, { w: 'sitting', d: 'one of several meal times' }],
    qs: [
      { t: 'gap', q: 'Roughly __________ of served food came back uneaten. (fraction)', accept: ['a fifth', '1/5', '20%'], exp: '“about a fifth of the food served came back uneaten”.' },
      { t: 'gap', q: 'Smaller bowls cut waste by about a __________. (fraction)', accept: ['quarter', '1/4', '25%'], exp: '“waste fell by a quarter”.' },
      { t: 'mc', q: 'What problem did the charity donation scheme hit?', opts: ['No volunteers', 'Single-language date labels', 'Cold food', 'Late deliveries'], a: 1, exp: '“dates printed in English only confused some staff”.' },
      { t: 'mc', q: 'Which intervention had ZERO measurable effect?', opts: ['Tray deposits', 'Smaller bowls', 'Poster campaigns', 'Two lunch sittings'], a: 2, exp: '“posters had zero measurable effect”.' },
      { t: 'match', q: 'Who said: portion size matters more than assumed?', opts: ['Aisha', 'Dan', 'The Professor'], a: 1, exp: 'Dan: “portion size matters more than people assume”.' },
      { t: 'match', q: 'Who said: composting is the last resort?', opts: ['Aisha', 'Dan', 'The Professor'], a: 0, exp: 'Aisha: “it’s the last resort in the hierarchy”.' },
      { t: 'short', q: 'What would fix over-cooking at source, according to Dan?', accept: ['two sittings', 'splitting lunch into two sittings', 'split lunch', 'two lunch sittings'], exp: '“Splitting lunch into two sittings would fix it at source”.' }
    ] }
];
/* Writing task bank */
const IELTS_WRITE = {
  a1: [
    { id: 'w1', type: 'Line graph', title: 'Museum Visitors (1990–2020)', prompt: 'The graph below shows the number of visitors to three museums in one city between 1990 and 2020. Summarise the information by selecting and reporting the main features, and make comparisons where relevant. Write at least 150 words.',
      data: 'History Museum: 1990: 300k → 2000: 520k → 2010: 480k → 2020: 700k. Science Centre: 1990: 150k → 2000: 350k → 2010: 610k → 2020: 640k. Art Gallery: 1990: 420k → 2000: 400k → 2010: 310k → 2020: 330k.',
      vocab: ['visitor numbers', 'a steady rise', 'peaked at', 'overtook', 'a sharp decline', 'by contrast', 'over the period', 'the most popular venue'],
      structures: ['X rose steadily from A to B.', 'Y overtook Z in + year.', 'Having remained stable, figures then…', 'The most striking feature is…'],
      guide: { intro: 'Paraphrase the prompt: change “shows” → “illustrates”, “visitors” → “attendance figures”.', body: 'Overview sentence first (no data): which museum ended highest? Then group the lines by trend, not year-by-year.', concl: 'Task 1 needs no conclusion — the overview is enough.', mistakes: ['Describing every year in order (mechanical).', 'Copying the prompt word-for-word.', 'Giving opinions or reasons — Task 1 has no “why”.'] },
      sample: 'The line graph illustrates attendance figures at three museums in a single city over a thirty-year period. Overall, the History Museum and the Science Centre grew substantially, while the Art Gallery steadily declined. In 1990, the Art Gallery was the most popular venue, attracting 420,000 visitors, whereas the Science Centre received only 150,000. However, the Science Centre’s numbers then climbed rapidly, overtaking the History Museum in 2010 at around 610,000 and finishing at 640,000. The History Museum followed a similar upward path, dipping slightly in 2010 before reaching 700,000 in 2020, the highest figure of the three. By contrast, the Art Gallery, after a stable start at roughly 400,000, fell to a low of 310,000 in 2010 and recovered only marginally thereafter. (≈155 words)' },
    { id: 'w2', type: 'Bar chart', title: 'Household Spending (two years)', prompt: 'The chart below shows household spending as a percentage of total spending in one country in 2000 and 2020. Summarise the information. Write at least 150 words.',
      data: 'Housing: 2000: 18% → 2020: 27%. Food: 24% → 17%. Transport: 15% → 13%. Leisure: 9% → 14%. Healthcare: 6% → 11%. Other: 28% → 18%.',
      vocab: ['proportion', 'accounted for', 'the largest segment', 'roughly a quarter', 'a doubling of', 'in contrast to'],
      structures: ['Spending on X accounted for A% in 2000, rising/falling to B% in 2020.', 'Housing overtook food as the largest category.', 'The proportion of income spent on X doubled.'],
      guide: { intro: 'State what the chart compares: two years, six categories, percentages.', body: 'Lead with the biggest change (housing up 9 points), then falls (food), then minor movers. Compare within a sentence, not list-like.', concl: 'End after the overview plus two grouped body paragraphs.', mistakes: ['Writing “27% in 2020 and 18% in 2000” for every category — grouping beats listing.', 'Confusing percentage points with per cent.'] },
      sample: 'The bar chart compares how households in one country allocated their spending across six categories in 2000 and 2020. Overall, housing replaced food as the largest single expense, while leisure and healthcare grew at the expense of “other” items. In 2000, food accounted for the biggest share at 24%, but by 2020 this had fallen to 17%. Housing moved in the opposite direction, climbing from 18% to 27% and overtaking food. Leisure expanded from 9% to 14%, and healthcare doubled its share to 11%, a change likely linked to ageing populations. Transport changed little, dipping from 15% to 13%. The “other” category shrank most dramatically, from 28% to 18%, suggesting that spending became concentrated in fewer areas over the two decades. (≈150 words)' },
    { id: 'w3', type: 'Process', title: 'How Chocolate Is Made', prompt: 'The diagram shows how chocolate is produced from cacao beans. Summarise the process. Write at least 150 words.',
      data: 'Stages: 1. Harvest cacao pods in tropical plantations → 2. Extract beans, ferment for a week → 3. Dry beans in the sun → 4. Pack and ship to factory → 5. Roast at high temperature → 6. Grind into cocoa liquor → 7. Mix with sugar and milk → 8. Mould and cool into bars → 9. Wrap and distribute.',
      vocab: ['in the initial stage', 'subsequently', 'at which point', 'is transferred to', 'the penultimate step', 'the finished product'],
      structures: ['First of all, the pods are harvested…', 'Once the beans have been fermented, they are dried…', 'Having been roasted, the beans are ground…', 'The process ends when the bars are wrapped.'],
      guide: { intro: 'One sentence: what the diagram shows and how many stages (nine).', body: 'Use present simple passive throughout. Group farm stages vs factory stages. Sequence words every sentence: initially, then, subsequently, finally.', concl: 'Finish with the final product in one clause.', mistakes: ['Active voice: “farmers dry beans” — prefer passive for processes.', 'Missing a stage — count them.', 'Adding invented details not in the diagram.'] },
      sample: 'The flow chart shows the nine stages involved in manufacturing chocolate, from harvesting cacao pods to distributing the finished bars. In the initial stage, cacao pods are harvested on tropical plantations, after which the beans are extracted and left to ferment for approximately one week. Subsequently, they are dried in the sun before being packed and shipped to a factory. The processing then begins: the beans are roasted at a high temperature and ground into a thick paste known as cocoa liquor. In the penultimate stage, this liquor is blended with sugar and milk to create the chocolate mixture, which is moulded into bars and cooled. Finally, the bars are wrapped and distributed to retailers, completing the transformation from farm crop to consumer product. (≈140 words)' },
    { id: 'w4', type: 'Pie charts', title: 'Energy Use in Homes (two decades)', prompt: 'The pie charts show how energy was used in homes in one country in 2000 and 2020. Summarise the information. Write at least 150 words.',
      data: '2000: Heating 55%, Water heating 20%, Lighting 10%, Appliances 15%. 2020: Heating 40%, Water heating 18%, Lighting 4%, Appliances 38%.',
      vocab: ['the largest share', 'accounted for over half', 'more than doubled', 'a dramatic increase in', 'remained relatively stable'],
      structures: ['Heating accounted for over half of all use in 2000.', 'The share devoted to appliances more than doubled.', 'By contrast, lighting became almost negligible.'],
      guide: { intro: 'Paraphrase: “how residential energy was consumed in two separate years.”', body: 'Overview: heating lost its dominance to appliances. Body 1: 2000 picture. Body 2: 2020 changes, biggest first.', concl: 'No opinion; a final comparative sentence is fine.', mistakes: ['Listing each slice separately without comparing.', 'Writing “38% in 2020 and 15% in 2000” — merge into one sentence about growth.'] },
      sample: 'The pie charts compare residential energy consumption in one country across two decades, 2000 and 2020. Overall, space heating lost its dominance, while appliances grew to become the single largest consumer of household energy. In 2000, heating accounted for the majority of use at 55%, followed by water heating at 20% and appliances at just 15%. Lighting represented one-tenth. Twenty years later, the picture had changed markedly: the heating share fell to 40%, water heating remained relatively stable at 18%, and lighting shrank to a negligible 4%, presumably due to LED technology. The most striking change concerned appliances, whose share more than doubled to 38%, overtaking all other categories. This shift suggests that digital devices, rather than heating systems, now drive household electricity demand. (≈145 words)' } ],
  a2: [
    { id: 'e1', type: 'Opinion essay', title: 'Free University Education', prompt: 'Some people believe university education should be free for all students, while others think students should pay for their own studies. Discuss both views and give your own opinion. Write at least 250 words.',
      vocab: ['tuition-free', 'a broader tax base', 'human capital', 'to foot the bill', 'a return on investment', 'upward mobility'],
      structures: ['While it is true that…, I would argue that…', 'The principal argument in favour of… is that…', 'Critics counter this by pointing out that…', 'On balance, …'],
      guide: { intro: 'Paraphrase both views in one sentence, then state your position clearly in the thesis.', body: 'One paragraph per view: strongest argument + example + mini-conclusion. Your view can be one of the two or a middle position.', concl: 'Restate position in fresh words; add one implication.', mistakes: ['Only discussing the view you agree with.', 'Personal stories instead of general examples.', 'Starting sentences with “Also, and, but” repeatedly.'] },
      sample: 'Whether the state or the individual should fund university degrees divides opinion. Some argue that free tuition widens access, while others insist that graduates, who profit most, should pay. I believe a mixed model serves societies best. The case for free education rests on equality of opportunity. When tuition is free, admission depends on ability rather than family wealth, and countries cultivate talent that would otherwise remain untapped. Germany’s tuition-free universities, for example, draw able students from modest backgrounds who become the engineers and teachers of the next generation. Opponents reply that someone must foot the bill, and that graduates earn substantially more over a lifetime than non-graduates. Charging fees, they argue, is fair because students repay a share of their future advantage; free degrees simply transfer costs to taxi drivers who never attended. This is compelling, yet income-contingent loans — repaid only above a salary threshold — achieve the same fairness without deterring the poor. On balance, therefore, universities should be accessible to all, but the fairest mechanism is graduate repayment linked to income, not free tuition for everyone. (≈200 words)' },
    { id: 'e2', type: 'Discussion essay', title: 'Remote Work: Permanent Shift?', prompt: 'Working from home has become normal in many industries. Do the advantages of remote work outweigh the disadvantages? Write at least 250 words.',
      vocab: ['commuting time', 'productivity gains', 'social isolation', 'blurred boundaries', 'hot-desking', 'city-centre economies'],
      structures: ['The most obvious benefit of… is…', 'A further advantage concerns…', 'Nevertheless, this arrangement carries risks…', 'Weighing both sides, …'],
      guide: { intro: 'Name the trend, then state clearly whether advantages outweigh disadvantages.', body: 'Para 2: two advantages with development. Para 3: two disadvantages. Do not list five shallow points — develop two properly.', concl: 'Your verdict: often depends on role, industry or personality.', mistakes: ['Ignoring who the essay is for (a general reader, not your teacher).', 'Contradicting your own thesis in the conclusion.'] },
      sample: 'Remote work has moved from perk to policy in a single decade, and opinions remain divided over its net effect. This essay argues that its advantages outweigh its drawbacks for most knowledge workers, though not without real costs. The clearest gain is time. Eliminating the daily commute returns, for many employees, an hour or more each day — time that surveys show is spent on sleep, exercise and family rather than work. Firms benefit too: they recruit from anywhere and reduce expensive city-centre office space, and several studies report stable or higher productivity for remote teams. However, the disadvantages are equally concrete. New hires learn workplace culture more slowly through screens, and social isolation is now a recognised occupational risk. Boundaries also blur: when the laptop sits on the kitchen table, work expands into evenings, and burnout can follow. These effects fall unevenly — junior staff and extroverts suffer most. On balance, the advantages prevail, provided employers deliberately rebuild the connection that offices once provided through mentoring and occasional in-person collaboration. The future, in short, is hybrid rather than wholly remote. (≈190 words)' },
    { id: 'e3', type: 'Advantages/disadvantages', title: 'Tourism and Local Communities', prompt: 'International tourism brings money to local communities but can also damage them. What are the advantages and disadvantages of tourism for local people? Write at least 250 words.',
      vocab: ['a source of income', 'seasonal employment', 'cultural exchange', 'overtourism', 'the cost of living', 'infrastructure strain'],
      structures: ['Tourism generates…', 'One drawback is that…', 'This can lead to…', 'Unless it is managed carefully, …'],
      guide: { intro: 'Do not give your opinion here — the question asks for advantages AND disadvantages.', body: 'Para 2: advantages (jobs, income, cultural pride). Para 3: disadvantages (seasonality, prices, crowding).', concl: 'A balanced summary; you may suggest that management determines the outcome.', mistakes: ['Turning it into an opinion essay.', 'Generic examples — name a real place or type of place.'] },
      sample: 'International tourism has become a lifeline for many communities, yet its effects are far from uniformly positive. This essay considers both sides before suggesting that management, not tourism itself, decides the outcome. The advantages are immediate and visible. Tourist spending creates jobs — in hotels, guiding, transport and crafts — that often pay better than farming or fishing in the same region. It can also finance heritage: ticket revenues from Angkor Wat or Machu Picchu fund conservation that local taxes alone could never afford. Cultural pride may grow too, as festivals and crafts that were fading find enthusiastic new audiences. The disadvantages, however, are equally real. Employment is frequently seasonal, leaving families with lean months and no security. In popular cities, short-term rentals push up rents and drive residents from their own neighbourhoods, while crowded streets erode the very atmosphere that attracted visitors. Venice and Barcelona illustrate how quickly enthusiasm can turn to protest. In conclusion, tourism delivers income and cultural vitality, but only careful management — limits on numbers, local ownership rules, off-season promotion — ensures that the benefits reach residents rather than flowing past them. (≈185 words)' },
    { id: 'e4', type: 'Problem/solution', title: 'Plastic Pollution in Oceans', prompt: 'Plastic waste in the world’s oceans is a growing problem. What are the main causes of this problem, and what solutions can you suggest? Write at least 250 words.',
      vocab: ['single-use plastics', 'waste management', 'runoff', 'decompose', 'a deposit-refund scheme', 'enforcement'],
      structures: ['The root of the problem lies in…', 'One promising solution would be to…', 'If governments invested in…, this would…', 'Individuals also have a part to play by…'],
      guide: { intro: 'Define the problem briefly; state that causes and solutions will be examined.', body: 'Para 2: two causes, developed (packaging culture + weak waste systems). Para 3: two solutions matched to those causes.', concl: 'Brief; note that solutions need both governments and individuals.', mistakes: ['Listing four causes in one sentence — depth beats breadth.', 'Vague solutions (“we should all try harder”).'] },
      sample: 'Every year, millions of tonnes of plastic enter the ocean, harming wildlife and entering the food chain. This essay examines two principal causes and proposes matching solutions. The first cause is our dependence on single-use packaging. Bottles, bags and wrappers are used for minutes yet persist for centuries, and they escape into rivers during every rainstorm. The second is inadequate waste management: in many fast-growing cities, collection simply fails to keep pace with consumption, so refuse is dumped or burned near waterways. Both problems are solvable with policies that already exist. Deposit-refund schemes, which charge a small sum on bottles and return it on recycling, have lifted collection rates above ninety per cent in several countries; extending them to all packaging would remove the main source of ocean plastic. Meanwhile, investment in formal waste collection — bins, trucks and sorting plants — would stop the leakage in expanding cities. International funds could pay for this, since plastic pollution crosses borders with the currents. In conclusion, the ocean plastic problem stems from disposable packaging and weak infrastructure. The remedies are proven and affordable; what is missing, largely, is political will and enforcement. (≈195 words)' },
    { id: 'e5', type: 'Two-part question', title: 'Children and Screens', prompt: 'Children today spend many hours looking at screens. Why is this the case, and should parents limit this time? Give reasons and relevant examples. Write at least 250 words.',
      vocab: ['peer pressure', 'a default activity', 'unsupervised browsing', 'screen-free', 'moderation', 'parental controls'],
      structures: ['There are two main reasons why…', 'The first is that…, and the second…', 'In my view, limits are justified provided that…', 'Rather than banning outright, parents should…'],
      guide: { intro: 'Answer BOTH questions in the thesis — why, and whether to limit.', body: 'Para 2: reasons (devices are cheap and everywhere; screens are the default babysitter and social space). Para 3: your position on limits with conditions.', concl: 'One sentence: moderation with structure beats both extremes.', mistakes: ['Answering only one of the two questions.', 'Moralising without examples.'] },
      sample: 'Screens dominate children’s free time to an extent previous generations would find strange. This essay explores the causes of the trend and argues that sensible limits are justified. Two forces explain the shift. First, devices are now cheap, portable and universal: the tablet that entertains a toddler is the same one older siblings use for homework. Second, screens have become the default social space — children chat, game and watch together online, so restricting devices risks cutting them off from their friends, a pressure parents feel keenly. Should parents therefore intervene? In my view, yes, but with structure rather than blanket bans. Unsupervised browsing exposes children to advertising and, occasionally, harmful content, and late-night use demonstrably damages sleep and concentration at school. Effective limits are those children understand: screens out of bedrooms, devices parked during meals, and content chosen together. Families in which parents follow the same rules report fewer conflicts, suggesting the example matters more than the prohibition. In conclusion, screens have filled the vacuum left by shrinking public play spaces and the pull of online friendship. Parents should limit them — but through consistent household routines that teach moderation, not through bans that simply push usage out of sight. (≈200 words)' } ],
  gt1: [
    { id: 'f1', type: 'Formal letter', title: 'Complaint to a Landlord', prompt: 'You rent a flat and the heating has not worked for two weeks. Write a letter to your landlord. In your letter: explain the problem, describe how it affects you, and say what action you would like. Write at least 150 words. Begin: Dear Mr…,',
      vocab: ['I am writing to bring to your attention', 'despite repeated requests', 'render the flat uninhabitable', 'I would appreciate it if', 'at your earliest convenience'],
      structures: ['I am writing regarding…', 'This has resulted in…', 'Could you please arrange for…', 'I look forward to your prompt reply.'],
      guide: { intro: 'State purpose in line one — formal letters waste no time.', body: 'One paragraph per bullet: facts, effects, requested action with a deadline.', tone: 'Firm but courteous; no contractions, no anger.', mistakes: ['Using “Hi” or contractions in a formal letter.', 'Threatening legal action immediately.'] },
      sample: 'Dear Mr Hale, I am writing to bring to your attention a serious problem with the heating system at Flat 4, 12 Beechwood Road, which has now been out of service for two weeks. Despite the radiators being checked by a neighbour last winter, they have produced no heat at all since 3 November, and repeated calls to the number you left have gone unanswered. The effect on my family has been considerable. We are heating rooms with electric heaters, which is both unsafe and expensive, and my daughter has missed two days of school with a cold. Under our tenancy agreement, heating must be maintained in working order throughout the winter months. I would therefore appreciate it if you could arrange for a qualified engineer to visit within five working days. If the system cannot be repaired promptly, I would ask you to provide alternative accommodation or a rent reduction for the affected period. I look forward to your prompt reply. Yours sincerely, Elena Rustamova (≈165 words)' },
    { id: 'f2', type: 'Semi-formal letter', title: 'Thanking a Host Family', prompt: 'You recently stayed with a host family while studying abroad. Write a letter to thank them. In your letter: remind them when you stayed, mention something you especially enjoyed, and invite them to visit you. Write at least 150 words. Begin: Dear…,',
      vocab: ['it was a pleasure to stay', 'made me feel at home', 'I still think about', 'if your travels ever bring you', 'do let me know'],
      structures: ['Thank you so much for…', 'I particularly enjoyed…', 'You would always be welcome to…', 'Please give my regards to…'],
      guide: { intro: 'Warm opening; you know them, but this is still a letter, not a text message.', body: 'Specific memories beat generic thanks: name the meal, the trip, the help with English.', tone: 'Friendly, some contractions acceptable.', mistakes: ['Being too formal and distant.', 'Forgetting one of the three bullet points.'] },
      sample: 'Dear Marta and Tomas, I have been back in Baku for two weeks now, but I still think about my month with you every day. Staying with your family from 2 to 30 July was the best part of my language course. I particularly enjoyed our Sunday walks along the river and our long dinners, where you patiently corrected my grammar between jokes — that is how I really learned to speak. Thank you as well for taking me to your village festival; I have told everyone here about the music and the homemade cakes. If your travels ever bring you to Azerbaijan, you must stay with us. My parents would love to meet the family who looked after their daughter, and I promise to show you the old city at sunset, just as you showed me yours. Do let me know your plans — my home is your home. With warm wishes, Aysel (≈155 words)' },
    { id: 'f3', type: 'Informal letter', title: 'Advice to a Friend Moving Abroad', prompt: 'A friend is moving to your city to study and has asked for advice about finding somewhere to live. Write a letter. In your letter: suggest an area, warn about something, and offer to help. Write at least 150 words. Begin: Dear…,',
      vocab: ['great news about', 'you’ll be spoiled for choice', 'watch out for', 'noisy at weekends', 'just say the word'],
      structures: ['I was thrilled to hear that…', 'I’d recommend… because…', 'One thing to watch out for is…', 'Let me know when you’re arriving and…'],
      guide: { intro: 'Congratulate, react to their news — personality is allowed.', body: 'Practical detail: real area names or types, real pitfalls (scams, deposits, winter).', tone: 'Chatty, contractions, exclamation marks sparingly.', mistakes: ['Formal sign-off “Yours faithfully” — use “Love/Best/See you soon”.', 'No structure at all — informal ≠ disorganised.'] },
      sample: 'Dear Nurlan, Great news about the master’s — congratulations! You asked about finding a flat, so here’s what I know. Look at Fountain Row or the streets behind the tram stop: ten minutes from campus, loads of shared flats, and rents are about a third lower than near the seafront. Avoid anything advertised “five minutes from everything” — I learned that means five minutes by car at 3 a.m. Watch out for deposit scams: never transfer money before viewing, and get a proper contract even if the landlord is friendly — mine wasn’t, and I lost two months’ rent. Also, book early; by September the good rooms vanish. When you arrive, I’ll help you view flats and translate anything confusing — I’m free the whole first week of September. Bring winter clothes you actually like, by the way. It gets seriously cold here, and you’ll be outside a lot. Just say the word when your dates are fixed! See you soon, Kamran (≈160 words)' } ]
};
/* Speaking banks */
const IELTS_SPEAK = {
  p1: [
    { topic: 'Home & hometown', qs: ['Where are you from?', 'Do you live in a house or a flat?', 'What do you like most about your hometown?', 'Has your hometown changed much recently?'], az: 'Ev və doğma şəhər', tip: 'Add one detail + one feeling to each answer.' },
    { topic: 'Work or studies', qs: ['Do you work or are you a student?', 'Why did you choose this field?', 'What is the best thing about it?', 'Would you change anything about it?'], az: 'İş və ya təhsil', tip: 'Use present perfect: “I’ve been studying X for…”.' },
    { topic: 'Free time', qs: ['What do you do in your free time?', 'Did you have the same hobbies as a child?', 'Do you prefer indoor or outdoor activities?', 'Is there a hobby you would like to start?'], az: 'Boş vaxt', tip: 'Use “used to” for childhood habits.' },
    { topic: 'Food & cooking', qs: ['What is a typical dish from your country?', 'Can you cook?', 'Have eating habits in your country changed?', 'Do you prefer eating at home or eating out?'], az: 'Yemək və aşpazlıq', tip: 'One example per answer keeps fluency natural.' },
    { topic: 'Weather & seasons', qs: ['What’s the weather like in your country?', 'Which season do you enjoy most?', 'Does weather affect your mood?', 'Has climate change been noticeable where you live?'], az: 'Hava və fəsillər', tip: 'Compare: “Unlike the coast, inland summers are…”. ' },
    { topic: 'Technology habits', qs: ['How often do you use your phone?', 'What app could you not live without?', 'Has technology changed how you meet friends?', 'Would you like less screen time?'], az: 'Texnologiya vərdişləri', tip: 'Adverbs of frequency upgrade Part 1 instantly.' } ],
  p2: [
    { card: 'Describe a person who has influenced you.', bullets: ['who this person is', 'how you know them', 'what they have done', 'and explain why they have influenced you'], theme: 'People', follow: ['Are famous people good role models?', 'Who influences young people most — parents or friends?'] },
    { card: 'Describe a skill you learned recently.', bullets: ['what the skill is', 'why you learned it', 'how you learned it', 'and explain how you feel about it now'], theme: 'Learning', follow: ['Are some skills easier to learn as an adult?', 'Should schools teach practical life skills?'] },
    { card: 'Describe a place you like to visit to relax.', bullets: ['where it is', 'how often you go', 'what you do there', 'and explain why it helps you relax'], theme: 'Places', follow: ['Why is access to green space unequal in cities?', 'Do people relax differently from 30 years ago?'] },
    { card: 'Describe a book, film or article that impressed you.', bullets: ['what it was', 'when you encountered it', 'what it was about', 'and explain why it impressed you'], theme: 'Culture', follow: ['Will printed books survive?', 'Should governments fund the arts?'] },
    { card: 'Describe a time when you solved a problem online.', bullets: ['what the problem was', 'how you found the solution', 'what tools you used', 'and explain what you learned from it'], theme: 'Technology', follow: ['Do we depend too much on search engines?', 'Is everything online trustworthy?'] },
    { card: 'Describe a tradition in your country.', bullets: ['what the tradition is', 'when it happens', 'what people do', 'and explain why it is important'], theme: 'Society', follow: ['Are traditions disappearing?', 'Should traditions adapt to modern life?'] } ],
  p3: [
    { theme: 'Education & society', qs: ['Should university education be free for everyone?', 'How might AI change what schools teach?', 'Why do some students learn better outside classrooms?', 'Is a degree still the best path to a good job?'], az: 'Təhsil və cəmiyyət' },
    { theme: 'Environment', qs: ['Who bears most responsibility for climate change — governments, companies or individuals?', 'Are “green” lifestyles only for the wealthy?', 'Should polluting flights be taxed more heavily?', 'Can technology solve environmental problems it helped create?'], az: 'Ekologiya' },
    { theme: 'Technology & media', qs: ['Should there be an age limit for social media?', 'How can people judge online information?', 'Will traditional journalism disappear?', 'Does constant connectivity improve or harm relationships?'], az: 'Texnologiya və media' },
    { theme: 'Work & the future', qs: ['Will robots take most jobs within our lifetime?', 'Is a four-day working week realistic?', 'Why do people value job security less than before?', 'Should retirement ages rise as lifespans increase?'], az: 'İş və gələcək' } ],
  phrases: { fillers: ['That’s an interesting question…', 'Let me think for a second…', 'Well, in my case…'], opinion: ['If you ask me, …', 'Personally, I’d say…', 'From my perspective…'], examples: ['A good example of this is…', 'Take my cousin, for instance…', 'I remember when…'], contrast: ['Having said that, …', 'On the flip side, …', 'That said, it depends on…'] },
  strategies: [
    { t: 'Never memorise scripts', az: 'Hazır mətn əzbərləmə', d: 'Examiners spot rehearsed answers and mark down on memorised language. Learn phrases and structures, not paragraphs.' },
    { t: 'Buy thinking time naturally', az: 'Fikirləşmək üçün vaxt qazan', d: '“That’s an interesting question — let me think…” is a real phrase native speakers use. Silence costs fluency marks; fillers don’t.' },
    { t: 'Extend, then justify', az: 'Genişləndir və əsaslandır', d: 'Formula: answer → reason → example. “Yes, I do — mainly because it helps me switch off. Last weekend, for instance, …”' },
    { t: 'Self-correct calmly', az: 'Sakitcə düzəlt', d: 'Fixing your own mistake (“…in 2019 — sorry, 2018”) shows awareness and protects Grammar marks far more than it costs Fluency.' },
    { t: 'Record, listen, repeat', az: 'Yazıb dinlə, təkrar et', d: 'Record your Part 2 answer, count your fillers (“eeem”), re-record. Two recordings per topic per week measurably raise fluency.' }
  ],
  criteria: [
    { c: 'Fluency & Coherence', d: 'Can you keep going, connect ideas, and avoid long pauses?', self: ['I spoke for the full time', 'I used linking words naturally', 'I avoided long silences'] },
    { c: 'Lexical Resource', d: 'Range of vocabulary: topic words, collocations, idioms used naturally.', self: ['I used at least 3 topic words', 'I used a collocation or two', 'I paraphrased instead of repeating'] },
    { c: 'Grammatical Range & Accuracy', d: 'Mix of simple and complex sentences; error frequency.', self: ['I used a conditional or two', 'I self-corrected when needed', 'Past tenses were accurate'] },
    { c: 'Pronunciation', d: 'Clarity, stress, intonation — accent itself is not penalised.', self: ['I stressed key words', 'My intonation rose and fell', 'A listener would understand every word'] }
  ]
};
/* Standalone question-bank pool (metadata-driven; extend freely) */
const IELTS_POOL = [
  { id: 'p1', skill: 'Grammar', testType: 'Both', section: 'Grammar for IELTS', part: '', questionType: 'Error correction', difficulty: 'B1', topic: 'Subject–verb agreement', q: 'The number of international students ___ every year since 2015.', opts: ['increase', 'has increased', 'have increased'], a: 1, exp: '“The number of…” is singular; “since 2015” needs present perfect.', az: '“The number of” təkdür — present perfect gəlir.' },
  { id: 'p2', skill: 'Grammar', testType: 'Both', section: 'Grammar for IELTS', part: '', questionType: 'Error correction', difficulty: 'B2', topic: 'Conditionals', q: 'If the government ___ last year, prices would be lower now.', opts: ['acted', 'had acted', 'acts'], a: 1, exp: 'Unreal past condition + present result → past perfect (mixed conditional).', az: 'Qarışıq şərt: If + had done, would + do.' },
  { id: 'p3', skill: 'Grammar', testType: 'Both', section: 'Grammar for IELTS', part: '', questionType: 'Sentence completion', difficulty: 'B2', topic: 'Relative clauses', q: 'The factory ___ we visited last week employs 300 people.', opts: ['which', 'where', 'that'], a: 2, exp: '“Visited” takes a direct object → defining “that” (or “which”) — not “where”.', az: '“Visit” birbaşa obyekt alır, “where” düz gəlmir.' },
  { id: 'p4', skill: 'Grammar', testType: 'Both', section: 'Grammar for IELTS', part: '', questionType: 'Error correction', difficulty: 'B1', topic: 'Prepositions', q: 'Sales rose significantly ___ 2019 ___ 2021.', opts: ['from / to', 'since / until', 'at / at'], a: 0, exp: 'Point-to-point ranges use “from … to …”.', az: 'Aralıq: from … to …' },
  { id: 'p5', skill: 'Grammar', testType: 'Both', section: 'Grammar for IELTS', part: '', questionType: 'Error correction', difficulty: 'B2', topic: 'Passive voice', q: 'The survey ___ by more than 2,000 residents last spring.', opts: ['completed', 'was completed', 'was completing'], a: 1, exp: 'Past simple passive: was + past participle.', az: 'Keçmiş məchul: was completed.' },
  { id: 'p6', skill: 'Grammar', testType: 'Both', section: 'Grammar for IELTS', part: '', questionType: 'Sentence completion', difficulty: 'B2+', topic: 'Hedging', q: 'Remote work ___ to reduce commuting costs in most sectors.', opts: ['definitely proves', 'appears', 'is proving impossible'], a: 1, exp: 'Academic writing hedges: “appears to reduce” avoids overclaiming.', az: 'Elmi yazıda “appears/tends to” işlədin.' },
  { id: 'p7', skill: 'Vocabulary', testType: 'Both', section: 'Vocabulary', part: '', questionType: 'Word choice', difficulty: 'B1', topic: 'Environment', q: 'The city plans to ___ carbon emissions by 40% before 2035.', opts: ['cut down', 'curb', 'cancel'], a: 1, exp: '“Curb emissions” is the standard collocation.', az: '“Curb emissions” — emissiyanı cilovlamaq.' },
  { id: 'p8', skill: 'Vocabulary', testType: 'Both', section: 'Vocabulary', part: '', questionType: 'Word choice', difficulty: 'B2', topic: 'Economy', q: 'Rising interest rates are designed to ___ inflation.', opts: ['harm', 'curb', 'improve'], a: 1, exp: 'Curb = restrain. Central banks curb inflation.', az: 'Mərkəzi banklar inflyasiyanı cilovlayır.' },
  { id: 'p9', skill: 'Vocabulary', testType: 'Both', section: 'Vocabulary', part: '', questionType: 'Collocation', difficulty: 'B2', topic: 'Technology', q: 'New battery technology could ___ petrol cars obsolete.', opts: ['make', 'do', 'put'], a: 0, exp: '“Render/make something obsolete” — not “do”.', az: '“Make obsolete” — köhnəldib çıxartmaq.' },
  { id: 'p10', skill: 'Vocabulary', testType: 'Both', section: 'Vocabulary', part: '', questionType: 'Word choice', difficulty: 'B1+', topic: 'Health', q: 'A ___ lifestyle is a major risk factor for heart disease.', opts: ['sedentary', 'secluded', 'settled'], a: 0, exp: 'Sedentary = sitting, inactive.', az: 'Sedentary = oturaq.' },
  { id: 'p11', skill: 'Vocabulary', testType: 'Both', section: 'Vocabulary', part: '', questionType: 'Collocation', difficulty: 'B2+', topic: 'Education', q: 'The report recommends placing greater ___ on vocational training.', opts: ['emphasis', 'emphasise', 'emphatic'], a: 0, exp: 'Noun needed: “place emphasis on”.', az: '“Place emphasis on” — vurğu qoymaq.' },
  { id: 'p12', skill: 'Vocabulary', testType: 'Both', section: 'Vocabulary', part: '', questionType: 'Word choice', difficulty: 'B2', topic: 'Society', q: 'Migration can ___ social tensions if housing is scarce.', opts: ['light', 'heighten', 'high'], a: 1, exp: '“Heighten tensions” is the fixed collocation.', az: '“Heighten tensions” — gərginliyi artırmaq.' }
];
/* Build unified question bank with metadata (add questions to sources above; they flow in automatically) */
function buildIELTSQB() {
  const qb = [];
  IELTS_POOL.forEach(q => qb.push(q));
  IELTS_GRAM.forEach(g => g.quiz.forEach((q, i) => qb.push({ id: g.id + '-q' + i, skill: 'Grammar', testType: 'Both', section: 'Grammar for IELTS', part: '', questionType: 'Multiple choice', difficulty: g.band === 'Foundation' ? 'B1' : g.band === 'Intermediate' ? 'B2' : g.band === 'Upper-Intermediate' ? 'B2+' : 'C1', topic: g.t, q: q.q, opts: q.opts, a: q.a, exp: q.exp })));
  IELTS_READ.forEach(p => p.qs.forEach((q, i) => { if (q.t === 'mc' || q.t === 'tf') qb.push({ id: p.id + '-q' + i, skill: 'Reading', testType: p.type === 'A' ? 'Academic' : 'General', section: 'Reading', part: p.title, questionType: q.t === 'tf' ? 'True/False/Not Given' : 'Multiple choice', difficulty: p.level, topic: p.topic, q: q.q, opts: q.t === 'tf' ? ['TRUE', 'FALSE', 'NOT GIVEN'] : q.opts, a: q.t === 'tf' ? (q.a === 'TRUE' ? 0 : 1) : q.a, exp: q.exp }); }));
  IELTS_LISTEN.forEach(l => l.qs.forEach((q, i) => { if (q.t === 'mc') qb.push({ id: l.id + '-q' + i, skill: 'Listening', testType: 'Both', section: 'Listening', part: l.part, questionType: 'Multiple choice', difficulty: l.level, topic: l.title, q: q.q, opts: q.opts, a: q.a, exp: q.exp }); }));
  return qb;
}
const IELTS_QB = buildIELTSQB();
