/* ============ IELTS PRO · Data layer (scalable — add items here) ============ */
/* Each question: { id, skill, testType, section, part, questionType, difficulty, topic, q, opts?, a (index or accepted-string), exp, az? } */
const IELTS_INFO = {
  what: 'IELTS (International English Language Testing System) is the world’s most widely used English test for study, work and migration. It assesses your ability to listen, read, write and speak in English through a face-to-face speaking test and written papers. Over 12,000 organisations — universities, employers and governments — accept IELTS results. There is no “pass” or “fail”: you receive a band score from 1 (non-user) to 9 (expert user) for each skill and an overall band. This site offers ORIGINAL practice material inspired by the exam format — it is not affiliated with IELTS officials, and all practice results here are estimates, not official IELTS scores.',
  types: [
    { t: 'IELTS Academic', az: 'IELTS Akademik', d: 'For university admission and professional registration. Reading and Writing use academic contexts: articles, charts, graphs, processes and formal essays.', who: 'Choose this if you plan to study at university or register with a professional body (medicine, nursing, engineering).' },
    { t: 'IELTS General Training', az: 'IELTS Genel', d: 'For migration, secondary education and work experience. Reading and Writing use everyday and workplace contexts: notices, ads, staff documents and letters.', who: 'Choose this for immigration to the UK, Canada, Australia or New Zealand, or for non-degree training.' }
  ],
  sections: [
    { n: 'Listening', icon: '🎧', time: '≈ 30 min + 10 min transfer', parts: 4, qs: 40, az: 'Dinləmə', d: 'Four recorded monologues and conversations. Part 1: everyday social conversation (form completion). Part 2: social monologue (maps, matching). Part 3: academic discussion (2–4 speakers). Part 4: academic lecture (notes completion).' },
    { n: 'Reading', icon: '📚', time: '60 min', parts: 3, qs: 40, az: 'Oxu', d: 'Academic: three long extracts from books, journals and newspapers. General Training: everyday notices, workplace documents and one descriptive text. No extra transfer time — answers go straight onto the answer sheet.' },
    { n: 'Writing', icon: '✍️', time: '60 min', parts: 2, qs: 2, az: 'Yazı', d: 'Task 1 (Academic: describe a chart, graph, table, process or map · General Training: write a formal, semi-formal or informal letter) in about 20 minutes, minimum 150 words. Task 2: an essay in about 40 minutes, minimum 250 words. Task 2 counts twice as much.' },
    { n: 'Speaking', icon: '🗣️', time: '11–14 min', parts: 3, qs: '—', az: 'Danışiq', d: 'A face-to-face interview with a certified examiner. Part 1: introduction and everyday questions (4–5 min). Part 2: long turn with a cue card, 1 minute to prepare and up to 2 minutes to speak. Part 3: two-way abstract discussion linked to Part 2 (4–5 min).' }
  ],
  bands: [
    { b: '9', n: 'Expert user', d: 'Fully operational command; accurate and fluent with complete understanding.' },
    { b: '8', n: 'Very good user', d: 'Fully operational with only occasional unsystematic inaccuracies.' },
    { b: '7', n: 'Good user', d: 'Operational command with occasional inaccuracies; handles complex language well.' },
    { b: '6', n: 'Competent user', d: 'Generally effective command despite some inaccuracies; uses fairly complex language.' },
    { b: '5', n: 'Modest user', d: 'Partial command; copes with overall meaning in most situations, though mistakes occur.' },
    { b: '4', n: 'Limited user', d: 'Basic competence limited to familiar situations.' }
  ],
  scoring: 'Each of the four skills receives a whole or half band (e.g. 6.5). The overall band is the average of the four, rounded to the nearest half band: if the average ends in .25 it rounds UP to .5, and .75 rounds UP to the next whole band. Example: L 6.5, R 7.0, W 6.0, S 7.0 → average 6.625 → 6.5. Example: L 6.5, R 6.5, W 5.5, S 6.0 → average 6.125 → 6.0. Listening and Reading bands come from your raw score out of 40 using published conversion tables (see the Band Calculator). Writing and Speaking are assessed by trained examiners against four published criteria.',
  cefr: 'Approximate relationship (unofficial guidance): Band 4.0–5.0 ≈ B1 · 5.5–6.5 ≈ B2 · 7.0–8.0 ≈ C1 · 8.5–9.0 ≈ C2. Most universities ask for 6.0–7.0; most immigration programmes ask for 6.0–7.0 with minimum scores in each skill.',
  strategy: [
    { t: '1 · Diagnose before you drill', az: 'Qabaqca diaqnoz', d: 'Take the Diagnostic Test here, then build a study plan targeting your two weakest skills. Improving a 5.5 skill to 6.5 raises your overall more than pushing a 7.0 to 7.5.' },
    { t: '2 · Learn the question types', az: 'Sual növlərini öyrən', d: 'Every IELTS question type has a strategy: True/False/Not Given needs strict logic; matching headings tests paragraph main ideas; form completion needs exact spelling and word limits.' },
    { t: '3 · Train under time pressure', az: 'Vaxt altında məşq', d: 'Reading gives you 20 minutes per passage — practise finishing in 17. Writing Task 1 deserves only 20 minutes. Timed practice on this site uses condensed, realistic timing.' },
    { t: '4 · Build topic vocabulary', az: 'Mövzu lüğəti', d: 'IELTS recycles about ten core topics: education, environment, technology, health, work, media and society. Learn words in topic families with collocations, not isolated lists.' },
    { t: '5 · Record and review', az: 'Yazıb təkrar et', d: 'Record your speaking, keep a mistake notebook, and re-test regularly. Every wrong answer on this site is saved to My Mistakes automatically.' }
  ]
};
const IELTS_RAW = {
  listening: [[39, 40, 9], [37, 38, 8.5], [35, 36, 8], [32, 34, 7.5], [30, 31, 7], [26, 29, 6.5], [23, 25, 6], [18, 22, 5.5], [16, 17, 5], [13, 15, 4.5], [10, 12, 4]],
  readingA: [[39, 40, 9], [37, 38, 8.5], [35, 36, 8], [33, 34, 7.5], [30, 32, 7], [27, 29, 6.5], [23, 26, 6], [19, 22, 5.5], [15, 18, 5], [13, 14, 4.5], [10, 12, 4]],
  readingG: [[40, 40, 9], [39, 39, 8.5], [37, 38, 8], [36, 36, 7.5], [34, 35, 7], [32, 33, 6.5], [30, 31, 6], [27, 29, 5.5], [23, 26, 5], [19, 22, 4.5], [15, 18, 4]]
};
/* ---- Grammar for IELTS · 12 topics × 4 difficulty bands ---- */
const IELTS_GRAM = [
  { id: 'sent', band: 'Foundation', t: 'Sentence structure', az: 'Cümlə quruluşu', ex: 'Every sentence needs a subject and a finite verb: “The graph shows a steady increase.” — not “Shows a steady increase.”', ielts: 'In Writing Task 1, begin descriptions with full clauses: “The chart illustrates…” “Overall, sales rose…”.', mistake: 'Sentence fragments: “Because many people prefer cities.” (fragment — add a main clause: “Cities are popular because they offer more jobs.”)', azd: 'Hər cümlədə mübtəda və tam feli必须有 — fraqmentlərdən qaçın.', quiz: [{ q: 'Choose the complete sentence:', opts: ['Although the test was difficult.', 'Although the test was difficult, she passed.', 'She passed although difficult.'], a: 1, exp: 'A complex sentence needs both a dependent clause and a main clause.' }, { q: 'Fix the fragment: “Because houses use most energy.”', opts: ['Because houses use most energy, heating is the biggest cost.', 'Houses use most energy because.', 'Use most energy houses.'], a: 0, exp: 'Attach the fragment to a main clause with a comma.' }] },
  { id: 'tense', band: 'Foundation', t: 'Tense control', az: 'Zamanlar', ex: 'Present simple for facts and trends that are always true; past simple for finished chart periods: “Between 2000 and 2010, sales doubled.”', ielts: 'Task 1 with past data = past simple. Processes = present simple passive. Predictions = “is expected to / is projected to”.', mistake: '“The number of students increase” → the number… increases (the number is singular).', azd: 'Qrafik məlumatı keçmişdirsə past simple, prosesdirsə present passive işlədin.', quiz: [{ q: 'The chart shows 1990–2010 data. Choose the correct sentence:', opts: ['Sales rise sharply in 2005.', 'Sales rose sharply in 2005.', 'Sales rising sharply in 2005.'], a: 1, exp: 'Finished past period → past simple.' }, { q: 'Describe this process step: “The beans ___ (roast) at 120°C.”', opts: ['roast', 'are roasted', 'were roasted'], a: 1, exp: 'Processes use present simple passive.' }] },
  { id: 'sva', band: 'Foundation', t: 'Subject–verb agreement', az: 'Mübtəda–fel uyğunluğu', ex: '“The proportion of adults who exercise regularly has fallen.” (head noun = proportion)', ielts: 'Task 1 trap: “the number of…” (singular) vs “a number of…” (plural).', mistake: '“The number of tourists have increased” → has increased.', azd: 'Fel mübtədanın əsas sözü ilə uyğunlaşır, yaxın söz yox.', quiz: [{ q: 'A number of students ___ absent today.', opts: ['is', 'are', 'was'], a: 1, exp: '“A number of” = many → plural.' }, { q: 'The percentage of households with two cars ___ risen.', opts: ['have', 'has', 'were'], a: 1, exp: 'Head noun “percentage” is singular.' }] },
  { id: 'art', band: 'Foundation', t: 'Articles in academic writing', az: 'Artikllər', ex: '“The government introduced a policy. The policy reduced emissions.” First mention a/an, second mention the.', ielts: 'Generalisations can drop the article: “Pollution affects health.” But specific data takes “the”: “the figure for 2010”.', mistake: '“The most of people” → most people (no “the” with most + plural).', azd: 'İlk dəfə a/an, ikinci dəfə the; ümumi mənada artikl yox.', quiz: [{ q: '___ unemployment fell in ___ 1990s.', opts: ['The / the', '— / the', '— / —'], a: 1, exp: 'Unemployment as an unc general concept takes no article; decades take “the”.' }, { q: 'Choose the correct sentence:', opts: ['Most of students agree.', 'Most students agree.', 'The most students agree.'], a: 1, exp: 'most + plural noun without article.' }] },
  { id: 'modals', band: 'Intermediate', t: 'Modals for speculation and advice', az: 'Modallar', ex: '“This may suggest that…” “Governments should invest…” “The delay could be explained by…”', ielts: 'Task 2 conclusions and Speaking Part 3 live on hedged modals: may, might, could, should — they make you sound academic, not absolute.', mistake: '“Governments must to invest” → no “to” after must.', azd: 'May/might/could iddia dodağı qoyur, should tövsiyədir.', quiz: [{ q: 'Hedge this claim: “Social media harms teenagers.”', opts: ['Social media must harms teenagers.', 'Social media may harm some teenagers.', 'Social media can to harm teenagers.'], a: 1, exp: 'may + base verb, softened by “some” — academic hedging.' }, { q: 'Governments ___ ban cars, but they ___ encourage public transport.', opts: ['should not / should', 'shouldn’t to / should to', 'not should / should'], a: 0, exp: 'Modals take the bare infinitive.' }] },
  { id: 'cond', band: 'Intermediate', t: 'Conditionals', az: 'Şərt cümlələri', ex: 'If temperatures rise further, coastal cities will flood. (real future) · If governments had acted earlier, the crisis would have been smaller. (unreal past)', ielts: 'Speaking Part 3 hypotheticals (“What if everyone worked from home?”) need second conditionals; Task 2 solutions often mix first + second.', mistake: '“If I would have more time, I would study” → If I had more time…', azd: '2-ci tip: If + past, would + feil. 3-cü tip: If + had done, would have done.', quiz: [{ q: 'If public transport ___ free, fewer people would drive.', opts: ['is', 'were', 'will be'], a: 1, exp: 'Second conditional: if + past (were), would + base.' }, { q: 'If the company had trained staff, the errors ___ avoided.', opts: ['would be', 'would have been', 'will have been'], a: 1, exp: 'Unreal past → would have + past participle.' }] },
  { id: 'passive', band: 'Intermediate', t: 'Passive voice for processes', az: 'Məchul növ', ex: '“The beans are harvested, then roasted, and finally ground.”', ielts: 'Academic Task 1 process diagrams are almost entirely passive. Passive also lets you avoid repeating vague agents: “The data were collected in 2021.”', mistake: '“The data was collect” → were collected (data = plural in formal writing; and add -ed).', azd: 'Proseslər: is/are + III forma. Məlumat sözü rəsmi yazıda cəm kimi qəbul oluna bilər.', quiz: [{ q: 'Stage 3 of the process: “The mixture ___ into moulds.”', opts: ['pours', 'is poured', 'is pouring'], a: 1, exp: 'Present simple passive for process stages.' }, { q: 'Formal report: “The survey ___ by 2,000 residents.”', opts: ['was completed', 'completed', 'was completing'], a: 0, exp: 'Passive past simple.' }] },
  { id: 'relative', band: 'Intermediate', t: 'Relative clauses', az: 'Əlaqəli birləşmələr', ex: '“Cities that invest in cycling see fewer accidents.” · “The graph, which covers a decade, shows…”.', ielts: 'Relative clauses pack more information per sentence — exactly what examiners reward under Grammatical Range.', mistake: '“The city which I live” → the city where I live / which I live in.', azd: 'which/that şeylər, who insanlar, where yerlər üçündür.', quiz: [{ q: 'Join: “The plant absorbs CO₂. It grows fast.”', opts: ['The plant which absorbs CO₂ grows fast.', 'The plant, that grows fast, absorbs CO₂.', 'The plant it absorbs CO₂ grows fast.'], a: 0, exp: 'Defining relative clause with which — no commas.' }, { q: 'This is the factory ___ my mother worked for 20 years.', opts: ['which', 'where', 'that'], a: 1, exp: '“Worked for” the factory → where (or: which … for).' }] },
  { id: 'gerund', band: 'Upper-Intermediate', t: 'Gerunds and infinitives', az: 'Gerundium və infinitiv', ex: '“Buying local produce reduces emissions.” · “Governments aim to cut emissions by 2030.”', ielts: 'Vary your patterns: gerund subjects sound formal (“Recycling alone cannot solve…”); “aim to / be likely to / succeed in” are high-band structures.', mistake: '“They suggested to reduce taxes” → suggested reducing (suggest + gerund).', azd: 'suggest/avoid/consider + -ing; aim/decide/hope + to do.', quiz: [{ q: 'The council considered ___ the bridge.', opts: ['to widen', 'widening', 'widen'], a: 1, exp: 'consider + gerund.' }, { q: 'Firms are unlikely ___ such costs voluntarily.', opts: ['absorbing', 'to absorb', 'absorb'], a: 1, exp: 'be likely + to-infinitive.' }] },
  { id: 'complex', band: 'Upper-Intermediate', t: 'Complex sentences & linkers', az: 'Mürəkkəb cümlələr', ex: '“While car ownership rose, cycling fell — a pattern that suggests infrastructure, not income, drives the trend.”', ielts: 'Coherence and Cohesion rises when linkers are precise: whereas/while (contrast), consequently (result), although (concession), given that (reason).', mistake: '“Although but sales fell” — never pair although with but.', azd: 'Bir cümlədə bir əlaqələndirici: although X, Y (but yox).', quiz: [{ q: '___ online learning is cheaper, many students prefer classrooms.', opts: ['Despite', 'Although', 'However'], a: 1, exp: 'Although + clause; despite + noun.' }, { q: 'Choose the precise linker: “Prices doubled; ___, demand barely moved.”', opts: ['consequently', 'nevertheless', 'because'], a: 1, exp: 'Contrast → nevertheless.' }] },
  { id: 'nounphr', band: 'Advanced', t: 'Nominalisation & academic style', az: 'İsimləşdirmə', ex: '“The government reduced subsidies, which caused prices to rise.” → “The reduction of subsidies led to price increases.”', ielts: 'Band 8 writing converts verbs to noun phrases — it condenses information and raises formality. Balance it: overuse sounds cold.', mistake: 'Over-nominalisation: “The implementation of the utilisation of…” — simplify stacked nouns.', azd: 'Fel→isim çevirmə yazını rəsmiləşdirir: reduce → the reduction of.', quiz: [{ q: 'Nominalise: “Cities expanded rapidly.”', opts: ['The rapid expansion of cities…', 'The rapidly expand of cities…', 'Cities’ rapid expanding…'], a: 0, exp: 'Adjective becomes adverb→noun pattern: rapid + expansion + of.' }, { q: 'Which sentence is appropriately nominalised (not overloaded)?', opts: ['The facilitation of the optimisation of transport was undertaken.', 'The electrification of transport accelerated after 2015.', 'They did the electrifying of transport.'], a: 1, exp: 'One clean nominalisation with a clear agent and verb.' }] },
  { id: 'hedg', band: 'Advanced', t: 'Hedging & cautious language', az: 'Ehtiyatlı dil', ex: '“The data suggest that remote work may reduce commuting, though the effect appears limited to larger cities.”', ielts: 'Examiners reward writers who do not overclaim: tends to, appears to, is likely to, suggests. Overuse of “always/never/everyone” caps your band at 6.', mistake: '“All people know that…” → unfounded absolute; try “It is widely accepted that…”.', azd: '“Həmişə/heç vaxt/hamı” kimi mütləq sözlərdən qaçın — may/appears/tends to işlədin.', quiz: [{ q: 'Soften: “Video calls will replace business travel.”', opts: ['Video calls are likely to reduce business travel.', 'Video calls must replace business travel.', 'Video calls replacing business travel.'], a: 0, exp: 'are likely to + verb = calibrated claim.' }, { q: 'Which sentence overclaims?', opts: ['Some commuters may welcome shorter weeks.', 'Nobody will ever want to commute again.', 'Four-day weeks appear to raise satisfaction.'], a: 1, exp: '“Nobody… ever” is an unfalsifiable absolute.' }] }
];
/* ---- IELTS Vocabulary · topic families, word → az, collocations, pitfalls ---- */
const IELTS_VOCAB = [
  { topic: 'Education', words: [
    { w: 'curriculum', pos: 'n', def: 'the subjects included in a course of study', az: 'tədris proqramı', ex: 'A balanced curriculum includes arts as well as sciences.', col: 'national curriculum, curriculum design, core curriculum', syn: 'syllabus, programme of study', mistake: 'Not “studying plan” — the set word is curriculum.' },
    { w: 'tuition fees', pos: 'n', def: 'money paid for university teaching', az: 'təhsil haqqı', ex: 'Rising tuition fees discourage students from low-income families.', col: ' tuition fees soar/waive, fee waivers', syn: 'course fees', mistake: 'Singular “fee” only for one payment; general talk uses plural fees.' },
    { w: 'vocational', pos: 'adj', def: 'teaching skills for a particular job', az: 'peşə (təhsili)', ex: 'Vocational courses link classrooms directly to employers.', col: 'vocational training, vocational qualifications', syn: 'job-related, technical', mistake: 'Not “professional” — vocational refers to practical job skills.' },
    { w: 'distance learning', pos: 'n', def: 'study away from a campus, usually online', az: 'uzaqdan təhsil', ex: 'Distance learning widened access for rural students.', col: 'distance-learning platform, pursue distance learning', syn: 'remote study, e-learning', mistake: 'Usually uncountable: not “a distance learning”.' },
    { w: 'literacy', pos: 'n', def: 'the ability to read and write', az: 'savadlılıq', ex: 'Adult literacy programmes transform local economies.', col: 'literacy rates, digital literacy, literacy campaign', syn: 'reading skills', mistake: 'Literacy = reading/writing; numeracy = maths ability.' },
    { w: 'scholarship', pos: 'n', def: 'money awarded to support a student’s study', az: 'təqaüd', ex: 'She won a fully funded scholarship abroad.', col: 'win/award a scholarship, merit scholarship', syn: 'grant, bursary', mistake: 'A scholarship is merit-based; a grant may be need-based.' },
    { w: 'rote learning', pos: 'n', def: 'memorising without understanding', az: 'əzbərləmə', ex: 'Critics blame rote learning for weak problem-solving skills.', col: 'rely on rote learning', syn: 'memorisation', mistake: 'Negative connotation in essays — use carefully.' },
    { w: 'well-rounded', pos: 'adj', def: 'having a wide range of abilities', az: 'çoxtərəfli inkişaf etmiş', ex: 'Employers value well-rounded graduates with soft skills.', col: 'a well-rounded education', syn: 'versatile, all-round', mistake: 'Hyphenated before a noun: well-rounded students.' }] },
  { topic: 'Environment', words: [
    { w: 'emissions', pos: 'n', def: 'gases released into the air', az: 'tullantı qazları (emissiya)', ex: 'Cities must halve emissions by 2040 to meet targets.', col: 'carbon emissions, cut/curb emissions, emissions target', syn: 'discharges, output', mistake: 'Usually plural in climate contexts: cut emissions, not “an emission”.' },
    { w: 'sustainable', pos: 'adj', def: 'able to continue without harming the planet', az: 'davamlı', ex: 'Sustainable farming protects soil and profits alike.', col: 'sustainable development, environmentally sustainable', syn: 'eco-friendly, viable', mistake: 'Sustainable ≠ renewable: renewables are energy sources.' },
    { w: 'deforestation', pos: 'n', def: 'cutting down forests over a wide area', az: 'meşələrin qırılması', ex: 'Deforestation accelerates both floods and species loss.', col: 'combat deforestation, deforestation rates', syn: 'forest clearance', mistake: 'Countable in academic writing: “a deforestation rate”.' },
    { w: 'renewable', pos: 'adj', def: '(of energy) from sources that never run out', az: 'bərpa olunan', ex: 'Renewables supplied a third of national electricity last year.', col: 'renewable energy/sources, renewables sector', syn: 'green, clean (energy)', mistake: '“Renewables” as a noun = renewable energy sources.' },
    { w: 'carbon footprint', pos: 'n', def: 'the CO₂ an activity or person produces', az: 'karbon izi', ex: 'Cutting food waste shrinks your carbon footprint fast.', col: 'reduce/shrink a carbon footprint', syn: 'CO₂ footprint', mistake: 'Use with reduce/offset, not “make”. ' },
    { w: 'biodiversity', pos: 'n', def: 'the variety of living species in an area', az: 'biomüxtəliflik', ex: 'Wetland restoration boosts biodiversity dramatically.', col: 'biodiversity loss, rich biodiversity', syn: 'ecological variety', mistake: 'Uncountable: not “a biodiversity”.' },
    { w: 'landfill', pos: 'n', def: 'a site where rubbish is buried', az: 'zibilxana (torpaqda)', ex: 'Half of household waste still ends up in landfill.', col: 'landfill site, divert waste from landfill', syn: 'dump, tip', mistake: 'Not “landfills ground” — landfill sites.' },
    { w: 'drought', pos: 'n', def: 'a long period with little rain', az: 'quraqlıq', ex: 'Prolonged droughts push food prices upward.', col: 'severe/prolonged drought, drought-resistant crops', syn: 'dry spell', mistake: 'Silent letters: droughT — spell carefully in Listening.' }] },
  { topic: 'Technology', words: [
    { w: 'artificial intelligence', pos: 'n', def: 'computer systems that perform human-like tasks', az: 'süni intellekt', ex: 'Artificial intelligence already screens job applications.', col: 'AI-powered, adopt AI, AI ethics', syn: 'machine intelligence', mistake: 'In essays define it once, then use AI.' },
    { w: 'automation', pos: 'n', def: 'use of machines to do work without people', az: 'avtomatlaşdırma', ex: 'Automation will reshape manufacturing jobs within a decade.', col: 'job automation, automation threatens', syn: 'robotisation', mistake: 'Uncountable: not “an automation”.' },
    { w: 'cybersecurity', pos: 'n', def: 'protection of computers and data from attacks', az: 'kiber təhlükəsizlik', ex: 'Cybersecurity spending rose 40% after the breach.', col: 'cybersecurity threat/breach', syn: 'IT security', mistake: 'One word, no hyphen, in modern usage.' },
    { w: 'obsolete', pos: 'adj', def: 'no longer used because something newer exists', az: 'köhnəlmiş, artıq istifadə olunmayan', ex: 'Video rental stores became obsolete almost overnight.', col: 'render something obsolete, obsolete technology', syn: 'outdated, outmoded', mistake: '“Absolute” is a different word — don’t confuse them.' },
    { w: 'breakthrough', pos: 'n', def: 'an important discovery or success', az: 'elmi kəşf, irəliləyiş', ex: 'The vaccine breakthrough relied on decades of research.', col: 'a major/scientific breakthrough, breakthrough in', syn: 'advance, leap', mistake: 'Countable: a breakthrough, breakthroughs.' },
    { w: 'surveillance', pos: 'n', def: 'close watching, especially by cameras or police', az: 'nəzarət (izləmə)', ex: 'Widespread surveillance raises privacy concerns.', col: 'mass surveillance, surveillance cameras', syn: 'monitoring', mistake: 'Uncountable; stress on the second syllable: surVEIllance.' },
    { w: 'digital divide', pos: 'n', def: 'the gap between those with and without technology access', az: 'rəqəmsal bərabərsizlik', ex: 'The digital divide left rural pupils offline during lockdowns.', col: 'bridge/narrow the digital divide', syn: 'access gap', mistake: 'Keep the fixed phrase — not “digital inequality” in formal charts.' },
    { w: 'user-friendly', pos: 'adj', def: 'easy to use', az: 'istifadəçi üçün rahat', ex: 'Governments demand user-friendly public apps.', col: 'a user-friendly interface', syn: 'intuitive, accessible', mistake: 'Hyphenated before a noun.' }] },
  { topic: 'Health', words: [
    { w: 'obesity', pos: 'n', def: 'being extremely overweight', az: 'piylənmə', ex: 'Childhood obesity has tripled since 1990.', col: 'obesity epidemic, obesity rates soar', syn: 'morbid overweight', mistake: 'Uncountable; adjective is obese.' },
    { w: 'sedentary', pos: 'adj', def: 'sitting a lot with little exercise', az: 'oturaq həyat tərzi', ex: 'Sedentary lifestyles strain both heart and spine.', col: 'a sedentary lifestyle/job', syn: 'inactive, desk-bound', mistake: 'Stress: SEDentary; often with “lifestyle”.' },
    { w: 'vaccination', pos: 'n', def: 'giving a vaccine to prevent disease', az: 'vaksinasiya', ex: 'Mass vaccination ended smallpox for good.', col: 'vaccination campaign, vaccination coverage', syn: 'immunisation', mistake: 'Vaccination (the act) vs vaccine (the substance).' },
    { w: 'mental wellbeing', pos: 'n', def: 'a healthy state of mind', az: 'psixoloji rifah', ex: 'Employers now invest in staff mental wellbeing.', col: 'promote/support mental wellbeing', syn: 'psychological health', mistake: 'Wellbeing is one word in most modern style guides.' },
    { w: 'life expectancy', pos: 'n', def: 'how long people are expected to live', az: 'orta ömür uzunluğu', ex: 'Life expectancy rose five years in two decades.', col: 'life expectancy at birth, rising life expectancy', syn: 'longevity', mistake: 'Always with “life”, not “living expectancy”.' },
    { w: 'screen time', pos: 'n', def: 'time spent looking at phones, TVs or computers', az: 'ekran qarşısında vaxt', ex: 'Excessive screen time disrupts children’s sleep.', col: 'limit/reduce screen time', syn: 'device hours', mistake: 'Usually uncountable.' },
    { w: 'epidemic', pos: 'n', def: 'rapid spread of disease in one area', az: 'epidemiya', ex: 'The flu epidemic overwhelmed clinics.', col: 'an obesity/flu epidemic, reach epidemic proportions', syn: 'outbreak', mistake: 'Epidemic = one region; pandemic = worldwide.' },
    { w: 'preventive', pos: 'adj', def: 'intended to stop illness before it starts', az: 'qarşısının alınması (profilaktik)', ex: 'Preventive care is cheaper than hospital treatment.', col: 'preventive medicine, preventive measures', syn: 'prophylactic', mistake: 'Both preventive and preventative exist; prefer preventive.' }] },
  { topic: 'Work', words: [
    { w: 'remote work', pos: 'n', def: 'working away from a central office', az: 'uzaqdan iş', ex: 'Remote work cut commuting costs for millions.', col: 'embrace remote work, remote-work policy', syn: 'telecommuting, working from home', mistake: 'Hyphenate as adjective: remote-work culture.' },
    { w: 'productivity', pos: 'n', def: 'the rate of output per worker or hour', az: 'məhsuldarlıq', ex: 'Quiet offices boost productivity measurably.', col: 'productivity gains, boost productivity', syn: 'efficiency', mistake: 'Uncountable; adjective is productive.' },
    { w: 'recruitment', pos: 'n', def: 'the process of finding new employees', az: 'işə qəbul', ex: 'Online recruitment changed how firms hire.', col: 'recruitment agency, recruitment drive', syn: 'hiring', mistake: '“Recruitment” is the process; “recruit” is the person.' },
    { w: 'redundancy', pos: 'n', def: 'losing a job because the role no longer exists', az: 'işdən çıxarılma (stat üzrə)', ex: 'Automation led to 200 redundancies at the plant.', col: 'make redundancies, redundancy package', syn: 'layoffs (US)', mistake: 'Plural redundancies when counting people.' },
    { w: 'flexible hours', pos: 'n', def: 'a system letting staff choose start/end times', az: 'çevik iş saatları', ex: 'Flexible hours helped parents stay in work.', col: 'offer/introduce flexible hours', syn: 'flextime', mistake: 'Often plural: flexible hours, a flexible-hours policy.' },
    { w: 'promotion', pos: 'n', def: 'a move to a higher job position', az: 'vəzifə yüksəlişi', ex: 'She earned promotion within two years.', col: 'gain/earn promotion, promotion prospects', syn: 'advancement', mistake: 'In work context ≠ marketing promotion.' },
    { w: 'work-life balance', pos: 'n', def: 'a healthy split between job and personal life', az: 'iş–həyat balansı', ex: 'Poor work-life balance drives staff turnover.', col: 'improve/restore work-life balance', syn: 'lifestyle balance', mistake: 'Hyphens required in the compound.' },
    { w: 'incentive', pos: 'n', def: 'something that encourages action', az: 'həvəsləndirici, stimul', ex: 'Tax incentives attract green investment.', col: 'financial incentive, incentive scheme', syn: 'motivator, inducement', mistake: 'Stress the second syllable: inCENtive.' }] },
  { topic: 'Economy', words: [
    { w: 'inflation', pos: 'n', def: 'a general rise in prices', az: 'inflyasiya', ex: 'High inflation erodes household savings.', col: 'soaring inflation, curb inflation, inflation rate', syn: 'price rises', mistake: 'Uncountable;搭配 “inflation rate” for data.' },
    { w: 'recession', pos: 'n', def: 'a period of economic decline', az: 'iqtisadi tənəzzül', ex: 'The recession pushed youth unemployment to record highs.', col: 'slip into recession, recession-hit sectors', syn: 'downturn, slump', mistake: '“Recession” = two consecutive quarters of negative growth.' },
    { w: 'GDP', pos: 'n', def: 'Gross Domestic Product — total value of goods and services', az: 'ÜDM', ex: 'GDP per capita doubled in a generation.', col: 'GDP growth, GDP per capita', syn: 'economic output', mistake: 'Write out at first mention in formal essays.' },
    { w: 'subsidy', pos: 'n', def: 'government money supporting an industry or price', az: 'subsidia (dövlət yardımı)', ex: 'Fossil-fuel subsidies outweigh green-energy support.', col: 'subsidise farming, fuel subsidies', syn: 'state aid', mistake: 'Verb is subsidise (UK) / subsidize (US).' },
    { w: 'consumer spending', pos: 'n', def: 'money people spend on goods and services', az: 'istehlak xərcləri', ex: 'Consumer spending drives two-thirds of the economy.', col: 'consumer spending picks up/falls', syn: 'household consumption', mistake: 'Keep the collocation “consumer”, not “customers’ spending”.' },
    { w: 'inequality', pos: 'n', def: 'unfair difference in income or opportunity', az: 'bərabərsizlik', ex: 'Wage inequality widened after deregulation.', col: 'income inequality, narrow/tackle inequality', syn: 'disparity, gap', mistake: 'Often followed by “in”: inequality in pay.' },
    { w: 'tariff', pos: 'n', def: 'a tax on imported goods', az: 'gömrük rüsumu', ex: 'Steel tariffs raised costs for carmakers.', col: 'impose/lift tariffs, tariff barriers', syn: 'customs duty', mistake: 'Plural tariffs when discussing policy generally.' },
    { w: 'infrastructure', pos: 'n', def: 'basic systems a country needs (roads, power, internet)', az: 'infrastruktur', ex: 'Ageing infrastructure slows freight and growth.', col: 'invest in infrastructure, crumbling infrastructure', syn: 'public works', mistake: 'Uncountable: not “infrastructures”.' }] },
  { topic: 'Culture & Society', words: [
    { w: 'globalisation', pos: 'n', def: 'the growing connection of world economies and cultures', az: 'qloballaşma', ex: 'Globalisation spreads both products and ideas instantly.', col: 'globalisation of markets, anti-globalisation', syn: 'international integration', mistake: 'UK spelling globalisation / US globalization.' },
    { w: 'heritage', pos: 'n', def: 'traditions and historic things passed down', az: 'mədəni irs', ex: 'UNESCO lists the old city as world heritage.', col: 'cultural heritage, heritage site', syn: 'legacy, tradition', mistake: 'Uncountable in heritage-site contexts.' },
    { w: 'multicultural', pos: 'adj', def: 'including many cultures', az: 'çoxmədəniyyətli', ex: 'Multicultural cities attract international talent.', col: 'a multicultural society, multiculturalism policy', syn: 'cosmopolitan', mistake: 'Multicultural (adj) vs multiculturalism (n).' },
    { w: 'urbanisation', pos: 'n', def: 'the movement of people into cities', az: 'şəhərləşmə', ex: 'Rapid urbanisation strains housing and transport.', col: 'rapid urbanisation, urbanisation rate', syn: 'city growth', mistake: 'Verb: urbanise; adjective: urban.' },
    { w: 'social cohesion', pos: 'n', def: 'the strength of relationships within a community', az: 'ictimai həmrəylik', ex: 'Mixed housing designs strengthen social cohesion.', col: 'promote social cohesion', syn: 'community solidarity', mistake: 'Cohesion (sticking together) ≠ coherence (logical flow).' },
    { w: 'stereotype', pos: 'n', def: 'a fixed, unfair idea about a group', az: 'stereotip', ex: 'Media stereotypes distort how migrants are seen.', col: 'challenge/break stereotypes, gender stereotypes', syn: 'cliché, generalisation', mistake: 'Countable: a stereotype, stereotypes.' },
    { w: 'integration', pos: 'n', def: 'becoming part of a wider community', az: 'inteqrasiya', ex: 'Language classes speed up migrant integration.', col: 'social integration, integrate newcomers', syn: 'inclusion', mistake: 'Integration implies joining, not erasing identity.' },
    { w: 'discrimination', pos: 'n', def: 'unfair treatment of a group', az: 'ayrı-seçkilik', ex: 'Laws ban discrimination at work.', col: 'face/fight discrimination, racial discrimination', syn: 'bias, prejudice (n)', mistake: 'Uncountable in legal contexts.' }] },
  { topic: 'Media', words: [
    { w: 'misinformation', pos: 'n', def: 'false information spread without intent to harm', az: 'yanlış informasiya', ex: 'Misinformation spreads faster than corrections.', col: 'combat misinformation, misinformation campaign', syn: 'false news', mistake: 'Misinformation (unintentional) vs disinformation (deliberate).' },
    { w: 'censorship', pos: 'n', def: 'controlling or banning information', az: 'senzura', ex: 'Internet censorship limits academic debate.', col: 'impose censorship, media censorship', syn: 'information control', mistake: 'Uncountable; a censored item is “censored content”.' },
    { w: 'mainstream media', pos: 'n', def: 'large, traditional news organisations', az: 'əsas media orqanları', ex: 'Mainstream media fact-checks viral claims.', col: 'mainstream outlets, go mainstream', syn: 'legacy media', mistake: 'No “the” when contrasting with social media: mainstream media reports…' },
    { w: 'influencer', pos: 'n', def: 'a person who shapes opinions on social media', az: 'influenser (təsirli şəxsiyyət)', ex: 'Influencers now rival TV in advertising reach.', col: 'influencer marketing, top influencers', syn: 'content creator', mistake: 'One who influences; not “influenceur”.' },
    { w: 'tabloid', pos: 'n', def: 'a small-format paper focused on celebrity news', az: 'tabloid (sarı mətbuat)', ex: 'Tabloids prioritise scandal over policy.', col: 'tabloid press, tabloid headlines', syn: 'gutter press', mistake: 'Adjective: tabloid journalism.' },
    { w: 'propaganda', pos: 'n', def: 'biased information promoting a political cause', az: 'propaqanda', ex: 'Wartime propaganda shaped public opinion.', col: 'state propaganda, propaganda machine', syn: 'indoctrination', mistake: 'Strongly negative — use with evidence in essays.' },
    { w: 'coverage', pos: 'n', def: 'the reporting of news events', az: 'işıqlandırma (media)', ex: 'Live coverage kept voters informed.', col: 'extensive news coverage, media coverage of', syn: 'reporting', mistake: 'Uncountable: not “a coverage”.' },
    { w: 'clickbait', pos: 'n', def: 'headlines designed to attract clicks, not inform', az: 'klikləmə üçün oyun başlıqları', ex: 'Clickbait erodes trust in journalism.', col: 'clickbait headlines', syn: 'sensational headlines', mistake: 'Uncountable: “a piece of clickbait”.' }] }
];
/* ---- Collocations · 5 categories ---- */
const IELTS_COLL = [
  { cat: 'Academic collocations', items: [
    { p: 'conduct research', m: 'to carry out scientific study', az: 'tədqiqat aparmaq', ex: 'Universities conduct research on renewable storage.', gap: 'The lab will ___ research into battery life.', a: 'conduct' },
    { p: 'draw a conclusion', m: 'to decide something after reasoning', az: 'nəticə çıxarmaq', ex: 'From the data, we can draw a clear conclusion.', gap: 'It is too early to ___ a conclusion.', a: 'draw' },
    { p: 'play a role', m: 'to have an influence', az: 'rol oynamaq', ex: 'Diet plays a role in heart health.', gap: 'Genetics also ___ a role in lifespan.', a: 'play' },
    { p: 'a significant impact', m: 'a large effect', az: 'əhəmiyyətli təsir', ex: 'The reform had a significant impact on scores.', gap: 'Tourism has a ___ impact on coastal jobs.', a: 'significant' }] },
  { cat: 'Environment collocations', items: [
    { p: 'reduce emissions', m: 'to cut released gases', az: 'tullantıları azaltmaq', ex: 'Buses reduce emissions in dense districts.', gap: 'New rules ___ emissions from factories.', a: 'reduce' },
    { p: 'fossil fuels', m: 'coal, oil and gas', az: 'fossil yanacaqlar', ex: 'We must transition away from fossil fuels.', gap: 'Burning ___ fuels warms the planet.', a: 'fossil' },
    { p: 'carbon footprint', m: 'total CO₂ produced', az: 'karbon izi', ex: 'Cycling shrinks your carbon footprint.', gap: 'Firms now measure their carbon ___.', a: 'footprint' },
    { p: 'renewable energy', m: 'power from sun, wind, water', az: 'bərpa olunan enerji', ex: 'Islands lead on renewable energy.', gap: 'Wind is the cheapest ___ energy source here.', a: 'renewable' }] },
  { cat: 'Education collocations', items: [
    { p: 'sit an exam', m: 'to take an exam', az: 'imtahan vermək', ex: 'Students sit an exam each semester.', gap: 'Candidates ___ the exam in June.', a: 'sit' },
    { p: 'a broad curriculum', m: 'a wide range of subjects', az: 'geniş tədris proqramı', ex: 'A broad curriculum builds flexible minds.', gap: 'The school offers a ___ curriculum of arts and sciences.', a: 'broad' },
    { p: 'hands-on experience', m: 'practical, direct practice', az: 'praktiki təcrübə', ex: 'Labs give students hands-on experience.', gap: 'Internships provide ___-on experience.', a: 'hands' },
    { p: 'meet a deadline', m: 'to finish on time', az: 'müddətə yetirmək', ex: 'Researchers met the deadline despite delays.', gap: 'Extension requests are rare if you ___ the deadline.', a: 'meet' }] },
  { cat: 'Technology collocations', items: [
    { p: 'cutting-edge technology', m: 'the newest advanced tech', az: 'son söz texnologiya', ex: 'Hospitals adopt cutting-edge scanners.', gap: 'The startup uses ___-edge robotics.', a: 'cutting' },
    { p: 'data privacy', m: 'protection of personal information', az: 'məlumat məxfiliyi', ex: 'Laws strengthen data privacy.', gap: 'Users worry about data ___.', a: 'privacy' },
    { p: 'widespread access', m: 'available to most people', az: 'geniş çıxış imkanı', ex: 'Broadband gives widespread access to courses.', gap: 'Wi-Fi provides ___ access across campus.', a: 'widespread' },
    { p: 'pose a threat', m: 'to be a danger', az: 'təhlükə yaratmaq', ex: 'Hackers pose a threat to hospitals.', gap: 'Deepfakes ___ a threat to elections.', a: 'pose' }] },
  { cat: 'Economic collocations', items: [
    { p: 'economic growth', m: 'increase in output and wealth', az: 'iqtisadi artım', ex: 'Trade fuelled economic growth.', gap: 'Exports drive ___ growth.', a: 'economic' },
    { p: 'raise living standards', m: 'to improve how people live', az: 'həyat səviyyəsini qaldırmaq', ex: 'Exports raised living standards inland.', gap: 'Tourism helped ___ living standards.', a: 'raise' },
    { p: 'a competitive market', m: 'one with many rivals', az: 'rəqabətli bazar', ex: 'Cheap flights created a competitive market.', gap: 'Deregulation built a ___ market in telecoms.', a: 'competitive' },
    { p: 'job creation', m: 'making new employment', az: 'yeni iş yerlərinin yaradılması', ex: 'Small firms lead job creation.', gap: 'Tax cuts aim to boost job ___.', a: 'creation' }] }
];
