/* Extra vocabulary — levels B1, B2 */
window.LF_VOCAB_EXTRA = window.LF_VOCAB_EXTRA || {};
window.LF_VOCAB_EXTRA["B1"] = [
  { word: "salary", meaning: "the money you receive regularly for the work you do", example: "She gets a good salary from her new job.", pic: "💷", pos: "n", ipa: "/ˈsæləri/", cat: "Work" },
  { word: "colleague", meaning: "a person you work with", example: "My colleague helped me finish the report.", pic: "🧑‍💼", pos: "n", ipa: "/ˈkɒliːɡ/", cat: "Work" },
  { word: "deadline", meaning: "the time by which something must be finished", example: "The deadline for the project is Friday.", pic: "⏰", pos: "n", ipa: "/ˈdedlaɪn/", cat: "Work" },
  { word: "interview", meaning: "a formal meeting where you are asked questions for a job", example: "He has a job interview tomorrow morning.", pic: "🗣️", pos: "n", ipa: "/ˈɪntəvjuː/", cat: "Work" },
  { word: "promotion", meaning: "a move to a higher position at work", example: "She got a promotion after two years.", pic: "📈", pos: "n", ipa: "/prəˈməʊʃn/", cat: "Work" },
  { word: "employer", meaning: "a person or company that gives people work", example: "My employer offers free training courses.", pic: "🏢", pos: "n", ipa: "/ɪmˈplɔɪə/", cat: "Work" },
  { word: "employee", meaning: "a person who works for a company", example: "The company has over 500 employees.", pic: "🧑‍💻", pos: "n", ipa: "/ɪmˈplɔɪiː/", cat: "Work" },
  { word: "task", meaning: "a piece of work that you have to do", example: "Cleaning the office is an easy task.", pic: "📋", pos: "n", ipa: "/tɑːsk/", cat: "Work" },
  { word: "skill", meaning: "an ability to do something well", example: "Cooking is a useful skill to have.", pic: "🛠️", pos: "n", ipa: "/skɪl/", cat: "Work" },
  { word: "career", meaning: "the jobs you do during your working life", example: "She wants a career in medicine.", pic: "🎯", pos: "n", ipa: "/kəˈrɪə/", cat: "Work" },
  { word: "hire", meaning: "to give someone a job", example: "The shop decided to hire two new staff.", pic: "🤝", pos: "v", ipa: "/ˈhaɪə/", cat: "Work" },
  { word: "resign", meaning: "to officially leave your job", example: "He resigned from his position last week.", pic: "🚪", pos: "v", ipa: "/rɪˈzaɪn/", cat: "Work" },
  { word: "attend", meaning: "to go to an event or place", example: "I attend a meeting every Monday.", pic: "📅", pos: "v", ipa: "/əˈtend/", cat: "Work" },
  { word: "earn", meaning: "to get money for the work you do", example: "She earns a good salary each month.", pic: "💰", pos: "v", ipa: "/ɜːn/", cat: "Work" },
  { word: "retire", meaning: "to stop working because of your age", example: "My father will retire at sixty-five.", pic: "🌅", pos: "v", ipa: "/rɪˈtaɪə/", cat: "Work" },
  { word: "neighbour", meaning: "a person who lives near you", example: "Our neighbour waters our plants when we travel.", pic: "🏘️", pos: "n", ipa: "/ˈneɪbə/", cat: "People" },
  { word: "stranger", meaning: "a person you do not know", example: "A stranger asked me for directions.", pic: "🙋", pos: "n", ipa: "/ˈstreɪndʒə/", cat: "People" },
  { word: "guest", meaning: "a person invited to a home or event", example: "We have a guest staying for the weekend.", pic: "🚪", pos: "n", ipa: "/ɡest/", cat: "People" },
  { word: "host", meaning: "a person who welcomes and looks after guests", example: "The host offered everyone a drink.", pic: "🍹", pos: "n", ipa: "/həʊst/", cat: "People" },
  { word: "teenager", meaning: "a person between thirteen and nineteen years old", example: "The teenager spends hours on his phone.", pic: "🧑", pos: "n", ipa: "/ˈtiːneɪdʒə/", cat: "People" },
  { word: "adult", meaning: "a fully grown person", example: "Adults must buy a full ticket.", pic: "🧑", pos: "n", ipa: "/ˈædʌlt/", cat: "People" },
  { word: "customer", meaning: "a person who buys something from a shop", example: "The customer asked for a refund.", pic: "🛒", pos: "n", ipa: "/ˈkʌstəmə/", cat: "People" },
  { word: "audience", meaning: "the people who watch or listen to a show", example: "The audience clapped loudly at the end.", pic: "👏", pos: "n", ipa: "/ˈɔːdiəns/", cat: "People" },
  { word: "relative", meaning: "a member of your family", example: "We visit our relatives every summer.", pic: "👨‍👩‍👧", pos: "n", ipa: "/ˈrelətɪv/", cat: "Family" },
  { word: "cousin", meaning: "the child of your aunt or uncle", example: "My cousin lives in another city.", pic: "🧒", pos: "n", ipa: "/ˈkʌzn/", cat: "Family" },
  { word: "nephew", meaning: "the son of your brother or sister", example: "My nephew is learning to walk.", pic: "👶", pos: "n", ipa: "/ˈnefjuː/", cat: "Family" },
  { word: "niece", meaning: "the daughter of your brother or sister", example: "My niece loves drawing pictures.", pic: "👧", pos: "n", ipa: "/niːs/", cat: "Family" },
  { word: "grandparent", meaning: "the parent of your mother or father", example: "My grandparents live in the countryside.", pic: "👴", pos: "n", ipa: "/ˈɡrænpeərənt/", cat: "Family" },
  { word: "ancestor", meaning: "a family member who lived long ago", example: "Our ancestors came from Ireland.", pic: "🕰️", pos: "n", ipa: "/ˈænsestə/", cat: "Family" },
  { word: "marriage", meaning: "the legal union of two people as partners", example: "Their marriage lasted thirty years.", pic: "💍", pos: "n", ipa: "/ˈmærɪdʒ/", cat: "Family" },
  { word: "divorce", meaning: "the legal ending of a marriage", example: "They decided on a divorce after many years.", pic: "📄", pos: "n", ipa: "/dɪˈvɔːs/", cat: "Family" },
  { word: "household", meaning: "all the people living in one house", example: "The whole household eats dinner together.", pic: "🏠", pos: "n", ipa: "/ˈhaʊshəʊld/", cat: "Home" },
  { word: "furniture", meaning: "items like chairs, tables and beds", example: "They bought new furniture for the living room.", pic: "🛋️", pos: "n", ipa: "/ˈfɜːnɪtʃə/", cat: "Home" },
  { word: "cupboard", meaning: "a piece of furniture with shelves for storing things", example: "The cups are in the kitchen cupboard.", pic: "🚪", pos: "n", ipa: "/ˈkʌbəd/", cat: "Home" },
  { word: "balcony", meaning: "a small platform outside a room with a railing", example: "We drink coffee on the balcony.", pic: "🌇", pos: "n", ipa: "/ˈbælkəni/", cat: "Home" },
  { word: "garage", meaning: "a building where you keep a car", example: "The car is parked in the garage.", pic: "🚗", pos: "n", ipa: "/ˈɡærɑːʒ/", cat: "Home" },
  { word: "rent", meaning: "to pay money to live in or use a place", example: "They rent a flat near the station.", pic: "🔑", pos: "v", ipa: "/rent/", cat: "Home" },
  { word: "decorate", meaning: "to make a room look nice with paint or objects", example: "We decorated the bedroom with posters.", pic: "🎨", pos: "v", ipa: "/ˈdekəreɪt/", cat: "Home" },
  { word: "move", meaning: "to go to live in a different place", example: "They moved to a bigger house.", pic: "📦", pos: "v", ipa: "/muːv/", cat: "Home" },
  { word: "repair", meaning: "to fix something that is broken", example: "He repaired the broken chair.", pic: "🔧", pos: "v", ipa: "/rɪˈpeə/", cat: "Home" },
  { word: "routine", meaning: "the things you do regularly in the same order", example: "My morning routine starts with a shower.", pic: "🔁", pos: "n", ipa: "/ruːˈtiːn/", cat: "Routine" },
  { word: "schedule", meaning: "a plan of times for doing things", example: "My schedule is full this week.", pic: "📅", pos: "n", ipa: "/ˈʃedjuːl/", cat: "Routine" },
  { word: "habit", meaning: "something you do often without thinking", example: "Brushing your teeth is a good habit.", pic: "🦷", pos: "n", ipa: "/ˈhæbɪt/", cat: "Routine" },
  { word: "wake", meaning: "to stop sleeping", example: "I wake up at seven every day.", pic: "⏰", pos: "v", ipa: "/weɪk/", cat: "Routine" },
  { word: "prepare", meaning: "to get something ready", example: "She prepared lunch for the children.", pic: "🍳", pos: "v", ipa: "/prɪˈpeə/", cat: "Routine" },
  { word: "arrange", meaning: "to plan or organize something", example: "We arranged a meeting for Monday.", pic: "🗂️", pos: "v", ipa: "/əˈreɪndʒ/", cat: "Routine" },
  { word: "complete", meaning: "to finish something", example: "I completed the exercise quickly.", pic: "✅", pos: "v", ipa: "/kəmˈpliːt/", cat: "Routine" },
  { word: "delay", meaning: "to make something happen later than planned", example: "The train was delayed by an hour.", pic: "⏳", pos: "v", ipa: "/dɪˈleɪ/", cat: "Routine" },
  { word: "ingredient", meaning: "one of the foods used to make a dish", example: "Flour is a key ingredient in bread.", pic: "🥣", pos: "n", ipa: "/ɪnˈɡriːdiənt/", cat: "Food" },
  { word: "recipe", meaning: "instructions for cooking a dish", example: "This recipe needs three eggs.", pic: "📖", pos: "n", ipa: "/ˈresəpi/", cat: "Food" },
  { word: "flavour", meaning: "the taste of food or drink", example: "This soup has a rich flavour.", pic: "😋", pos: "n", ipa: "/ˈfleɪvə/", cat: "Food" },
  { word: "snack", meaning: "a small amount of food eaten between meals", example: "I had a snack after school.", pic: "🍪", pos: "n", ipa: "/snæk/", cat: "Food" },
  { word: "dessert", meaning: "a sweet dish eaten at the end of a meal", example: "We had ice cream for dessert.", pic: "🍰", pos: "n", ipa: "/dɪˈzɜːt/", cat: "Food" },
  { word: "meal", meaning: "an occasion when you eat food", example: "Dinner is the main meal of the day.", pic: "🍽️", pos: "n", ipa: "/miːl/", cat: "Food" },
  { word: "taste", meaning: "to try food to see what it is like", example: "Taste the sauce and add more salt.", pic: "👅", pos: "v", ipa: "/teɪst/", cat: "Food" },
  { word: "boil", meaning: "to cook food in very hot water", example: "Boil the potatoes for twenty minutes.", pic: "♨️", pos: "v", ipa: "/bɔɪl/", cat: "Food" },
  { word: "bake", meaning: "to cook food in an oven", example: "She baked a chocolate cake.", pic: "🍞", pos: "v", ipa: "/beɪk/", cat: "Food" },
  { word: "fry", meaning: "to cook food in hot oil", example: "He fried the eggs for breakfast.", pic: "🍳", pos: "v", ipa: "/fraɪ/", cat: "Food" },
  { word: "receipt", meaning: "a paper that shows you paid for something", example: "Keep the receipt in case you return it.", pic: "🧾", pos: "n", ipa: "/rɪˈsiːt/", cat: "Shopping" },
  { word: "bargain", meaning: "something bought for less than its usual price", example: "This jacket was a real bargain.", pic: "🏷️", pos: "n", ipa: "/ˈbɑːɡən/", cat: "Shopping" },
  { word: "refund", meaning: "money given back when you return something", example: "The shop gave me a full refund.", pic: "💸", pos: "n", ipa: "/ˈriːfʌnd/", cat: "Shopping" },
  { word: "discount", meaning: "a reduction in the price of something", example: "Students get a ten percent discount.", pic: "🔻", pos: "n", ipa: "/ˈdɪskaʊnt/", cat: "Shopping" },
  { word: "price", meaning: "the amount of money you pay for something", example: "The price of milk has gone up.", pic: "💲", pos: "n", ipa: "/praɪs/", cat: "Shopping" },
  { word: "purchase", meaning: "to buy something", example: "She purchased a new phone online.", pic: "🛍️", pos: "v", ipa: "/ˈpɜːtʃəs/", cat: "Shopping" },
  { word: "afford", meaning: "to have enough money to buy something", example: "We can't afford a new car this year.", pic: "💳", pos: "v", ipa: "/əˈfɔːd/", cat: "Shopping" },
  { word: "compare", meaning: "to look at things to see how they are similar or different", example: "Compare the prices before you buy.", pic: "⚖️", pos: "v", ipa: "/kəmˈpeə/", cat: "Shopping" },
  { word: "return", meaning: "to take something back to a shop", example: "I returned the shoes because they were too small.", pic: "↩️", pos: "v", ipa: "/rɪˈtɜːn/", cat: "Shopping" },
  { word: "symptom", meaning: "a sign that shows you are ill", example: "A cough is a common symptom of a cold.", pic: "🤧", pos: "n", ipa: "/ˈsɪmptəm/", cat: "Health" },
  { word: "treatment", meaning: "the medical care given to make someone better", example: "The treatment for the infection worked well.", pic: "💊", pos: "n", ipa: "/ˈtriːtmənt/", cat: "Health" },
  { word: "patient", meaning: "a person who is receiving medical care", example: "The patient is resting in bed.", pic: "🛏️", pos: "n", ipa: "/ˈpeɪʃnt/", cat: "Health" },
  { word: "injury", meaning: "damage to your body from an accident", example: "He suffered a leg injury in the game.", pic: "🤕", pos: "n", ipa: "/ˈɪndʒəri/", cat: "Health" },
  { word: "diet", meaning: "the food and drink a person usually has", example: "A healthy diet includes lots of fruit.", pic: "🥗", pos: "n", ipa: "/ˈdaɪət/", cat: "Health" },
  { word: "recover", meaning: "to become healthy again after being ill", example: "She is recovering from a bad flu.", pic: "💪", pos: "v", ipa: "/rɪˈkʌvə/", cat: "Health" },
  { word: "cure", meaning: "to make an illness go away", example: "This medicine will cure your headache.", pic: "💊", pos: "v", ipa: "/kjʊə/", cat: "Health" },
  { word: "injure", meaning: "to hurt someone or yourself", example: "He injured his arm while playing football.", pic: "🤕", pos: "v", ipa: "/ˈɪndʒə/", cat: "Health" },
  { word: "examine", meaning: "to look at something carefully", example: "The doctor examined my throat.", pic: "🔍", pos: "v", ipa: "/ɪɡˈzæmɪn/", cat: "Health" },
  { word: "subject", meaning: "a topic you study at school", example: "History is my favourite subject.", pic: "📚", pos: "n", ipa: "/ˈsʌbdʒɪkt/", cat: "School" },
  { word: "homework", meaning: "work given to students to do at home", example: "I finished my homework before dinner.", pic: "📝", pos: "n", ipa: "/ˈhəʊmwɜːk/", cat: "School" },
  { word: "exam", meaning: "a formal test of your knowledge", example: "She passed her final exam.", pic: "📄", pos: "n", ipa: "/ɪɡˈzæm/", cat: "School" },
  { word: "grade", meaning: "a mark showing the quality of your work", example: "He got a good grade in maths.", pic: "🎓", pos: "n", ipa: "/ɡreɪd/", cat: "School" },
  { word: "lesson", meaning: "a period of teaching", example: "We have a music lesson on Fridays.", pic: "🎵", pos: "n", ipa: "/ˈlesn/", cat: "School" },
  { word: "revise", meaning: "to study again before an exam", example: "I need to revise for the test tomorrow.", pic: "📖", pos: "v", ipa: "/rɪˈvaɪz/", cat: "School" },
  { word: "memorise", meaning: "to learn something so you remember it", example: "She memorised the poem for class.", pic: "🧠", pos: "v", ipa: "/ˈmeməraɪz/", cat: "School" },
  { word: "graduate", meaning: "to finish your studies at a school or university", example: "He will graduate from university in June.", pic: "🎓", pos: "v", ipa: "/ˈɡrædʒueɪt/", cat: "School" },
  { word: "explain", meaning: "to make something clear and easy to understand", example: "Can you explain this rule to me?", pic: "💡", pos: "v", ipa: "/ɪkˈspleɪn/", cat: "School" },
  { word: "ambition", meaning: "a strong wish to achieve something", example: "Her ambition is to become a doctor.", pic: "🌟", pos: "n", ipa: "/æmˈbɪʃn/", cat: "Goals" },
  { word: "goal", meaning: "something you want to achieve", example: "My goal is to run a marathon.", pic: "🎯", pos: "n", ipa: "/ɡəʊl/", cat: "Goals" },
  { word: "dream", meaning: "something you hope to do in the future", example: "His dream is to travel the world.", pic: "💭", pos: "n", ipa: "/driːm/", cat: "Goals" },
  { word: "plan", meaning: "an idea about how to do something", example: "We made a plan for the weekend.", pic: "🗺️", pos: "n", ipa: "/plæn/", cat: "Goals" },
  { word: "progress", meaning: "the process of getting better or moving forward", example: "She is making good progress in English.", pic: "📈", pos: "n", ipa: "/ˈprəʊɡres/", cat: "Goals" },
  { word: "achieve", meaning: "to succeed in doing something you wanted", example: "He achieved his goal of losing weight.", pic: "🏆", pos: "v", ipa: "/əˈtʃiːv/", cat: "Goals" },
  { word: "improve", meaning: "to make something better", example: "Practice will improve your writing.", pic: "📈", pos: "v", ipa: "/ɪmˈpruːv/", cat: "Goals" },
  { word: "succeed", meaning: "to do what you tried to do", example: "She succeeded in passing the exam.", pic: "✅", pos: "v", ipa: "/səkˈsiːd/", cat: "Goals" },
  { word: "attempt", meaning: "to try to do something", example: "He attempted to climb the mountain.", pic: "🧗", pos: "v", ipa: "/əˈtempt/", cat: "Goals" },
  { word: "hobby", meaning: "an activity you enjoy in your free time", example: "Photography is my favourite hobby.", pic: "📷", pos: "n", ipa: "/ˈhɒbi/", cat: "Leisure" },
  { word: "concert", meaning: "a live music performance", example: "We went to a concert last night.", pic: "🎤", pos: "n", ipa: "/ˈkɒnsət/", cat: "Leisure" },
  { word: "match", meaning: "a game between two teams or players", example: "The football match ended in a draw.", pic: "⚽", pos: "n", ipa: "/mætʃ/", cat: "Leisure" },
  { word: "ticket", meaning: "a piece of paper that lets you enter a place", example: "I bought a ticket for the cinema.", pic: "🎫", pos: "n", ipa: "/ˈtɪkɪt/", cat: "Leisure" },
  { word: "competition", meaning: "an event where people try to win", example: "She won first prize in the competition.", pic: "🏅", pos: "n", ipa: "/ˌkɒmpəˈtɪʃn/", cat: "Leisure" },
  { word: "relax", meaning: "to rest and become calm", example: "I relax by listening to music.", pic: "😌", pos: "v", ipa: "/rɪˈlæks/", cat: "Leisure" },
  { word: "enjoy", meaning: "to get pleasure from something", example: "We enjoyed the film very much.", pic: "😄", pos: "v", ipa: "/ɪnˈdʒɔɪ/", cat: "Leisure" },
  { word: "celebrate", meaning: "to do something special for a happy event", example: "We celebrated her birthday with a party.", pic: "🎉", pos: "v", ipa: "/ˈselɪbreɪt/", cat: "Leisure" },
  { word: "invite", meaning: "to ask someone to come to an event", example: "They invited us to their wedding.", pic: "💌", pos: "v", ipa: "/ɪnˈvaɪt/", cat: "Leisure" },
  { word: "luggage", meaning: "the bags you take when you travel", example: "My luggage was too heavy to carry.", pic: "🧳", pos: "n", ipa: "/ˈlʌɡɪdʒ/", cat: "Travel" },
  { word: "passport", meaning: "an official document for travelling abroad", example: "You need a passport to fly to another country.", pic: "🛂", pos: "n", ipa: "/ˈpɑːspɔːt/", cat: "Travel" },
  { word: "journey", meaning: "the act of travelling from one place to another", example: "The journey to the coast took three hours.", pic: "🚌", pos: "n", ipa: "/ˈdʒɜːni/", cat: "Travel" },
  { word: "destination", meaning: "the place you are travelling to", example: "Our destination is a small island.", pic: "🏝️", pos: "n", ipa: "/ˌdestɪˈneɪʃn/", cat: "Travel" },
  { word: "tourist", meaning: "a person who visits a place for pleasure", example: "The city is full of tourists in summer.", pic: "📸", pos: "n", ipa: "/ˈtʊərɪst/", cat: "Travel" },
  { word: "abroad", meaning: "in or to a foreign country", example: "She is studying abroad this year.", pic: "✈️", pos: "adv", ipa: "/əˈbrɔːd/", cat: "Travel" },
  { word: "arrive", meaning: "to reach the place you are going to", example: "We arrived at the hotel at noon.", pic: "🏨", pos: "v", ipa: "/əˈraɪv/", cat: "Travel" },
  { word: "depart", meaning: "to leave a place to go somewhere", example: "The train departs at nine o'clock.", pic: "🚉", pos: "v", ipa: "/dɪˈpɑːt/", cat: "Travel" },
  { word: "book", meaning: "to arrange to have a seat or room", example: "I booked a room for two nights.", pic: "📅", pos: "v", ipa: "/bʊk/", cat: "Travel" },
  { word: "device", meaning: "a machine or tool made for a purpose", example: "This device measures your heart rate.", pic: "📱", pos: "n", ipa: "/dɪˈvaɪs/", cat: "Tech" },
  { word: "screen", meaning: "the flat surface where images are shown", example: "The screen is too bright at night.", pic: "🖥️", pos: "n", ipa: "/skriːn/", cat: "Tech" },
  { word: "keyboard", meaning: "the set of keys you press to type", example: "She typed quickly on the keyboard.", pic: "⌨️", pos: "n", ipa: "/ˈkiːbɔːd/", cat: "Tech" },
  { word: "password", meaning: "a secret word that lets you enter a system", example: "Choose a strong password for your account.", pic: "🔒", pos: "n", ipa: "/ˈpɑːswɜːd/", cat: "Tech" },
  { word: "download", meaning: "to copy a file from the internet to your device", example: "I downloaded the app for free.", pic: "⬇️", pos: "v", ipa: "/ˌdaʊnˈləʊd/", cat: "Tech" },
  { word: "upload", meaning: "to send a file from your device to the internet", example: "She uploaded the photos to her page.", pic: "⬆️", pos: "v", ipa: "/ˌʌpˈləʊd/", cat: "Tech" },
  { word: "connect", meaning: "to join something to a network or device", example: "Connect the printer to your computer.", pic: "🔗", pos: "v", ipa: "/kəˈnekt/", cat: "Tech" },
  { word: "search", meaning: "to look for information on the internet", example: "I searched for the answer online.", pic: "🔎", pos: "v", ipa: "/sɜːtʃ/", cat: "Tech" }
];
window.LF_VOCAB_EXTRA["B2"] = [
  { word: "negotiation", meaning: "a formal discussion to reach an agreement", example: "The negotiation lasted for three days.", pic: "🤝", pos: "n", ipa: "/nɪˌɡəʊʃiˈeɪʃn/", cat: "Work" },
  { word: "workload", meaning: "the amount of work you have to do", example: "Her workload increased after the promotion.", pic: "📚", pos: "n", ipa: "/ˈwɜːkləʊd/", cat: "Work" },
  { word: "supervisor", meaning: "a person who watches over and directs workers", example: "My supervisor approved the new plan.", pic: "👔", pos: "n", ipa: "/ˈsuːpəvaɪzə/", cat: "Work" },
  { word: "recruit", meaning: "to find new people to join a company", example: "The firm is recruiting new engineers.", pic: "📢", pos: "v", ipa: "/rɪˈkruːt/", cat: "Work" },
  { word: "delegate", meaning: "to give part of your work to someone else", example: "A good manager knows how to delegate tasks.", pic: "📤", pos: "v", ipa: "/ˈdelɪɡeɪt/", cat: "Work" },
  { word: "collaborate", meaning: "to work together with others", example: "The two teams collaborated on the project.", pic: "🤝", pos: "v", ipa: "/kəˈlæbəreɪt/", cat: "Work" },
  { word: "specialise", meaning: "to focus on one particular area of work", example: "She specialises in corporate law.", pic: "🎯", pos: "v", ipa: "/ˈspeʃəlaɪz/", cat: "Work" },
  { word: "promote", meaning: "to give someone a higher position at work", example: "They promoted him to manager.", pic: "📈", pos: "v", ipa: "/prəˈməʊt/", cat: "Work" },
  { word: "acquaintance", meaning: "a person you know slightly but not well", example: "He is just an acquaintance from work.", pic: "👋", pos: "n", ipa: "/əˈkweɪntəns/", cat: "People" },
  { word: "peer", meaning: "a person of the same age or level as you", example: "Her peers respect her opinion.", pic: "👥", pos: "n", ipa: "/pɪə/", cat: "People" },
  { word: "mentor", meaning: "an experienced person who guides and advises you", example: "Her mentor helped her choose a career.", pic: "🧑‍🏫", pos: "n", ipa: "/ˈmentɔː/", cat: "People" },
  { word: "citizen", meaning: "a person who belongs to a country by law", example: "Every citizen has the right to vote.", pic: "🗳️", pos: "n", ipa: "/ˈsɪtɪzn/", cat: "People" },
  { word: "volunteer", meaning: "a person who works without being paid", example: "She works as a volunteer at the hospital.", pic: "💛", pos: "n", ipa: "/ˌvɒlənˈtɪə/", cat: "People" },
  { word: "generation", meaning: "all the people born around the same time", example: "The younger generation loves social media.", pic: "👨‍👩‍👧‍👦", pos: "n", ipa: "/ˌdʒenəˈreɪʃn/", cat: "People" },
  { word: "descendant", meaning: "a person related to someone who lived earlier", example: "He is a descendant of a famous writer.", pic: "🌳", pos: "n", ipa: "/dɪˈsendənt/", cat: "Family" },
  { word: "sibling", meaning: "a brother or sister", example: "She has two siblings, a brother and a sister.", pic: "👫", pos: "n", ipa: "/ˈsɪblɪŋ/", cat: "Family" },
  { word: "upbringing", meaning: "the way a child is raised by their family", example: "Her upbringing taught her to be honest.", pic: "🏡", pos: "n", ipa: "/ˈʌpbrɪŋɪŋ/", cat: "Family" },
  { word: "inherit", meaning: "to receive money or property from someone who died", example: "She inherited a house from her aunt.", pic: "🏠", pos: "v", ipa: "/ɪnˈherɪt/", cat: "Family" },
  { word: "adopt", meaning: "to legally take a child into your family", example: "They decided to adopt a child.", pic: "👶", pos: "v", ipa: "/əˈdɒpt/", cat: "Family" },
  { word: "raise", meaning: "to look after a child until they grow up", example: "She raised three children on her own.", pic: "👩‍👧", pos: "v", ipa: "/reɪz/", cat: "Family" },
  { word: "renovate", meaning: "to repair and improve a building", example: "They renovated the old kitchen.", pic: "🔨", pos: "v", ipa: "/ˈrenəveɪt/", cat: "Home" },
  { word: "interior", meaning: "the inside part of a building", example: "The interior of the house is very modern.", pic: "🛋️", pos: "n", ipa: "/ɪnˈtɪəriə/", cat: "Home" },
  { word: "appliance", meaning: "a machine used in the home", example: "The kitchen is full of new appliances.", pic: "🔌", pos: "n", ipa: "/əˈplaɪəns/", cat: "Home" },
  { word: "accommodation", meaning: "a place where you live or stay", example: "The hotel offers comfortable accommodation.", pic: "🏨", pos: "n", ipa: "/əˌkɒməˈdeɪʃn/", cat: "Home" },
  { word: "residence", meaning: "the place where someone lives", example: "The president's official residence is in the capital.", pic: "🏛️", pos: "n", ipa: "/ˈrezɪdəns/", cat: "Home" },
  { word: "furnish", meaning: "to put furniture in a room", example: "They furnished the flat with simple items.", pic: "🛏️", pos: "v", ipa: "/ˈfɜːnɪʃ/", cat: "Home" },
  { word: "occupy", meaning: "to live in or use a place", example: "The family occupies the top floor.", pic: "🏢", pos: "v", ipa: "/ˈɒkjupaɪ/", cat: "Home" },
  { word: "relocate", meaning: "to move to a new place to live or work", example: "The company relocated to a bigger city.", pic: "🚚", pos: "v", ipa: "/ˌriːləʊˈkeɪt/", cat: "Home" },
  { word: "commute", meaning: "to travel regularly between home and work", example: "She commutes to the city every day.", pic: "🚆", pos: "v", ipa: "/kəˈmjuːt/", cat: "Routine" },
  { word: "errand", meaning: "a short trip to do a small task", example: "I have a few errands to run after work.", pic: "🛒", pos: "n", ipa: "/ˈerənd/", cat: "Routine" },
  { word: "chore", meaning: "a boring job you must do at home", example: "Washing the dishes is my least favourite chore.", pic: "🧽", pos: "n", ipa: "/tʃɔː/", cat: "Routine" },
  { word: "allocate", meaning: "to give a share of time or money for a purpose", example: "We allocated two hours for the meeting.", pic: "⏱️", pos: "v", ipa: "/ˈæləkeɪt/", cat: "Routine" },
  { word: "prioritise", meaning: "to deal with the most important things first", example: "You should prioritise your health.", pic: "🥇", pos: "v", ipa: "/praɪˈɒrətaɪz/", cat: "Routine" },
  { word: "postpone", meaning: "to delay something to a later time", example: "They postponed the meeting until Friday.", pic: "⏸️", pos: "v", ipa: "/pəˈspəʊn/", cat: "Routine" },
  { word: "accomplish", meaning: "to succeed in finishing something", example: "She accomplished all her tasks for the day.", pic: "🏁", pos: "v", ipa: "/əˈkʌmplɪʃ/", cat: "Routine" },
  { word: "cuisine", meaning: "a style of cooking from a particular place", example: "Italian cuisine is popular worldwide.", pic: "🍝", pos: "n", ipa: "/kwɪˈziːn/", cat: "Food" },
  { word: "nutrition", meaning: "the process of getting the food your body needs", example: "Good nutrition is important for children.", pic: "🥦", pos: "n", ipa: "/njuˈtrɪʃn/", cat: "Food" },
  { word: "appetite", meaning: "the desire to eat food", example: "The long walk gave me a big appetite.", pic: "😋", pos: "n", ipa: "/ˈæpɪtaɪt/", cat: "Food" },
  { word: "portion", meaning: "an amount of food for one person", example: "The restaurant serves large portions.", pic: "🍽️", pos: "n", ipa: "/ˈpɔːʃn/", cat: "Food" },
  { word: "consume", meaning: "to eat or drink something", example: "People consume too much sugar.", pic: "🥤", pos: "v", ipa: "/kənˈsjuːm/", cat: "Food" },
  { word: "digest", meaning: "to break down food in your body", example: "It takes time to digest a heavy meal.", pic: "🫀", pos: "v", ipa: "/daɪˈdʒest/", cat: "Food" },
  { word: "whisk", meaning: "to mix food quickly with a tool", example: "Whisk the eggs until they are fluffy.", pic: "🥚", pos: "v", ipa: "/wɪsk/", cat: "Food" },
  { word: "retail", meaning: "the business of selling goods to the public", example: "She works in the retail sector.", pic: "🏬", pos: "n", ipa: "/ˈriːteɪl/", cat: "Shopping" },
  { word: "merchandise", meaning: "goods that are bought and sold", example: "The store sells branded merchandise.", pic: "🛍️", pos: "n", ipa: "/ˈmɜːtʃəndaɪs/", cat: "Shopping" },
  { word: "transaction", meaning: "the act of buying or selling something", example: "The transaction was completed online.", pic: "💳", pos: "n", ipa: "/trænˈzækʃn/", cat: "Shopping" },
  { word: "budget", meaning: "the money you plan to spend", example: "We stayed within our budget this month.", pic: "💰", pos: "n", ipa: "/ˈbʌdʒɪt/", cat: "Shopping" },
  { word: "expense", meaning: "money you spend on something", example: "Travel is a major expense for us.", pic: "💸", pos: "n", ipa: "/ɪkˈspens/", cat: "Shopping" },
  { word: "diagnosis", meaning: "the identification of an illness by a doctor", example: "The diagnosis was a mild infection.", pic: "🩺", pos: "n", ipa: "/ˌdaɪəɡˈnəʊsɪs/", cat: "Health" },
  { word: "therapy", meaning: "treatment to help someone recover", example: "He attends therapy for his back pain.", pic: "🛋️", pos: "n", ipa: "/ˈθerəpi/", cat: "Health" },
  { word: "immunity", meaning: "the body's ability to resist illness", example: "Vaccines build immunity to disease.", pic: "🛡️", pos: "n", ipa: "/ɪˈmjuːnəti/", cat: "Health" },
  { word: "prescription", meaning: "a doctor's written order for medicine", example: "You need a prescription for this drug.", pic: "📋", pos: "n", ipa: "/prɪˈskrɪpʃn/", cat: "Health" },
  { word: "diagnose", meaning: "to identify an illness", example: "The doctor diagnosed her with diabetes.", pic: "🩺", pos: "v", ipa: "/ˈdaɪəɡnəʊz/", cat: "Health" },
  { word: "prescribe", meaning: "to order medicine for a patient", example: "The doctor prescribed antibiotics.", pic: "💊", pos: "v", ipa: "/prɪˈskraɪb/", cat: "Health" },
  { word: "curriculum", meaning: "the subjects taught in a school", example: "The curriculum includes art and music.", pic: "📚", pos: "n", ipa: "/kəˈrɪkjələm/", cat: "School" },
  { word: "scholarship", meaning: "money given to help a student study", example: "She won a scholarship to university.", pic: "🎓", pos: "n", ipa: "/ˈskɒləʃɪp/", cat: "School" },
  { word: "lecture", meaning: "a formal talk given to students", example: "The lecture on history was fascinating.", pic: "🎤", pos: "n", ipa: "/ˈlektʃə/", cat: "School" },
  { word: "assignment", meaning: "a piece of work given to a student", example: "The assignment is due next Monday.", pic: "📝", pos: "n", ipa: "/əˈsaɪnmənt/", cat: "School" },
  { word: "discipline", meaning: "a subject or area of study", example: "Psychology is a fascinating discipline.", pic: "🧠", pos: "n", ipa: "/ˈdɪsəplɪn/", cat: "School" },
  { word: "enrol", meaning: "to officially join a course or school", example: "She enrolled in a language course.", pic: "📝", pos: "v", ipa: "/ɪnˈrəʊl/", cat: "School" },
  { word: "comprehend", meaning: "to understand something fully", example: "It took time to comprehend the theory.", pic: "🧠", pos: "v", ipa: "/ˌkɒmprɪˈhend/", cat: "School" },
  { word: "aspiration", meaning: "a strong hope or ambition", example: "Her aspiration is to lead the company.", pic: "🌟", pos: "n", ipa: "/ˌæspəˈreɪʃn/", cat: "Goals" },
  { word: "milestone", meaning: "an important event in your progress", example: "Graduating was a major milestone for her.", pic: "🏁", pos: "n", ipa: "/ˈmaɪlstəʊn/", cat: "Goals" },
  { word: "objective", meaning: "a goal you want to reach", example: "Our main objective is to increase sales.", pic: "🎯", pos: "n", ipa: "/əbˈdʒektɪv/", cat: "Goals" },
  { word: "motivation", meaning: "the reason that makes you want to do something", example: "Money is not his only motivation.", pic: "🔥", pos: "n", ipa: "/ˌməʊtɪˈveɪʃn/", cat: "Goals" },
  { word: "fulfil", meaning: "to achieve something you hoped for", example: "She fulfilled her dream of becoming a pilot.", pic: "✨", pos: "v", ipa: "/fʊlˈfɪl/", cat: "Goals" },
  { word: "strive", meaning: "to try very hard to achieve something", example: "They strive for excellence in everything.", pic: "💪", pos: "v", ipa: "/straɪv/", cat: "Goals" },
  { word: "pursue", meaning: "to follow a goal or career", example: "He decided to pursue a career in law.", pic: "🏃", pos: "v", ipa: "/pəˈsjuː/", cat: "Goals" },
  { word: "overcome", meaning: "to succeed in dealing with a problem", example: "She overcame her fear of public speaking.", pic: "🏆", pos: "v", ipa: "/ˌəʊvəˈkʌm/", cat: "Goals" },
  { word: "recreation", meaning: "activities done for enjoyment in free time", example: "The park is used for recreation.", pic: "🎾", pos: "n", ipa: "/ˌrekriˈeɪʃn/", cat: "Leisure" },
  { word: "spectator", meaning: "a person who watches a sport or event", example: "The spectators cheered loudly.", pic: "📣", pos: "n", ipa: "/spekˈteɪtə/", cat: "Leisure" },
  { word: "pastime", meaning: "an activity you enjoy in your free time", example: "Reading is her favourite pastime.", pic: "📖", pos: "n", ipa: "/ˈpɑːstaɪm/", cat: "Leisure" },
  { word: "entertainment", meaning: "things that amuse or interest people", example: "The city offers plenty of entertainment.", pic: "🎭", pos: "n", ipa: "/ˌentəˈteɪnmənt/", cat: "Leisure" },
  { word: "leisure", meaning: "time when you are not working", example: "She spends her leisure time painting.", pic: "🎨", pos: "n", ipa: "/ˈleʒə/", cat: "Leisure" },
  { word: "indulge", meaning: "to allow yourself to enjoy something", example: "I indulged in a slice of chocolate cake.", pic: "🍰", pos: "v", ipa: "/ɪnˈdʌldʒ/", cat: "Leisure" },
  { word: "unwind", meaning: "to relax after work or stress", example: "A warm bath helps me unwind.", pic: "🛁", pos: "v", ipa: "/ˌʌnˈwaɪnd/", cat: "Leisure" },
  { word: "itinerary", meaning: "a plan of a journey with times and places", example: "Our itinerary includes three cities.", pic: "🗺️", pos: "n", ipa: "/aɪˈtɪnərəri/", cat: "Travel" },
  { word: "expedition", meaning: "a long journey for a special purpose", example: "They joined an expedition to the desert.", pic: "🐪", pos: "n", ipa: "/ˌekspəˈdɪʃn/", cat: "Travel" },
  { word: "souvenir", meaning: "an object you keep to remember a place", example: "She bought a souvenir from the market.", pic: "🎁", pos: "n", ipa: "/ˌsuːvəˈnɪə/", cat: "Travel" },
  { word: "frontier", meaning: "the border between two countries", example: "They crossed the frontier into France.", pic: "🚧", pos: "n", ipa: "/ˈfrʌntɪə/", cat: "Travel" },
  { word: "embark", meaning: "to begin a journey or new project", example: "They embarked on a trip around the world.", pic: "⛵", pos: "v", ipa: "/ɪmˈbɑːk/", cat: "Travel" },
  { word: "wander", meaning: "to walk around without a clear direction", example: "We wandered through the old town.", pic: "🚶", pos: "v", ipa: "/ˈwɒndə/", cat: "Travel" },
  { word: "explore", meaning: "to travel around a place to learn about it", example: "We explored the caves near the coast.", pic: "🧭", pos: "v", ipa: "/ɪkˈsplɔː/", cat: "Travel" },
  { word: "software", meaning: "the programs that run on a computer", example: "The new software fixes many bugs.", pic: "💻", pos: "n", ipa: "/ˈsɒftweə/", cat: "Tech" },
  { word: "hardware", meaning: "the physical parts of a computer", example: "The hardware is fast and reliable.", pic: "🖥️", pos: "n", ipa: "/ˈhɑːdweə/", cat: "Tech" },
  { word: "algorithm", meaning: "a set of steps a computer follows to solve a problem", example: "The algorithm sorts the data quickly.", pic: "🤖", pos: "n", ipa: "/ˈælɡərɪðəm/", cat: "Tech" },
  { word: "interface", meaning: "the way a user interacts with a program", example: "The app has a simple interface.", pic: "🖱️", pos: "n", ipa: "/ˈɪntəfeɪs/", cat: "Tech" },
  { word: "database", meaning: "a large collection of stored information", example: "The database holds millions of records.", pic: "🗄️", pos: "n", ipa: "/ˈdeɪtəbeɪs/", cat: "Tech" },
  { word: "encrypt", meaning: "to change data into a secret code", example: "The app encrypts your messages.", pic: "🔐", pos: "v", ipa: "/ɪnˈkrɪpt/", cat: "Tech" },
  { word: "install", meaning: "to put a program onto a device", example: "I installed the update last night.", pic: "📲", pos: "v", ipa: "/ɪnˈstɔːl/", cat: "Tech" },
  { word: "navigate", meaning: "to move around a website or app", example: "It's easy to navigate the new site.", pic: "🧭", pos: "v", ipa: "/ˈnævɪɡeɪt/", cat: "Tech" },
  { word: "ecosystem", meaning: "all the living things in an area and their environment", example: "The forest is a delicate ecosystem.", pic: "🌳", pos: "n", ipa: "/ˈiːkəʊsɪstəm/", cat: "Nature" },
  { word: "habitat", meaning: "the natural home of an animal or plant", example: "The wetland is a habitat for birds.", pic: "🦆", pos: "n", ipa: "/ˈhæbɪtæt/", cat: "Nature" },
  { word: "landscape", meaning: "the visible features of an area of land", example: "The landscape is covered in green hills.", pic: "🏞️", pos: "n", ipa: "/ˈlændskeɪp/", cat: "Nature" },
  { word: "vegetation", meaning: "the plants growing in a place", example: "Dense vegetation covers the valley.", pic: "🌿", pos: "n", ipa: "/ˌvedʒəˈteɪʃn/", cat: "Nature" },
  { word: "biodiversity", meaning: "the variety of living things in an area", example: "The rainforest has high biodiversity.", pic: "🦋", pos: "n", ipa: "/ˌbaɪəʊdaɪˈvɜːsəti/", cat: "Nature" },
  { word: "flourish", meaning: "to grow or develop well", example: "These plants flourish in warm weather.", pic: "🌺", pos: "v", ipa: "/ˈflʌrɪʃ/", cat: "Nature" },
  { word: "erode", meaning: "to gradually wear away by wind or water", example: "The river eroded the riverbank.", pic: "🌊", pos: "v", ipa: "/ɪˈrəʊd/", cat: "Nature" },
  { word: "thrive", meaning: "to grow and do very well", example: "The business thrived in the new market.", pic: "🌱", pos: "v", ipa: "/θraɪv/", cat: "Nature" },
  { word: "heritage", meaning: "the traditions and history passed down from the past", example: "The castle is part of our national heritage.", pic: "🏰", pos: "n", ipa: "/ˈherɪtɪdʒ/", cat: "Culture" },
  { word: "folklore", meaning: "traditional stories and beliefs of a people", example: "The region is rich in folklore.", pic: "📜", pos: "n", ipa: "/ˈfəʊklɔː/", cat: "Culture" },
  { word: "ritual", meaning: "a set of actions done in a fixed way", example: "The ceremony includes a special ritual.", pic: "🕯️", pos: "n", ipa: "/ˈrɪtʃuəl/", cat: "Culture" },
  { word: "artefact", meaning: "an object made by people in the past", example: "The museum displays ancient artefacts.", pic: "🏺", pos: "n", ipa: "/ˈɑːtɪfækt/", cat: "Culture" },
  { word: "immerse", meaning: "to become fully involved in something", example: "She immersed herself in the local culture.", pic: "🌊", pos: "v", ipa: "/ɪˈmɜːs/", cat: "Culture" },
  { word: "assimilate", meaning: "to become part of a new culture or group", example: "The newcomers slowly assimilated into society.", pic: "🫂", pos: "v", ipa: "/əˈsɪməleɪt/", cat: "Culture" },
  { word: "hypothesis", meaning: "an idea that can be tested by research", example: "The experiment tested the hypothesis.", pic: "🔬", pos: "n", ipa: "/haɪˈpɒθəsɪs/", cat: "Science" },
  { word: "phenomenon", meaning: "a fact or event that can be observed", example: "Lightning is a natural phenomenon.", pic: "⚡", pos: "n", ipa: "/fəˈnɒmɪnən/", cat: "Science" },
  { word: "analysis", meaning: "the careful study of something", example: "The analysis of the data took a week.", pic: "📊", pos: "n", ipa: "/əˈnæləsɪs/", cat: "Science" },
  { word: "laboratory", meaning: "a room where scientific work is done", example: "The samples were tested in the laboratory.", pic: "🧪", pos: "n", ipa: "/ləˈbɒrətri/", cat: "Science" },
  { word: "specimen", meaning: "a sample used for scientific study", example: "They collected a specimen of the plant.", pic: "🌿", pos: "n", ipa: "/ˈspesɪmən/", cat: "Science" },
  { word: "analyse", meaning: "to study something in detail", example: "We analysed the results carefully.", pic: "🔍", pos: "v", ipa: "/ˈænəlaɪz/", cat: "Science" },
  { word: "verify", meaning: "to check that something is true", example: "The team verified the findings.", pic: "✅", pos: "v", ipa: "/ˈverɪfaɪ/", cat: "Science" },
  { word: "hypothesise", meaning: "to suggest an idea that can be tested", example: "Scientists hypothesised about the cause.", pic: "💭", pos: "v", ipa: "/haɪˈpɒθəsaɪz/", cat: "Science" },
  { word: "debate", meaning: "a formal discussion of opposing views", example: "The debate about the new law was lively.", pic: "🗣️", pos: "n", ipa: "/dɪˈbeɪt/", cat: "Talk" },
  { word: "persuade", meaning: "to make someone agree with you", example: "She persuaded me to join the club.", pic: "💬", pos: "v", ipa: "/pəˈsweɪd/", cat: "Talk" },
  { word: "convey", meaning: "to communicate an idea or feeling", example: "His tone conveyed his frustration.", pic: "📨", pos: "v", ipa: "/kənˈveɪ/", cat: "Talk" },
  { word: "articulate", meaning: "to express ideas clearly in words", example: "She articulated her views clearly.", pic: "🗣️", pos: "v", ipa: "/ɑːˈtɪkjuleɪt/", cat: "Talk" },
  { word: "clarify", meaning: "to make something easier to understand", example: "Could you clarify what you mean?", pic: "💡", pos: "v", ipa: "/ˈklærəfaɪ/", cat: "Talk" },
  { word: "assert", meaning: "to state something firmly and clearly", example: "He asserted that the plan would work.", pic: "✊", pos: "v", ipa: "/əˈsɜːt/", cat: "Talk" },
  { word: "concede", meaning: "to admit that something is true", example: "She conceded that she was wrong.", pic: "🙇", pos: "v", ipa: "/kənˈsiːd/", cat: "Talk" },
  { word: "emphasise", meaning: "to give special importance to something", example: "He emphasised the need for safety.", pic: "🔊", pos: "v", ipa: "/ˈemfəsaɪz/", cat: "Talk" }
];
