/* Extra vocabulary — levels C1, C2 */
window.LF_VOCAB_EXTRA = window.LF_VOCAB_EXTRA || {};
window.LF_VOCAB_EXTRA["C1"] = [
  { word: "abolish", meaning: "to officially end a law, system or practice", example: "The government plans to abolish the old tax.", pic: "🚫", pos: "v", ipa: "/əˈbɒlɪʃ/", cat: "Culture" },
  { word: "abstract", meaning: "existing as an idea rather than a physical thing", example: "Justice is an abstract concept.", pic: "💭", pos: "adj", ipa: "/ˈæbstrækt/", cat: "Science" },
  { word: "accomplish", meaning: "to succeed in doing something", example: "She accomplished all her goals this year.", pic: "🏆", pos: "v", ipa: "/əˈkʌmplɪʃ/", cat: "Goals" },
  { word: "accurate", meaning: "completely correct and exact", example: "The report must be accurate.", pic: "🎯", pos: "adj", ipa: "/ˈækjərət/", cat: "Science" },
  { word: "acknowledge", meaning: "to accept or admit that something is true", example: "He acknowledged his mistake openly.", pic: "🤝", pos: "v", ipa: "/əkˈnɒlɪdʒ/", cat: "Talk" },
  { word: "acquire", meaning: "to get or gain something through effort", example: "She acquired a new skill quickly.", pic: "📈", pos: "v", ipa: "/əˈkwaɪə/", cat: "Goals" },
  { word: "adapt (c1)", meaning: "to change to suit new conditions", example: "Animals adapt to their environment.", pic: "🦎", pos: "v", ipa: "/əˈdæpt/", cat: "Nature" },
  { word: "adequate", meaning: "enough for what is needed", example: "The room has adequate space for ten people.", pic: "✔️", pos: "adj", ipa: "/ˈædɪkwət/", cat: "Talk" },
  { word: "advocate", meaning: "to support an idea publicly", example: "She advocates for better schools.", pic: "📢", pos: "v", ipa: "/ˈædvəkeɪt/", cat: "Culture" },
  { word: "affluent", meaning: "having a lot of money; rich", example: "They live in an affluent neighbourhood.", pic: "💰", pos: "adj", ipa: "/ˈæfluənt/", cat: "Economy" },
  { word: "agenda", meaning: "a list of things to discuss", example: "The first item on the agenda is safety.", pic: "📋", pos: "n", ipa: "/əˈdʒendə/", cat: "Work" },
  { word: "allocate", meaning: "to give resources for a purpose", example: "The city allocates money for parks.", pic: "💸", pos: "v", ipa: "/ˈæləkeɪt/", cat: "Work" },
  { word: "ambiguous", meaning: "able to be understood in more than one way", example: "The sentence is ambiguous without context.", pic: "🌫️", pos: "adj", ipa: "/æmˈbɪɡjuəs/", cat: "Talk" },
  { word: "amend", meaning: "to change a document or law", example: "They amended the contract yesterday.", pic: "📝", pos: "v", ipa: "/əˈmend/", cat: "Culture" },
  { word: "anticipate", meaning: "to expect something will happen", example: "We anticipate a busy weekend.", pic: "🔮", pos: "v", ipa: "/ænˈtɪsɪpeɪt/", cat: "Goals" },
  { word: "apparent", meaning: "easy to see or understand", example: "It became apparent that we were lost.", pic: "👀", pos: "adj", ipa: "/əˈpærənt/", cat: "Talk" },
  { word: "appreciate", meaning: "to be grateful for or understand the value of something", example: "I appreciate your help very much.", pic: "🙏", pos: "v", ipa: "/əˈpriːʃieɪt/", cat: "Emotions" },
  { word: "appropriate", meaning: "right for a situation", example: "Wear appropriate clothes for the interview.", pic: "✅", pos: "adj", ipa: "/əˈprəʊpriət/", cat: "Talk" },
  { word: "arbitrary", meaning: "based on chance rather than a reason", example: "The decision seemed completely arbitrary.", pic: "🎲", pos: "adj", ipa: "/ˈɑːbɪtrəri/", cat: "Science" },
  { word: "assess", meaning: "to judge the quality or value of something", example: "Teachers assess students' progress monthly.", pic: "📊", pos: "v", ipa: "/əˈses/", cat: "School" },
  { word: "assume (c1)", meaning: "to think something is true without proof", example: "I assume the train will be on time.", pic: "🤔", pos: "v", ipa: "/əˈsjuːm/", cat: "Talk" },
  { word: "attain", meaning: "to reach a goal or level", example: "He attained the highest score in the class.", pic: "🏔️", pos: "v", ipa: "/əˈteɪn/", cat: "Goals" },
  { word: "attribute", meaning: "to say that something is caused by someone or something", example: "She attributes her success to hard work.", pic: "🔗", pos: "v", ipa: "/əˈtrɪbjuːt/", cat: "Talk" },
  { word: "authentic", meaning: "real and true, not a copy", example: "The museum shows authentic ancient coins.", pic: "📜", pos: "adj", ipa: "/ɔːˈθentɪk/", cat: "Culture" },
  { word: "barely", meaning: "almost not", example: "I could barely hear her voice.", pic: "🙉", pos: "adv", ipa: "/ˈbeəli/", cat: "Talk" },
  { word: "beneficial", meaning: "helpful or good for someone", example: "Exercise is beneficial for your heart.", pic: "💚", pos: "adj", ipa: "/ˌbenɪˈfɪʃl/", cat: "Health" },
  { word: "bias", meaning: "an unfair preference for or against something", example: "The study shows a bias in the results.", pic: "⚖️", pos: "n", ipa: "/ˈbaɪəs/", cat: "Science" },
  { word: "boost", meaning: "to increase or improve something", example: "The news boosted their confidence.", pic: "🚀", pos: "v", ipa: "/buːst/", cat: "Goals" },
  { word: "boundary", meaning: "a line that separates two areas or ideas", example: "Respect the boundary between work and home.", pic: "🧱", pos: "n", ipa: "/ˈbaʊndri/", cat: "Talk" },
  { word: "capacity", meaning: "the ability or amount something can hold", example: "The hall has a capacity of 500 people.", pic: "📦", pos: "n", ipa: "/kəˈpæsəti/", cat: "Work" },
  { word: "catastrophe", meaning: "a terrible disaster", example: "The flood was a catastrophe for the town.", pic: "🌊", pos: "n", ipa: "/kəˈtæstrəfi/", cat: "Environment" },
  { word: "circumstance", meaning: "a condition or fact connected with a situation", example: "Under the circumstances, we must wait.", pic: "🌪️", pos: "n", ipa: "/ˈsɜːkəmstəns/", cat: "Talk" },
  { word: "clarity", meaning: "the quality of being clear and easy to understand", example: "Clarity is essential in scientific writing.", pic: "💡", pos: "n", ipa: "/ˈklærəti/", cat: "Talk" },
  { word: "coincide", meaning: "to happen at the same time or in the same place", example: "My holiday coincides with hers.", pic: "📅", pos: "v", ipa: "/ˌkəʊɪnˈsaɪd/", cat: "Routine" },
  { word: "collapse", meaning: "to fall down suddenly", example: "The old bridge collapsed in the storm.", pic: "💥", pos: "v", ipa: "/kəˈlæps/", cat: "Environment" },
  { word: "compensate", meaning: "to pay or act to make up for something", example: "The company compensated the customers.", pic: "💷", pos: "v", ipa: "/ˈkɒmpenseɪt/", cat: "Work" },
  { word: "compile", meaning: "to collect information into one list or book", example: "She compiled a report from the data.", pic: "🗂️", pos: "v", ipa: "/kəmˈpaɪl/", cat: "Science" },
  { word: "comprehensive", meaning: "including everything or nearly everything", example: "The guide is comprehensive and detailed.", pic: "📚", pos: "adj", ipa: "/ˌkɒmprɪˈhensɪv/", cat: "School" },
  { word: "conceive", meaning: "to think of or imagine something", example: "He conceived a brilliant plan.", pic: "💭", pos: "v", ipa: "/kənˈsiːv/", cat: "Goals" },
  { word: "conclude (c1)", meaning: "to decide something after thinking about it", example: "We concluded that the idea would work.", pic: "🔚", pos: "v", ipa: "/kənˈkluːd/", cat: "Talk" },
  { word: "confidential", meaning: "secret and private", example: "This information is strictly confidential.", pic: "🔒", pos: "adj", ipa: "/ˌkɒnfɪˈdenʃl/", cat: "Work" },
  { word: "conform", meaning: "to follow rules or standards", example: "Students must conform to the school rules.", pic: "📏", pos: "v", ipa: "/kənˈfɔːm/", cat: "Culture" },
  { word: "consecutive", meaning: "following one after another without a break", example: "It rained for three consecutive days.", pic: "🔢", pos: "adj", ipa: "/kənˈsekjətɪv/", cat: "Routine" },
  { word: "consent", meaning: "permission to do something", example: "You need parental consent for the trip.", pic: "✅", pos: "n", ipa: "/kənˈsent/", cat: "Talk" },
  { word: "consequently", meaning: "as a result", example: "The roads were wet; consequently, we drove slowly.", pic: "➡️", pos: "adv", ipa: "/ˈkɒnsɪkwəntli/", cat: "Talk" },
  { word: "consistent", meaning: "always behaving or happening in the same way", example: "She is consistent in her work.", pic: "🔁", pos: "adj", ipa: "/kənˈsɪstənt/", cat: "Work" },
  { word: "consume", meaning: "to eat, drink or use something", example: "The machine consumes a lot of energy.", pic: "⚡", pos: "v", ipa: "/kənˈsjuːm/", cat: "Environment" },
  { word: "contemplate", meaning: "to think about something deeply", example: "She contemplated the offer for days.", pic: "🧠", pos: "v", ipa: "/ˈkɒntəmpleɪt/", cat: "Goals" },
  { word: "contradict", meaning: "to say the opposite of what someone said", example: "The witness contradicted his own story.", pic: "❌", pos: "v", ipa: "/ˌkɒntrəˈdɪkt/", cat: "Talk" },
  { word: "controversial", meaning: "causing strong disagreement", example: "The new law is highly controversial.", pic: "🔥", pos: "adj", ipa: "/ˌkɒntrəˈvɜːʃl/", cat: "Culture" },
  { word: "convey", meaning: "to express a message or feeling", example: "Her smile conveyed gratitude.", pic: "💬", pos: "v", ipa: "/kənˈveɪ/", cat: "Talk" },
  { word: "convince", meaning: "to make someone believe something", example: "He convinced me to join the team.", pic: "🤝", pos: "v", ipa: "/kənˈvɪns/", cat: "Talk" },
  { word: "criterion", meaning: "a standard used to judge something", example: "Cost is a key criterion for the decision.", pic: "📏", pos: "n", ipa: "/kraɪˈtɪəriən/", cat: "Science" },
  { word: "crucial", meaning: "extremely important", example: "Sleep is crucial for good health.", pic: "🔑", pos: "adj", ipa: "/ˈkruːʃl/", cat: "Talk" },
  { word: "dedicate", meaning: "to give a lot of time and energy to something", example: "She dedicated herself to teaching.", pic: "🎯", pos: "v", ipa: "/ˈdedɪkeɪt/", cat: "Goals" },
  { word: "deduce", meaning: "to work out the truth from facts", example: "We deduced the answer from the clues.", pic: "🧩", pos: "v", ipa: "/dɪˈdjuːs/", cat: "Science" },
  { word: "deficiency", meaning: "a lack of something needed", example: "A vitamin deficiency causes tiredness.", pic: "🥀", pos: "n", ipa: "/dɪˈfɪʃnsi/", cat: "Health" },
  { word: "delegate", meaning: "to give work to another person", example: "A good manager delegates tasks.", pic: "📤", pos: "v", ipa: "/ˈdelɪɡeɪt/", cat: "Work" },
  { word: "deliberate", meaning: "done on purpose", example: "It was a deliberate act of kindness.", pic: "🎯", pos: "adj", ipa: "/dɪˈlɪbərət/", cat: "Talk" },
  { word: "demonstrate", meaning: "to show or prove something clearly", example: "The experiment demonstrates the theory.", pic: "🔬", pos: "v", ipa: "/ˈdemənstreɪt/", cat: "Science" },
  { word: "denote", meaning: "to mean or represent something", example: "A red light denotes danger.", pic: "🔴", pos: "v", ipa: "/dɪˈnəʊt/", cat: "Science" },
  { word: "deprive", meaning: "to take away something needed", example: "Lack of sleep deprives you of energy.", pic: "🚫", pos: "v", ipa: "/dɪˈpraɪv/", cat: "Health" },
  { word: "derive", meaning: "to get something from a source", example: "The word derives from Latin.", pic: "🔤", pos: "v", ipa: "/dɪˈraɪv/", cat: "Culture" },
  { word: "deteriorate", meaning: "to become worse", example: "His health deteriorated quickly.", pic: "📉", pos: "v", ipa: "/dɪˈtɪəriəreɪt/", cat: "Health" },
  { word: "deviation", meaning: "a difference from what is normal", example: "Any deviation from the plan is risky.", pic: "↗️", pos: "n", ipa: "/ˌdiːviˈeɪʃn/", cat: "Science" },
  { word: "diminish", meaning: "to become smaller or less", example: "The noise diminished as we left.", pic: "🔉", pos: "v", ipa: "/dɪˈmɪnɪʃ/", cat: "Talk" },
  { word: "disclose", meaning: "to make secret information known", example: "The bank must disclose the fees.", pic: "🔓", pos: "v", ipa: "/dɪsˈkləʊz/", cat: "Work" },
  { word: "discriminate", meaning: "to treat people unfairly because of a difference", example: "The law forbids employers to discriminate.", pic: "⚖️", pos: "v", ipa: "/dɪˈskrɪmɪneɪt/", cat: "Culture" },
  { word: "displace", meaning: "to force people to leave their home", example: "The war displaced thousands of families.", pic: "🏚️", pos: "v", ipa: "/dɪsˈpleɪs/", cat: "Environment" },
  { word: "distinct", meaning: "clearly different", example: "The two species are quite distinct.", pic: "🔀", pos: "adj", ipa: "/dɪˈstɪŋkt/", cat: "Science" },
  { word: "distort", meaning: "to change the truth or shape of something", example: "The media distorted the facts.", pic: "🌀", pos: "v", ipa: "/dɪˈstɔːt/", cat: "Talk" },
  { word: "distribute", meaning: "to give things to many people", example: "They distributed food to the poor.", pic: "📦", pos: "v", ipa: "/dɪˈstrɪbjuːt/", cat: "Work" },
  { word: "diverse", meaning: "very different from each other", example: "The city has a diverse population.", pic: "🌈", pos: "adj", ipa: "/daɪˈvɜːs/", cat: "Culture" },
  { word: "domestic", meaning: "relating to home or one's own country", example: "Domestic flights are cheaper.", pic: "🏠", pos: "adj", ipa: "/dəˈmestɪk/", cat: "Travel" },
  { word: "dominant", meaning: "stronger or more important than others", example: "She has a dominant role in the company.", pic: "👑", pos: "adj", ipa: "/ˈdɒmɪnənt/", cat: "Work" },
  { word: "durable", meaning: "strong and lasting a long time", example: "These boots are durable and comfortable.", pic: "🛡️", pos: "adj", ipa: "/ˈdjʊərəbl/", cat: "Shopping" },
  { word: "dwell", meaning: "to live in a place", example: "They dwell in a remote valley.", pic: "🏡", pos: "v", ipa: "/dwel/", cat: "Home" },
  { word: "efficient (c1)", meaning: "working well without wasting time or energy", example: "The new system is more efficient.", pic: "⚙️", pos: "adj", ipa: "/ɪˈfɪʃnt/", cat: "Work" },
  { word: "elaborate", meaning: "detailed and complicated", example: "They gave an elaborate explanation.", pic: "🧩", pos: "adj", ipa: "/ɪˈlæbərət/", cat: "Talk" },
  { word: "elevate", meaning: "to raise to a higher level", example: "The speech elevated everyone's mood.", pic: "⏫", pos: "v", ipa: "/ˈelɪveɪt/", cat: "Talk" },
  { word: "eliminate", meaning: "to completely remove something", example: "The new method eliminates waste.", pic: "🗑️", pos: "v", ipa: "/ɪˈlɪmɪneɪt/", cat: "Environment" },
  { word: "emerge", meaning: "to come out into view or become known", example: "New evidence emerged last week.", pic: "🌅", pos: "v", ipa: "/iˈmɜːdʒ/", cat: "Science" },
  { word: "emphasise", meaning: "to give special importance to something", example: "The course emphasises practical skills.", pic: "❗", pos: "v", ipa: "/ˈemfəsaɪz/", cat: "Talk" },
  { word: "endeavour", meaning: "to try hard to do something", example: "We endeavour to provide the best service.", pic: "💪", pos: "v", ipa: "/ɪnˈdevə/", cat: "Goals" },
  { word: "endure", meaning: "to suffer something difficult without giving up", example: "The soldiers endured terrible conditions.", pic: "🧗", pos: "v", ipa: "/ɪnˈdjʊə/", cat: "Goals" },
  { word: "enhance", meaning: "to improve the quality or value of something", example: "Lighting can enhance a room.", pic: "✨", pos: "v", ipa: "/ɪnˈhɑːns/", cat: "Home" },
  { word: "enormous", meaning: "extremely large", example: "The building is enormous.", pic: "🐘", pos: "adj", ipa: "/ɪˈnɔːməs/", cat: "Talk" },
  { word: "ensure", meaning: "to make certain that something happens", example: "Please ensure the door is locked.", pic: "🔒", pos: "v", ipa: "/ɪnˈʃʊə/", cat: "Work" },
  { word: "entitle", meaning: "to give someone the right to something", example: "The ticket entitles you to free parking.", pic: "🎟️", pos: "v", ipa: "/ɪnˈtaɪtl/", cat: "Shopping" },
  { word: "equilibrium", meaning: "a state of balance", example: "The ecosystem reached a new equilibrium.", pic: "⚖️", pos: "n", ipa: "/ˌiːkwɪˈlɪbriəm/", cat: "Science" },
  { word: "evident", meaning: "clearly seen or understood", example: "It was evident that she was upset.", pic: "👁️", pos: "adj", ipa: "/ˈevɪdənt/", cat: "Talk" },
  { word: "evolve", meaning: "to develop gradually", example: "Technology evolves very quickly.", pic: "🧬", pos: "v", ipa: "/iˈvɒlv/", cat: "Science" },
  { word: "exceed", meaning: "to be greater than a number or limit", example: "The cost exceeded our budget.", pic: "📈", pos: "v", ipa: "/ɪkˈsiːd/", cat: "Work" },
  { word: "explicit", meaning: "stated clearly and directly", example: "She gave explicit instructions.", pic: "📢", pos: "adj", ipa: "/ɪkˈsplɪsɪt/", cat: "Talk" },
  { word: "exploit", meaning: "to use something unfairly for your own benefit", example: "The company exploited cheap labour.", pic: "🕸️", pos: "v", ipa: "/ɪkˈsplɔɪt/", cat: "Culture" },
  { word: "extensive", meaning: "covering a large area or amount", example: "The fire caused extensive damage.", pic: "🌊", pos: "adj", ipa: "/ɪkˈstensɪv/", cat: "Environment" },
  { word: "feasible", meaning: "possible to do successfully", example: "The plan is technically feasible.", pic: "✅", pos: "adj", ipa: "/ˈfiːzəbl/", cat: "Goals" },
  { word: "fluctuate", meaning: "to change often between levels", example: "Prices fluctuate throughout the year.", pic: "📊", pos: "v", ipa: "/ˈflʌktʃueɪt/", cat: "Economy" },
  { word: "formulate", meaning: "to create an idea or plan carefully", example: "The team formulated a new strategy.", pic: "📝", pos: "v", ipa: "/ˈfɔːmjuleɪt/", cat: "Work" },
  { word: "foster (c1)", meaning: "to encourage a feeling or skill to develop", example: "Reading fosters imagination.", pic: "🌱", pos: "v", ipa: "/ˈfɒstə/", cat: "Goals" },
  { word: "fundamental", meaning: "forming the base of something; very important", example: "Trust is fundamental to friendship.", pic: "🏗️", pos: "adj", ipa: "/ˌfʌndəˈmentl/", cat: "Talk" },
  { word: "generate (c1)", meaning: "to produce or create something", example: "The plant generates clean energy.", pic: "⚡", pos: "v", ipa: "/ˈdʒenəreɪt/", cat: "Environment" },
  { word: "hinder", meaning: "to make it difficult for something to happen", example: "Bad weather hindered the rescue.", pic: "⛔", pos: "v", ipa: "/ˈhɪndə/", cat: "Goals" },
  { word: "identical", meaning: "exactly the same", example: "The twins look identical.", pic: "👯", pos: "adj", ipa: "/aɪˈdentɪkl/", cat: "People" },
  { word: "immense", meaning: "extremely large or great", example: "The project required immense effort.", pic: "🌌", pos: "adj", ipa: "/ɪˈmens/", cat: "Goals" },
  { word: "implement (c1)", meaning: "to put a plan into action", example: "The school will implement the new rules.", pic: "⚙️", pos: "v", ipa: "/ˈɪmplɪment/", cat: "Work" },
  { word: "imply", meaning: "to suggest without saying directly", example: "His silence implied agreement.", pic: "🤫", pos: "v", ipa: "/ɪmˈplaɪ/", cat: "Talk" },
  { word: "incentive", meaning: "something that encourages you to do something", example: "Bonuses are a strong incentive to work hard.", pic: "🏆", pos: "n", ipa: "/ɪnˈsentɪv/", cat: "Work" },
  { word: "incidence", meaning: "how often something happens", example: "There is a high incidence of flu in winter.", pic: "📈", pos: "n", ipa: "/ˈɪnsɪdəns/", cat: "Health" },
  { word: "incorporate", meaning: "to include something as part of a whole", example: "The design incorporates local art.", pic: "🧩", pos: "v", ipa: "/ɪnˈkɔːpəreɪt/", cat: "Culture" },
  { word: "indifferent", meaning: "not interested or caring", example: "He was indifferent to the criticism.", pic: "😐", pos: "adj", ipa: "/ɪnˈdɪfrənt/", cat: "Emotions" },
  { word: "indispensable", meaning: "completely necessary", example: "The internet is indispensable today.", pic: "🔑", pos: "adj", ipa: "/ˌɪndɪˈspensəbl/", cat: "Tech" },
  { word: "inevitable (c1)", meaning: "certain to happen", example: "Change is inevitable in life.", pic: "⏳", pos: "adj", ipa: "/ɪnˈevɪtəbl/", cat: "Talk" },
  { word: "initiative", meaning: "the ability to act without being told", example: "She showed great initiative at work.", pic: "🚀", pos: "n", ipa: "/ɪˈnɪʃətɪv/", cat: "Work" },
  { word: "integrate", meaning: "to combine into one whole", example: "The app integrates maps and photos.", pic: "🔗", pos: "v", ipa: "/ˈɪntɪɡreɪt/", cat: "Tech" },
  { word: "intervene", meaning: "to become involved to change a situation", example: "The teacher intervened in the fight.", pic: "🛑", pos: "v", ipa: "/ˌɪntəˈviːn/", cat: "People" },
  { word: "intuitive", meaning: "understood by feeling, without thinking", example: "The controls are intuitive to use.", pic: "💡", pos: "adj", ipa: "/ɪnˈtjuːɪtɪv/", cat: "Tech" },
  { word: "invariably", meaning: "always; in every case", example: "He is invariably late on Mondays.", pic: "🔁", pos: "adv", ipa: "/ɪnˈveəriəbli/", cat: "Routine" },
  { word: "justify (c1)", meaning: "to give a good reason for something", example: "How can you justify that decision?", pic: "⚖️", pos: "v", ipa: "/ˈdʒʌstɪfaɪ/", cat: "Talk" },
  { word: "legitimate", meaning: "legal and reasonable", example: "She has a legitimate reason for being late.", pic: "✅", pos: "adj", ipa: "/lɪˈdʒɪtɪmət/", cat: "Culture" },
  { word: "manipulate", meaning: "to control someone unfairly for your own benefit", example: "He manipulated the situation to win.", pic: "🎭", pos: "v", ipa: "/məˈnɪpjuleɪt/", cat: "Talk" },
  { word: "marginal", meaning: "small and not very important", example: "There was a marginal difference in scores.", pic: "📉", pos: "adj", ipa: "/ˈmɑːdʒɪnl/", cat: "Science" },
  { word: "mitigate", meaning: "to make something less harmful", example: "Trees mitigate the effects of pollution.", pic: "🌳", pos: "v", ipa: "/ˈmɪtɪɡeɪt/", cat: "Environment" },
  { word: "notion (c1)", meaning: "an idea or belief", example: "The notion of time travel fascinates me.", pic: "💭", pos: "n", ipa: "/ˈnəʊʃn/", cat: "Science" },
  { word: "objective", meaning: "based on facts, not feelings", example: "The report must be objective.", pic: "🎯", pos: "adj", ipa: "/əbˈdʒektɪv/", cat: "Science" },
  { word: "obsolete", meaning: "no longer used", example: "These machines are now obsolete.", pic: "🕰️", pos: "adj", ipa: "/ˈɒbsəliːt/", cat: "Tech" },
  { word: "persist", meaning: "to continue doing something despite difficulty", example: "If you persist, you will succeed.", pic: "💪", pos: "v", ipa: "/pəˈsɪst/", cat: "Goals" },
  { word: "profound", meaning: "very deep or strong", example: "The book had a profound effect on me.", pic: "🌊", pos: "adj", ipa: "/prəˈfaʊnd/", cat: "Emotions" },
  { word: "radical", meaning: "very new and different from the usual", example: "The company made radical changes.", pic: "💥", pos: "adj", ipa: "/ˈrædɪkl/", cat: "Work" },
  { word: "reinforce", meaning: "to make an idea or structure stronger", example: "Practice reinforces learning.", pic: "🏗️", pos: "v", ipa: "/ˌriːɪnˈfɔːs/", cat: "School" },
  { word: "restrain", meaning: "to stop someone or something from doing something", example: "She restrained her anger.", pic: "🤐", pos: "v", ipa: "/rɪˈstreɪn/", cat: "Emotions" },
  { word: "retain", meaning: "to keep something", example: "The wall retains the heat of the sun.", pic: "🧲", pos: "v", ipa: "/rɪˈteɪn/", cat: "Science" },
  { word: "rigorous", meaning: "done with great care and thoroughness", example: "The drug passed rigorous tests.", pic: "🔬", pos: "adj", ipa: "/ˈrɪɡərəs/", cat: "Science" },
  { word: "stimulate", meaning: "to encourage activity or development", example: "Music stimulates creativity.", pic: "✨", pos: "v", ipa: "/ˈstɪmjuleɪt/", cat: "Culture" },
  { word: "subsequent", meaning: "happening after something else", example: "Subsequent tests confirmed the result.", pic: "⏭️", pos: "adj", ipa: "/ˈsʌbsɪkwənt/", cat: "Science" },
  { word: "supplement", meaning: "to add something extra", example: "She supplements her income with tutoring.", pic: "➕", pos: "v", ipa: "/ˈsʌplɪment/", cat: "Work" },
  { word: "tangible", meaning: "real and able to be seen or touched", example: "The project produced tangible results.", pic: "✋", pos: "adj", ipa: "/ˈtændʒəbl/", cat: "Goals" },
  { word: "transparent", meaning: "clear and open; easy to see through", example: "The process must be transparent to voters.", pic: "🔍", pos: "adj", ipa: "/trænsˈpærənt/", cat: "Culture" },
  { word: "underlying", meaning: "the real cause hidden beneath something", example: "Stress is the underlying cause of her illness.", pic: "🧩", pos: "adj", ipa: "/ˌʌndəˈlaɪɪŋ/", cat: "Health" },
  { word: "undermine", meaning: "to make something weaker over time", example: "Rumours undermined her confidence.", pic: "🕳️", pos: "v", ipa: "/ˌʌndəˈmaɪn/", cat: "Talk" },
  { word: "undertake", meaning: "to accept a task and begin it", example: "They undertook a difficult project.", pic: "🎒", pos: "v", ipa: "/ˌʌndəˈteɪk/", cat: "Work" },
  { word: "utilise", meaning: "to use something in an effective way", example: "We must utilise our resources wisely.", pic: "🛠️", pos: "v", ipa: "/ˈjuːtəlaɪz/", cat: "Work" },
  { word: "verify", meaning: "to check that something is true", example: "Please verify the facts before publishing.", pic: "🔎", pos: "v", ipa: "/ˈverɪfaɪ/", cat: "Science" },
  { word: "viable", meaning: "possible to succeed or work", example: "The idea is not economically viable.", pic: "🌱", pos: "adj", ipa: "/ˈvaɪəbl/", cat: "Goals" }
];
window.LF_VOCAB_EXTRA["C2"] = [
  { word: "aberration", meaning: "an unusual and temporary departure from the norm", example: "The storm was an aberration in a mild season.", pic: "🌪️", pos: "n", ipa: "/ˌæbəˈreɪʃn/", cat: "Science" },
  { word: "abhor", meaning: "to hate something intensely", example: "She abhors any form of cruelty.", pic: "😤", pos: "v", ipa: "/əbˈhɔː/", cat: "Emotions" },
  { word: "abject", meaning: "extremely bad or hopeless", example: "They lived in abject poverty.", pic: "💔", pos: "adj", ipa: "/ˈæbdʒekt/", cat: "People" },
  { word: "abnegate", meaning: "to give up or deny yourself something", example: "He abnegated his own comfort for the family.", pic: "🙏", pos: "v", ipa: "/ˈæbnɪɡeɪt/", cat: "Goals" },
  { word: "abstruse", meaning: "difficult to understand", example: "The theory is too abstruse for beginners.", pic: "🧠", pos: "adj", ipa: "/əbˈstruːs/", cat: "Science" },
  { word: "acquiesce", meaning: "to accept something unwillingly", example: "She acquiesced to the committee's decision.", pic: "🤐", pos: "v", ipa: "/ˌækwiˈes/", cat: "Talk" },
  { word: "acrimonious", meaning: "angry and bitter", example: "The divorce was long and acrimonious.", pic: "🔥", pos: "adj", ipa: "/ˌækrɪˈməʊniəs/", cat: "Emotions" },
  { word: "admonish", meaning: "to warn or scold someone firmly", example: "The coach admonished the players for lateness.", pic: "🗣️", pos: "v", ipa: "/ədˈmɒnɪʃ/", cat: "Talk" },
  { word: "adroit", meaning: "skilful and quick in thinking or movement", example: "She is adroit at negotiating.", pic: "🎯", pos: "adj", ipa: "/əˈdrɔɪt/", cat: "Work" },
  { word: "aesthetic", meaning: "relating to beauty and art", example: "The building has great aesthetic appeal.", pic: "🎨", pos: "adj", ipa: "/iːsˈθetɪk/", cat: "Culture" },
  { word: "alacrity", meaning: "eager and quick willingness", example: "He accepted the invitation with alacrity.", pic: "🏃", pos: "n", ipa: "/əˈlækrəti/", cat: "Emotions" },
  { word: "anomaly", meaning: "something unusual that differs from the expected", example: "The test showed an anomaly in the data.", pic: "❓", pos: "n", ipa: "/əˈnɒməli/", cat: "Science" },
  { word: "antithesis", meaning: "the exact opposite of something", example: "Greed is the antithesis of generosity.", pic: "⚖️", pos: "n", ipa: "/ænˈtɪθəsɪs/", cat: "Talk" },
  { word: "apocryphal", meaning: "widely told but probably untrue", example: "That story about the founder is apocryphal.", pic: "📖", pos: "adj", ipa: "/əˈpɒkrɪfl/", cat: "Culture" },
  { word: "apropos", meaning: "relevant to what is being discussed", example: "Apropos of nothing, I saw your brother.", pic: "🎯", pos: "adv", ipa: "/ˌæprəˈpəʊ/", cat: "Talk" },
  { word: "arcane", meaning: "known or understood by only a few", example: "He studies arcane medieval symbols.", pic: "🔮", pos: "adj", ipa: "/ɑːˈkeɪn/", cat: "Culture" },
  { word: "assiduous", meaning: "working carefully and with great effort", example: "She was assiduous in her research.", pic: "📚", pos: "adj", ipa: "/əˈsɪdjuəs/", cat: "Work" },
  { word: "augment", meaning: "to make something larger or greater", example: "They augmented the staff during summer.", pic: "📈", pos: "v", ipa: "/ɔːɡˈment/", cat: "Work" },
  { word: "austere", meaning: "simple, severe and without luxury", example: "The monks live an austere life.", pic: "🏜️", pos: "adj", ipa: "/ɒˈstɪə/", cat: "Culture" },
  { word: "banal", meaning: "boring and ordinary", example: "The film was full of banal dialogue.", pic: "😴", pos: "adj", ipa: "/bəˈnɑːl/", cat: "Culture" },
  { word: "bellicose", meaning: "eager to fight or argue", example: "The bellicose nation threatened war.", pic: "⚔️", pos: "adj", ipa: "/ˈbelɪkəʊs/", cat: "Culture" },
  { word: "benign", meaning: "kind or harmless", example: "The doctor said the growth was benign.", pic: "🕊️", pos: "adj", ipa: "/bɪˈnaɪn/", cat: "Health" },
  { word: "bereft", meaning: "deprived of or lacking something", example: "She felt bereft of hope.", pic: "🥀", pos: "adj", ipa: "/bɪˈreft/", cat: "Emotions" },
  { word: "blatant", meaning: "done openly and unashamedly", example: "That was a blatant lie.", pic: "🙈", pos: "adj", ipa: "/ˈbleɪtnt/", cat: "Talk" },
  { word: "bombastic", meaning: "using long words to sound impressive", example: "His bombastic speech bored everyone.", pic: "🗣️", pos: "adj", ipa: "/bɒmˈbæstɪk/", cat: "Talk" },
  { word: "capricious", meaning: "changing mood or behaviour suddenly", example: "The weather here is capricious.", pic: "🌦️", pos: "adj", ipa: "/kəˈprɪʃəs/", cat: "Nature" },
  { word: "catharsis", meaning: "the release of strong emotions through art or activity", example: "Writing the novel was a catharsis for her.", pic: "🌊", pos: "n", ipa: "/kəˈθɑːsɪs/", cat: "Culture" },
  { word: "cerebral", meaning: "involving the mind or intellect", example: "The novel is more cerebral than emotional.", pic: "🧠", pos: "adj", ipa: "/ˈserəbrəl/", cat: "Science" },
  { word: "chicanery", meaning: "trickery used to deceive people", example: "He won the contract through chicanery.", pic: "🎭", pos: "n", ipa: "/ʃɪˈkeɪnəri/", cat: "Work" },
  { word: "circumspect", meaning: "careful and unwilling to take risks", example: "Be circumspect before signing anything.", pic: "🕵️", pos: "adj", ipa: "/ˈsɜːkəmspekt/", cat: "Talk" },
  { word: "clandestine", meaning: "secret and hidden", example: "They held clandestine meetings at night.", pic: "🌙", pos: "adj", ipa: "/klænˈdestɪn/", cat: "Culture" },
  { word: "cogent (c2)", meaning: "clear, logical and convincing", example: "She presented a cogent argument.", pic: "🧩", pos: "adj", ipa: "/ˈkəʊdʒənt/", cat: "Talk" },
  { word: "complacent", meaning: "too satisfied with yourself to notice problems", example: "The team grew complacent after winning.", pic: "😌", pos: "adj", ipa: "/kəmˈpleɪsnt/", cat: "Goals" },
  { word: "confluence", meaning: "a situation where two things come together", example: "The confluence of ideas produced a new theory.", pic: "🌊", pos: "n", ipa: "/ˈkɒnfluəns/", cat: "Science" },
  { word: "conjecture", meaning: "a guess based on incomplete information", example: "The claim is pure conjecture.", pic: "🤔", pos: "n", ipa: "/kənˈdʒektʃə/", cat: "Science" },
  { word: "conundrum", meaning: "a confusing and difficult problem", example: "How to fund the project is a conundrum.", pic: "🧩", pos: "n", ipa: "/kəˈnʌndrəm/", cat: "Goals" },
  { word: "corroborate", meaning: "to support a statement with evidence", example: "The witness corroborated her story.", pic: "📜", pos: "v", ipa: "/kəˈrɒbəreɪt/", cat: "Science" },
  { word: "credulous", meaning: "too ready to believe things", example: "The scam targeted credulous buyers.", pic: "🐟", pos: "adj", ipa: "/ˈkredjələs/", cat: "People" },
  { word: "debacle", meaning: "a complete and sudden failure", example: "The launch was a public relations debacle.", pic: "💥", pos: "n", ipa: "/deɪˈbɑːkl/", cat: "Work" },
  { word: "demagogue", meaning: "a leader who gains power by appealing to emotions", example: "The demagogue stirred the crowd with fear.", pic: "🎙️", pos: "n", ipa: "/ˈdeməɡɒɡ/", cat: "Culture" },
  { word: "denigrate", meaning: "to criticise unfairly and damage reputation", example: "Do not denigrate your colleagues.", pic: "👇", pos: "v", ipa: "/ˈdenɪɡreɪt/", cat: "Talk" },
  { word: "despondent", meaning: "very sad and without hope", example: "He felt despondent after the rejection.", pic: "😞", pos: "adj", ipa: "/dɪˈspɒndənt/", cat: "Emotions" },
  { word: "diatribe", meaning: "a long angry speech criticising someone", example: "The review was a vicious diatribe.", pic: "🗯️", pos: "n", ipa: "/ˈdaɪətraɪb/", cat: "Talk" },
  { word: "didactic", meaning: "intended to teach, often in a moralising way", example: "The didactic tone of the book puts readers off.", pic: "📖", pos: "adj", ipa: "/daɪˈdæktɪk/", cat: "Culture" },
  { word: "diffident", meaning: "shy and lacking self-confidence", example: "She was diffident about speaking publicly.", pic: "🙈", pos: "adj", ipa: "/ˈdɪfɪdənt/", cat: "Emotions" },
  { word: "disparage", meaning: "to speak about someone in a disrespectful way", example: "He disparaged his rival's work.", pic: "👇", pos: "v", ipa: "/dɪˈspærɪdʒ/", cat: "Talk" },
  { word: "disseminate", meaning: "to spread information widely", example: "The university disseminates research findings.", pic: "📡", pos: "v", ipa: "/dɪˈsemɪneɪt/", cat: "Science" },
  { word: "ebullient", meaning: "full of energy and enthusiasm", example: "Her ebullient personality lights up the room.", pic: "🎉", pos: "adj", ipa: "/ɪˈbʌliənt/", cat: "Emotions" },
  { word: "echelon", meaning: "a level of rank or power", example: "He reached the highest echelons of power.", pic: "⛰️", pos: "n", ipa: "/ˈeʃəlɒn/", cat: "Work" },
  { word: "eclectic", meaning: "chosen from many different sources", example: "Her taste in music is eclectic.", pic: "🎶", pos: "adj", ipa: "/ɪˈklektɪk/", cat: "Culture" },
  { word: "efficacy", meaning: "the ability to produce the desired result", example: "Scientists tested the efficacy of the drug.", pic: "🎯", pos: "n", ipa: "/ˈefɪkəsi/", cat: "Science" },
  { word: "effrontery", meaning: "shameless rude boldness", example: "He had the effrontery to ask for more money.", pic: "😏", pos: "n", ipa: "/ɪˈfrʌntəri/", cat: "Talk" },
  { word: "egregious", meaning: "outstandingly bad", example: "The error was egregious and costly.", pic: "🚨", pos: "adj", ipa: "/ɪˈɡriːdʒəs/", cat: "Work" },
  { word: "elucidate", meaning: "to make something clear and easy to understand", example: "Could you elucidate your theory?", pic: "💡", pos: "v", ipa: "/iˈluːsɪdeɪt/", cat: "Talk" },
  { word: "emulate", meaning: "to try to equal someone by copying them", example: "Young players emulate their heroes.", pic: "🪞", pos: "v", ipa: "/ˈemjuleɪt/", cat: "Goals" },
  { word: "enigma", meaning: "a person or thing that is mysterious and hard to understand", example: "The ancient script remains an enigma.", pic: "❓", pos: "n", ipa: "/ɪˈnɪɡmə/", cat: "Science" },
  { word: "ephemeral", meaning: "lasting for a very short time", example: "Fame is often ephemeral.", pic: "🦋", pos: "adj", ipa: "/ɪˈfemərəl/", cat: "Culture" },
  { word: "epitome", meaning: "the perfect example of a quality", example: "She is the epitome of grace.", pic: "👑", pos: "n", ipa: "/ɪˈpɪtəmi/", cat: "People" },
  { word: "equanimity", meaning: "calmness of mind in difficult situations", example: "She faced the crisis with equanimity.", pic: "🧘", pos: "n", ipa: "/ˌekwəˈnɪməti/", cat: "Emotions" },
  { word: "erudite", meaning: "having great knowledge from study", example: "The erudite professor quoted many sources.", pic: "📚", pos: "adj", ipa: "/ˈerudaɪt/", cat: "School" },
  { word: "esoteric", meaning: "understood by only a small group of people", example: "The lecture covered esoteric philosophy.", pic: "🔮", pos: "adj", ipa: "/ˌesəˈterɪk/", cat: "Culture" },
  { word: "exacerbate", meaning: "to make a problem worse", example: "The noise exacerbated her headache.", pic: "🔥", pos: "v", ipa: "/ɪɡˈzæsəbeɪt/", cat: "Health" },
  { word: "exemplary", meaning: "perfect as an example to copy", example: "Her conduct was exemplary.", pic: "⭐", pos: "adj", ipa: "/ɪɡˈzempləri/", cat: "Goals" },
  { word: "expedite", meaning: "to make a process happen faster", example: "The clerk expedited my application.", pic: "⚡", pos: "v", ipa: "/ˈekspədaɪt/", cat: "Work" },
  { word: "facile", meaning: "too simple and therefore not convincing", example: "The answer was a facile generalisation.", pic: "🙄", pos: "adj", ipa: "/ˈfæsaɪl/", cat: "Talk" },
  { word: "fatuous", meaning: "silly and pointless", example: "He made a fatuous comment in the meeting.", pic: "🙃", pos: "adj", ipa: "/ˈfætʃuəs/", cat: "Talk" },
  { word: "fastidious", meaning: "very careful about small details", example: "She is fastidious about cleanliness.", pic: "🧹", pos: "adj", ipa: "/fæˈstɪdiəs/", cat: "Home" },
  { word: "fortuitous", meaning: "happening by chance in a lucky way", example: "The meeting was a fortuitous accident.", pic: "🍀", pos: "adj", ipa: "/fɔːˈtjuːɪtəs/", cat: "Goals" },
  { word: "garrulous", meaning: "talking a lot, especially about unimportant things", example: "The garrulous taxi driver never stopped.", pic: "🗣️", pos: "adj", ipa: "/ˈɡærələs/", cat: "Talk" },
  { word: "gregarious", meaning: "enjoying being with other people", example: "She is gregarious and loves parties.", pic: "🎉", pos: "adj", ipa: "/ɡrɪˈɡeəriəs/", cat: "People" },
  { word: "hackneyed", meaning: "used too often; unoriginal", example: "The speech was full of hackneyed phrases.", pic: "🪫", pos: "adj", ipa: "/ˈhæknid/", cat: "Talk" },
  { word: "hapless", meaning: "unlucky and helpless", example: "The hapless tourist lost his passport.", pic: "😩", pos: "adj", ipa: "/ˈhæpləs/", cat: "Travel" },
  { word: "hegemony", meaning: "dominance of one group over others", example: "The empire maintained hegemony over the region.", pic: "👑", pos: "n", ipa: "/hɪˈdʒeməni/", cat: "Culture" },
  { word: "hierarchical", meaning: "organised in levels of importance", example: "The company has a hierarchical structure.", pic: "🔺", pos: "adj", ipa: "/ˌhaɪəˈrɑːkɪkl/", cat: "Work" },
  { word: "hubris", meaning: "extreme pride that leads to failure", example: "His hubris cost him the election.", pic: "🦚", pos: "n", ipa: "/ˈhjuːbrɪs/", cat: "Goals" },
  { word: "idiosyncrasy", meaning: "an unusual habit or way of behaving", example: "Wearing odd socks is one of his idiosyncrasies.", pic: "🧦", pos: "n", ipa: "/ˌɪdiəˈsɪŋkrəsi/", cat: "People" },
  { word: "impetuous", meaning: "acting suddenly without thinking", example: "His impetuous decision caused problems.", pic: "🎢", pos: "adj", ipa: "/ɪmˈpetʃuəs/", cat: "Emotions" },
  { word: "inadvertently", meaning: "by accident; without meaning to", example: "She inadvertently revealed the surprise.", pic: "😅", pos: "adv", ipa: "/ˌɪnədˈvɜːtəntli/", cat: "Talk" },
  { word: "incumbent", meaning: "the current holder of an official position", example: "The incumbent won the election again.", pic: "👔", pos: "n", ipa: "/ɪnˈkʌmbənt/", cat: "Culture" },
  { word: "indefatigable", meaning: "never getting tired", example: "Her indefatigable energy amazed everyone.", pic: "🔋", pos: "adj", ipa: "/ˌɪndɪˈfætɪɡəbl/", cat: "Work" },
  { word: "indolent", meaning: "lazy and avoiding work", example: "The indolent student never finished tasks.", pic: "🦥", pos: "adj", ipa: "/ˈɪndələnt/", cat: "Work" },
  { word: "ineffable", meaning: "too great to be described in words", example: "The view filled her with ineffable joy.", pic: "🌌", pos: "adj", ipa: "/ɪnˈefəbl/", cat: "Emotions" },
  { word: "ingenuous", meaning: "honest and innocent; unable to deceive", example: "Her ingenuous question surprised the panel.", pic: "😇", pos: "adj", ipa: "/ɪnˈdʒenjuəs/", cat: "People" },
  { word: "innocuous", meaning: "harmless and not likely to offend", example: "The remark seemed innocuous but hurt her.", pic: "🕊️", pos: "adj", ipa: "/ɪˈnɒkjuəs/", cat: "Talk" },
  { word: "intransigent", meaning: "refusing to change your position", example: "Both sides remained intransigent.", pic: "🧱", pos: "adj", ipa: "/ɪnˈtrænsɪdʒənt/", cat: "Talk" },
  { word: "inundate", meaning: "to overwhelm with too much of something", example: "The office was inundated with emails.", pic: "🌊", pos: "v", ipa: "/ˈɪnʌndeɪt/", cat: "Work" },
  { word: "irascible", meaning: "becoming angry very easily", example: "The irascible chef shouted at the staff.", pic: "😡", pos: "adj", ipa: "/ɪˈræsəbl/", cat: "Emotions" },
  { word: "labyrinthine", meaning: "extremely complicated and confusing", example: "The city's streets are labyrinthine.", pic: "🌀", pos: "adj", ipa: "/ˌlæbəˈrɪnθaɪn/", cat: "Travel" },
  { word: "laconic", meaning: "using very few words", example: "His laconic replies annoyed the interviewer.", pic: "🤐", pos: "adj", ipa: "/ləˈkɒnɪk/", cat: "Talk" },
  { word: "languid", meaning: "slow and relaxed; lacking energy", example: "They spent a languid afternoon by the pool.", pic: "😴", pos: "adj", ipa: "/ˈlæŋɡwɪd/", cat: "Leisure" },
  { word: "laudable", meaning: "deserving praise", example: "Her laudable efforts saved the project.", pic: "🏅", pos: "adj", ipa: "/ˈlɔːdəbl/", cat: "Goals" },
  { word: "loquacious", meaning: "very talkative", example: "The loquacious host filled every silence.", pic: "💬", pos: "adj", ipa: "/ləˈkweɪʃəs/", cat: "Talk" },
  { word: "lugubrious", meaning: "sad and gloomy", example: "The lugubrious music matched the scene.", pic: "🎻", pos: "adj", ipa: "/ləˈɡuːbriəs/", cat: "Culture" },
  { word: "magnanimous", meaning: "generous and forgiving", example: "He was magnanimous in victory.", pic: "🕊️", pos: "adj", ipa: "/mæɡˈnænɪməs/", cat: "People" },
  { word: "maverick", meaning: "an independent person who does not follow rules", example: "The maverick director ignored studio advice.", pic: "🐺", pos: "n", ipa: "/ˈmævərɪk/", cat: "Work" },
  { word: "mendacious", meaning: "not telling the truth", example: "The mendacious claims were exposed.", pic: "🤥", pos: "adj", ipa: "/menˈdeɪʃəs/", cat: "Talk" },
  { word: "mercurial", meaning: "changing mood suddenly", example: "His mercurial temperament is hard to predict.", pic: "🌪️", pos: "adj", ipa: "/mɜːˈkjʊəriəl/", cat: "Emotions" },
  { word: "meticulous", meaning: "extremely careful about details", example: "She keeps meticulous records.", pic: "🔍", pos: "adj", ipa: "/məˈtɪkjələs/", cat: "Work" },
  { word: "mollify", meaning: "to make someone less angry", example: "He mollified the client with an apology.", pic: "🕊️", pos: "v", ipa: "/ˈmɒlɪfaɪ/", cat: "Talk" },
  { word: "munificent", meaning: "very generous", example: "The munificent donor gave a million.", pic: "💝", pos: "adj", ipa: "/mjuːˈnɪfɪsnt/", cat: "People" },
  { word: "nefarious", meaning: "evil and criminal", example: "The plan was nefarious in intent.", pic: "😈", pos: "adj", ipa: "/nɪˈfeəriəs/", cat: "Culture" },
  { word: "nebulous", meaning: "unclear and without shape or limits", example: "The proposal is still nebulous.", pic: "🌫️", pos: "adj", ipa: "/ˈnebjələs/", cat: "Talk" },
  { word: "nonchalant", meaning: "calmly casual and unconcerned", example: "He was nonchalant about the exam.", pic: "😎", pos: "adj", ipa: "/ˈnɒnʃələnt/", cat: "Emotions" },
  { word: "obfuscate", meaning: "to make something unclear on purpose", example: "The company obfuscated the true costs.", pic: "🌫️", pos: "v", ipa: "/ˈɒbfʌskeɪt/", cat: "Talk" },
  { word: "obsequious", meaning: "too eager to please powerful people", example: "The obsequious waiter never stopped bowing.", pic: "🙇", pos: "adj", ipa: "/əbˈsiːkwiəs/", cat: "People" },
  { word: "obstinate", meaning: "stubbornly refusing to change", example: "He was obstinate about the plan.", pic: "🦏", pos: "adj", ipa: "/ˈɒbstɪnət/", cat: "Emotions" },
  { word: "onerous", meaning: "difficult and unpleasant to deal with", example: "The new duties proved onerous.", pic: "⛰️", pos: "adj", ipa: "/ˈɒnərəs/", cat: "Work" },
  { word: "opulent", meaning: "rich, luxurious and grand", example: "The palace is staggeringly opulent.", pic: "💎", pos: "adj", ipa: "/ˈɒpjələnt/", cat: "Culture" },
  { word: "paradigm (c2)", meaning: "a typical model or pattern of something", example: "The discovery changed the scientific paradigm.", pic: "🧬", pos: "n", ipa: "/ˈpærədaɪm/", cat: "Science" },
  { word: "parsimonious", meaning: "unwilling to spend money", example: "The parsimonious landlord refused repairs.", pic: "🪙", pos: "adj", ipa: "/ˌpɑːsɪˈməʊniəs/", cat: "Shopping" },
  { word: "paucity", meaning: "a lack of something", example: "There is a paucity of research on this topic.", pic: "🕳️", pos: "n", ipa: "/ˈpɔːsəti/", cat: "Science" },
  { word: "pedantic", meaning: "too concerned with small details of rules", example: "His pedantic corrections annoyed everyone.", pic: "📏", pos: "adj", ipa: "/pɪˈdæntɪk/", cat: "School" },
  { word: "penchant", meaning: "a strong liking for something", example: "She has a penchant for spicy food.", pic: "🌶️", pos: "n", ipa: "/ˈpɒ̃ʃɒ̃/", cat: "Food" },
  { word: "perfunctory", meaning: "done quickly without care or interest", example: "He gave a perfunctory glance at the report.", pic: "🙄", pos: "adj", ipa: "/pəˈfʌŋktəri/", cat: "Work" },
  { word: "pernicious", meaning: "having a very harmful effect over time", example: "The rumour had a pernicious influence.", pic: "☠️", pos: "adj", ipa: "/pəˈnɪʃəs/", cat: "Talk" },
  { word: "pertinent", meaning: "directly relevant to the matter", example: "Please raise only pertinent questions.", pic: "🎯", pos: "adj", ipa: "/ˈpɜːtɪnənt/", cat: "Talk" },
  { word: "phlegmatic", meaning: "calm and not easily excited", example: "His phlegmatic nature calms the team.", pic: "🧘", pos: "adj", ipa: "/fleɡˈmætɪk/", cat: "Emotions" },
  { word: "pious", meaning: "very religious; falsely sincere", example: "Her pious words hid a selfish heart.", pic: "⛪", pos: "adj", ipa: "/ˈpaɪəs/", cat: "Culture" },
  { word: "platitude", meaning: "a boring statement repeated too often", example: "The speech was full of platitudes.", pic: "😴", pos: "n", ipa: "/ˈplætɪtjuːd/", cat: "Talk" },
  { word: "plethora", meaning: "a large amount of something", example: "There is a plethora of apps to choose from.", pic: "🌊", pos: "n", ipa: "/ˈpleθərə/", cat: "Tech" },
  { word: "pragmatic", meaning: "dealing with problems practically", example: "We need a pragmatic solution.", pic: "🛠️", pos: "adj", ipa: "/præɡˈmætɪk/", cat: "Work" },
  { word: "precarious", meaning: "dangerously likely to fail or fall", example: "The climber hung in a precarious position.", pic: "🧗", pos: "adj", ipa: "/prɪˈkeəriəs/", cat: "Goals" },
  { word: "precipitate", meaning: "to cause something to happen suddenly", example: "The scandal precipitated his resignation.", pic: "⏩", pos: "v", ipa: "/prɪˈsɪpɪteɪt/", cat: "Work" },
  { word: "precocious", meaning: "showing ability at an unusually young age", example: "The precocious child read at three.", pic: "🧒", pos: "adj", ipa: "/prɪˈkəʊʃəs/", cat: "School" },
  { word: "presumptuous", meaning: "too confident in a rude way", example: "It was presumptuous of him to decide for us.", pic: "🙄", pos: "adj", ipa: "/prɪˈzʌmptʃuəs/", cat: "People" },
  { word: "proclivity", meaning: "a natural tendency to do something", example: "He has a proclivity for exaggeration.", pic: "🎯", pos: "n", ipa: "/prəˈklɪvəti/", cat: "People" },
  { word: "profligate", meaning: "wastefully spending money", example: "His profligate lifestyle ended in debt.", pic: "💸", pos: "adj", ipa: "/ˈprɒflɪɡət/", cat: "Shopping" },
  { word: "proliferate", meaning: "to increase rapidly in number", example: "Smartphones proliferated across the globe.", pic: "🦠", pos: "v", ipa: "/prəˈlɪfəreɪt/", cat: "Tech" },
  { word: "propensity", meaning: "a natural tendency to behave a certain way", example: "She has a propensity to worry.", pic: "🌀", pos: "n", ipa: "/prəˈpensəti/", cat: "People" },
  { word: "puerile", meaning: "silly and childish", example: "He was fired for puerile behaviour.", pic: "🧒", pos: "adj", ipa: "/ˈpjʊəraɪl/", cat: "People" },
  { word: "pugnacious", meaning: "eager to fight or argue", example: "The pugnacious player got a red card.", pic: "🥊", pos: "adj", ipa: "/pʌɡˈneɪʃəs/", cat: "Emotions" },
  { word: "quintessential", meaning: "the most perfect example of a quality", example: "She is the quintessential teacher.", pic: "💎", pos: "adj", ipa: "/ˌkwɪntɪˈsenʃl/", cat: "People" },
  { word: "rancorous", meaning: "full of bitterness and hate", example: "The rancorous debate ended badly.", pic: "😤", pos: "adj", ipa: "/ˈræŋkərəs/", cat: "Talk" },
  { word: "recalcitrant", meaning: "refusing to obey rules", example: "The recalcitrant pupil was sent out.", pic: "🦏", pos: "adj", ipa: "/rɪˈkælsɪtrənt/", cat: "School" },
  { word: "recondite", meaning: "obscure and hard to understand", example: "The article is full of recondite terms.", pic: "🔬", pos: "adj", ipa: "/ˈrekəndaɪt/", cat: "Science" },
  { word: "refulgent", meaning: "shining brightly", example: "The refulgent morning light flooded the room.", pic: "☀️", pos: "adj", ipa: "/rɪˈfʌldʒənt/", cat: "Nature" },
  { word: "reprehensible", meaning: "very bad and deserving blame", example: "His behaviour was utterly reprehensible.", pic: "🚫", pos: "adj", ipa: "/ˌreprɪˈhensəbl/", cat: "Culture" },
  { word: "repudiate", meaning: "to refuse to accept or believe something", example: "She repudiated the accusations.", pic: "🙅", pos: "v", ipa: "/rɪˈpjuːdieɪt/", cat: "Talk" },
  { word: "resplendent", meaning: "very bright and impressive", example: "The bride looked resplendent in gold.", pic: "✨", pos: "adj", ipa: "/rɪˈsplendənt/", cat: "Culture" },
  { word: "salient", meaning: "most noticeable and important", example: "The salient point of the talk was simple.", pic: "📍", pos: "adj", ipa: "/ˈseɪliənt/", cat: "Talk" },
  { word: "sanguine", meaning: "cheerful and confident about the future", example: "She remains sanguine about the outcome.", pic: "😊", pos: "adj", ipa: "/ˈsæŋɡwɪn/", cat: "Emotions" },
  { word: "sardonic", meaning: "humorous in a mocking way", example: "His sardonic wit silenced the room.", pic: "😏", pos: "adj", ipa: "/sɑːˈdɒnɪk/", cat: "Talk" },
  { word: "satiate", meaning: "to satisfy a desire completely", example: "The feast satiated their hunger.", pic: "😋", pos: "v", ipa: "/ˈseɪʃieɪt/", cat: "Food" },
  { word: "serendipity", meaning: "finding something good without looking for it", example: "The discovery was pure serendipity.", pic: "🍀", pos: "n", ipa: "/ˌserənˈdɪpəti/", cat: "Science" },
  { word: "soporific", meaning: "making you feel sleepy", example: "The lecture was completely soporific.", pic: "😴", pos: "adj", ipa: "/ˌsɒpəˈrɪfɪk/", cat: "Culture" },
  { word: "specious", meaning: "seeming true but actually wrong", example: "His specious argument fooled no one.", pic: "🎭", pos: "adj", ipa: "/ˈspiːʃəs/", cat: "Talk" },
  { word: "sycophant", meaning: "a person who flatters important people for favours", example: "The manager surrounded himself with sycophants.", pic: "🙇", pos: "n", ipa: "/ˈsɪkəfænt/", cat: "Work" },
  { word: "taciturn", meaning: "speaking very little", example: "The taciturn farmer answered in grunts.", pic: "🤐", pos: "adj", ipa: "/ˈtæsɪtɜːn/", cat: "People" },
  { word: "tendentious", meaning: "biased; supporting a particular opinion", example: "The report was tendentious and unfair.", pic: "⚖️", pos: "adj", ipa: "/tenˈdenʃəs/", cat: "Talk" },
  { word: "timorous", meaning: "nervous and easily frightened", example: "The timorous kitten hid under the sofa.", pic: "🐱", pos: "adj", ipa: "/ˈtɪmərəs/", cat: "Emotions" },
  { word: "tractable", meaning: "easy to control or deal with", example: "The students were tractable and attentive.", pic: "🦮", pos: "adj", ipa: "/ˈtræktəbl/", cat: "School" },
  { word: "transient", meaning: "lasting only a short time", example: "Fame can be transient.", pic: "🫧", pos: "adj", ipa: "/ˈtrænziənt/", cat: "Culture" },
  { word: "truculent", meaning: "aggressive and quick to argue", example: "The truculent customer demanded a refund.", pic: "😠", pos: "adj", ipa: "/ˈtrʌkjələnt/", cat: "Shopping" },
  { word: "ubiquitous", meaning: "seeming to be everywhere", example: "Smartphones are now ubiquitous.", pic: "📱", pos: "adj", ipa: "/juːˈbɪkwɪtəs/", cat: "Tech" },
  { word: "unassailable", meaning: "impossible to attack or doubt", example: "Her evidence was unassailable.", pic: "🛡️", pos: "adj", ipa: "/ˌʌnəˈseɪləbl/", cat: "Talk" },
  { word: "vacillate", meaning: "to keep changing your opinion", example: "He vacillated between two offers.", pic: "🎢", pos: "v", ipa: "/ˈvæsɪleɪt/", cat: "Goals" },
  { word: "vapid", meaning: "boring and without interest or meaning", example: "The vapid conversation bored me.", pic: "😶", pos: "adj", ipa: "/ˈvæpɪd/", cat: "Talk" },
  { word: "venal", meaning: "willing to accept bribes", example: "The venal official sold secrets.", pic: "💷", pos: "adj", ipa: "/ˈviːnl/", cat: "Culture" },
  { word: "veracious", meaning: "truthful and honest", example: "The veracious report was trusted by all.", pic: "💯", pos: "adj", ipa: "/vəˈreɪʃəs/", cat: "Talk" },
  { word: "vicarious", meaning: "experienced through someone else", example: "Parents feel vicarious joy at a child's success.", pic: "🪞", pos: "adj", ipa: "/vɪˈkeəriəs/", cat: "Emotions" },
  { word: "vindicate", meaning: "to prove someone was right or innocent", example: "The verdict vindicated her claims.", pic: "⚖️", pos: "v", ipa: "/ˈvɪndɪkeɪt/", cat: "Culture" },
  { word: "vituperate", meaning: "to criticise very harshly", example: "He vituperated against the decision.", pic: "🗯️", pos: "v", ipa: "/vaɪˈtjuːpəreɪt/", cat: "Talk" },
  { word: "volition", meaning: "the power to choose freely", example: "She left of her own volition.", pic: "🦅", pos: "n", ipa: "/vəˈlɪʃn/", cat: "Goals" },
  { word: "wanton", meaning: "deliberate and without reason", example: "The vandals caused wanton destruction.", pic: "💥", pos: "adj", ipa: "/ˈwɒntən/", cat: "Culture" },
  { word: "zealot", meaning: "a person with extreme strong beliefs", example: "A religious zealot interrupted the meeting.", pic: "🔥", pos: "n", ipa: "/ˈzelət/", cat: "Culture" }
];
