/* Vocabulary Pro — unified rich vocabulary data
   Schema per entry: id, word, level, cat, aud(kids|teens|adults), pos, ipa,
   itype(illustration|scene|diagram|photo), alt, def, az, ex, syn[], ant[], col[], fam[]
   Words with artwork in vocabpro-art.js reference it by id; others use the
   professional placeholder until an image is added via Admin (VP.custom) or assets. */
(function () {
  const W = [];
  window.VP_WORDS = W;
  window.VP_CATS = ['Family', 'People', 'Home', 'Food', 'Animals', 'Nature', 'Weather', 'School', 'Work', 'Business', 'Travel', 'Transport', 'City', 'Shopping', 'Money', 'Time', 'Feelings', 'Character', 'Health', 'Technology', 'Communication', 'Culture', 'Sports', 'Entertainment', 'Environment', 'Science', 'Society', 'Economy', 'Politics', 'Media', 'Globalization', 'Academic Writing', 'IELTS'];
  function VP(word, lv, cat, aud, pos, ipa, itype, alt, def, az, ex, syn, ant, col, fam) {
    W.push({ id: word.toLowerCase().replace(/[^a-z0-9]+/g, '-'), word, level: lv, cat, aud, pos, ipa, itype, alt, def, az, ex, syn: syn || [], ant: ant || [], col: col || [], fam: fam || [] });
  }
  /* ---------- Children · A1 (friendly object illustrations) ---------- */
  VP('apple', 'A1', 'Food', 'kids', 'noun', '/ˈæpl/', 'illustration', 'A red apple with a green leaf', 'A round fruit that can be red, green or yellow.', 'alma', 'I eat an apple every day.', [], [], ['eat an apple', 'apple juice', 'an apple a day'], []);
  VP('bread', 'A1', 'Food', 'kids', 'noun', '/bred/', 'illustration', 'A golden loaf of fresh bread', 'A basic food made of flour, water and yeast, baked in an oven.', 'çörək', 'We buy fresh bread every morning.', ['loaf'], [], ['a loaf of bread', 'brown bread', 'bread and butter'], []);
  VP('milk', 'A1', 'Food', 'kids', 'noun', '/mɪlk/', 'illustration', 'A milk carton and a glass of milk', 'A white drink that comes from cows.', 'süd', 'The baby drinks warm milk.', [], [], ['a glass of milk', 'warm milk', 'milk shake'], []);
  VP('dog', 'A1', 'Animals', 'kids', 'noun', '/dɒɡ/', 'illustration', 'A happy golden dog sitting down', 'A common animal that people keep as a pet; it says "woof".', 'it', 'My dog sleeps in the garden.', ['puppy'], ['cat'], ['walk the dog', 'a pet dog', 'dog training'], []);
  VP('cat', 'A1', 'Animals', 'kids', 'noun', '/kæt/', 'illustration', 'A grey cat with a long tail', 'A small animal with soft fur that says "meow"; people keep it as a pet.', 'pişik', 'The cat is sleeping on the sofa.', ['kitten'], ['dog'], ['a cat sleeps', 'feed the cat', 'a wild cat'], []);
  VP('tree', 'A1', 'Nature', 'kids', 'noun', '/triː/', 'illustration', 'A green tree full of red fruit', 'A tall plant with a wooden trunk, branches and leaves.', 'ağac', 'Birds build nests in that tall tree.', [], [], ['a tall tree', 'climb a tree', 'tree house'], ['forest (n)']);
  VP('sun', 'A1', 'Weather', 'kids', 'noun', '/sʌn/', 'illustration', 'A bright smiling sun', 'The big bright star that gives us light and warmth in the day.', 'günəş', 'The sun is very bright today.', [], [], ['the sun shines', 'in the sun', 'sunlight (n)'], ['sunny (adj)', 'sunshine (n)']);
  VP('house', 'A1', 'Home', 'kids', 'noun', '/haʊs/', 'illustration', 'A small house with a red roof', 'A building where people live, usually for one family.', 'ev, malikanə', 'Their house has a red roof.', ['home'], [], ['a big house', 'clean the house', 'housework (n)'], ['home (n)', 'housing (n)']);
  VP('bed', 'A1', 'Home', 'kids', 'noun', '/bed/', 'illustration', 'A tidy bed with a blue pillow and a red heart', 'A piece of furniture that you sleep on.', 'çarpayı, yataq', 'I go to bed at nine o’clock.', [], [], ['go to bed', 'make the bed', 'a single bed'], ['bedroom (n)']);
  VP('ball', 'A1', 'Entertainment', 'kids', 'noun', '/bɔːl/', 'illustration', 'A black and white football', 'A round object that you throw, kick or bounce in games.', 'top', 'The children are playing with a ball.', [], [], ['play with a ball', 'kick the ball', 'throw a ball'], ['football (n)', 'basketball (n)']);
  VP('book', 'A1', 'School', 'kids', 'noun', '/bʊk/', 'illustration', 'An open book with blank pages', 'Pages with words and pictures fastened together that you read.', 'kitab', 'She reads a book before sleep.', [], [], ['read a book', 'a picture book', 'bookshop (n)'], ['booklet (n)', 'notebook (n)']);
  VP('school', 'A1', 'School', 'kids', 'noun', '/skuːl/', 'illustration', 'A school building with a flag and a bell', 'A place where children go to learn.', 'məktəb', 'I walk to school with my friends.', [], [], ['go to school', 'primary school', 'schoolbag (n)'], ['schoolyard (n)']);
  VP('family', 'A1', 'Family', 'kids', 'noun', '/ˈfæməli/', 'illustration', 'A mother, father and child standing together', 'A group of people who are related, such as parents and children.', 'ailə', 'My family has four people.', [], [], ['a big family', 'family member', 'family tree'], ['familial (adj)']);
  VP('bicycle', 'A1', 'Transport', 'kids', 'noun', '/ˈbaɪsɪkl/', 'illustration', 'A red bicycle with two wheels', 'A vehicle with two wheels that you ride by pushing the pedals.', 'velosiped', 'He rides his bicycle to the park.', ['bike'], [], ['ride a bicycle', 'bicycle lane', 'cycle (v)'], ['cyclist (n)', 'cycling (n)']);
  /* ---------- Teenagers · A2–B1 (modern lifestyle scenes) ---------- */
  VP('journey', 'A2', 'Travel', 'teens', 'noun', '/ˈdʒɜːni/', 'scene', 'A road leading towards mountains with a suitcase', 'An act of travelling from one place to another, especially a long distance.', 'səfər, yol', 'The journey to the mountains took four hours.', ['trip', 'travel (n)'], [], ['a long journey', 'begin a journey', 'journey time'], []);
  VP('crowded', 'B1', 'City', 'teens', 'adjective', '/ˈkraʊdɪd/', 'scene', 'A crowded city street full of people', 'Full of people, with very little space to move.', 'izdihamlı, qalanq', 'The market was crowded on Saturday.', ['packed', 'busy'], ['empty', 'deserted'], ['a crowded street', 'crowded with tourists', 'badly crowded'], ['crowd (n)', 'crowdedness (n)']);
  VP('confident', 'B1', 'Character', 'teens', 'adjective', '/ˈkɒnfɪdənt/', 'scene', 'A speaker presenting confidently to an audience', 'Believing in yourself and your ability to do things well.', 'özünə əmin', 'She felt confident before the exam.', ['self-assured', 'sure of yourself'], ['shy', 'unsure'], ['feel confident', 'a confident speaker', 'grow more confident'], ['confidence (n)', 'confidently (adv)']);
  VP('generous', 'A2', 'Character', 'teens', 'adjective', '/ˈdʒenərəs/', 'scene', 'A person giving a gift to another person', 'Happy to give more money, help or time than is expected.', 'səxavətli', 'He is generous with his time.', ['giving', 'kind-hearted'], ['mean', 'stingy'], ['a generous gift', 'generous with money', 'generosity (n)'], ['generously (adv)']);
  VP('exhausted', 'B1', 'Feelings', 'teens', 'adjective', '/ɪɡˈzɔːstɪd/', 'scene', 'A tired student resting their head on a desk after a long day', 'Extremely tired, with no energy left.', 'ərzindən çıxmış, gücsüz', 'After the match I was completely exhausted.', ['worn out', 'drained'], ['energetic', 'refreshed'], ['feel exhausted', 'physically exhausted', 'totally exhausted'], ['exhaustion (n)', 'exhausting (adj)']);
  VP('whisper', 'A2', 'Communication', 'teens', 'verb', '/ˈwɪspə/', 'scene', 'One person whispering a secret to another', 'To speak very quietly, using your breath rather than your voice.', 'pıçıldamaq', 'She whispered the answer to me.', ['murmur'], ['shout', 'yell'], ['whisper a secret', 'whisper to someone', 'in a whisper'], ['whisper (n)']);
  VP('festival', 'B1', 'Culture', 'teens', 'noun', '/ˈfestɪvl/', 'scene', 'A night festival with flags, lights and dancing', 'A special day or event when people celebrate something.', 'bayram, festival', 'The city holds a music festival every summer.', ['celebration'], [], ['a music festival', 'hold a festival', 'festival season'], ['festive (adj)']);
  VP('recycle', 'A2', 'Environment', 'teens', 'verb', '/ˌriːˈsaɪkl/', 'scene', 'Colourful recycling bins under a green arrow', 'To collect and treat used materials so they can be used again.', 'təkrar emal etmək', 'We recycle paper, glass and plastic.', ['reuse', 'process'], ['waste', 'discard'], ['recycle waste', 'recycling bin', 'recyclable (adj)'], ['recycling (n)', 'recycled (adj)']);
  VP('market', 'A2', 'Shopping', 'teens', 'noun', '/ˈmɑːkɪt/', 'scene', 'A street market stall with fruit and vegetables', 'A place where people buy and sell goods, especially outdoors.', 'bazar', 'Grandmother sells cheese at the market.', [], [], ['a street market', 'go to the market', 'market stall'], ['marketing (n)', 'supermarket (n)']);
  VP('volunteer', 'B1', 'Society', 'teens', 'noun', '/ˌvɒlənˈtɪə/', 'scene', 'Two volunteers carrying a donation box with a heart', 'Someone who does work willingly without being paid.', 'konullu', 'Volunteers cleaned the beach on Sunday.', [], [], ['work as a volunteer', 'volunteer work', 'voluntary (adj)'], ['voluntarily (adv)', 'volunteering (n)']);
  /* ---------- Adults / Academic · B2–C2 (editorial scenes & diagrams) ---------- */
  VP('negotiation', 'B2', 'Business', 'adults', 'noun', '/nɪˌɡəʊʃiˈeɪʃn/', 'scene', 'Two business representatives discussing an agreement at a table', 'A formal discussion between people who are trying to reach an agreement.', 'müzavirə', 'After long negotiations, both sides signed the contract.', ['bargaining', 'talks'], [], ['enter negotiations', 'wage negotiations', 'a negotiation process'], ['negotiate (v)', 'negotiator (n)', 'negotiable (adj)']);
  VP('economic growth', 'B2', 'Economy', 'adults', 'noun', '/ˌiːkəˈnɒmɪk ˈɡrəʊθ/', 'diagram', 'A rising bar chart with an upward arrow', 'An increase in the amount of goods and services that a country produces over time.', 'iqtisadi artım', 'Economic growth slowed to two per cent last year.', ['expansion'], ['recession', 'contraction'], ['sustain economic growth', 'rapid economic growth', 'annual growth rate'], ['grow (v)', 'growth (n)']);
  VP('ancient', 'B2', 'Culture', 'adults', 'adjective', '/ˈeɪnʃənt/', 'scene', 'An ancient temple with tall stone columns', 'Very old, belonging to a period in the far distant past.', 'qədim', 'They explored the ruins of an ancient temple.', ['age-old', 'antique'], ['modern', 'contemporary'], ['an ancient city', 'ancient history', 'in ancient times'], ['antiquity (n)']);
  VP('nevertheless', 'C1', 'Academic Writing', 'adults', 'adverb', '/ˌnevəðəˈles/', 'scene', 'Two contrasting documents joined by an up-and-down arrow', 'Used to say that something is true in spite of what was just mentioned; however.', 'buna baxmayaraq', 'The task was difficult; nevertheless, she finished it on time.', ['however', 'nonetheless', 'even so'], [], ['nevertheless, it is clear that…', 'a necessary, nevertheless costly, step'], [], []);
  VP('fragile', 'B2', 'Character', 'adults', 'adjective', '/ˈfrædʒaɪl/', 'scene', 'Hands carefully holding a delicate glass object', 'Easily broken or damaged; delicate.', 'kövrək, incə', 'Handle the vase carefully — it is fragile.', ['delicate', 'brittle'], ['sturdy', 'robust'], ['fragile goods', 'a fragile economy', 'emotionally fragile'], ['fragility (n)', 'fragilely (adv)']);
  VP('research', 'B2', 'Science', 'adults', 'noun', '/rɪˈsɜːtʃ/', 'scene', 'A scientist with a microscope and a results sheet', 'Careful study of a subject to discover new facts or information.', 'tədqiqat', 'Her research focuses on clean energy.', ['investigation', 'study'], [], ['carry out research', 'scientific research', 'research findings'], ['researcher (n)', 'research (v)']);
  VP('urbanization', 'B2', 'Globalization', 'adults', 'noun', '/ˌɜːbənaɪˈzeɪʃn/', 'scene', 'A growing city skyline of apartment blocks', 'The process by which more and more people move to live in cities.', 'şəhərləşmə', 'Rapid urbanization puts pressure on housing.', [], ['depopulation'], ['rapid urbanization', 'urbanization rate', 'urban sprawl'], ['urban (adj)', 'urbanize (v)']);
  VP('inflation', 'B2', 'Economy', 'adults', 'noun', '/ɪnˈfleɪʃn/', 'diagram', 'A price tag beside a red upward arrow', 'A general increase in prices and a fall in the value of money.', 'inflyasiya', 'Inflation reached eight per cent this year.', ['price rises'], ['deflation'], ['control inflation', 'the inflation rate', 'runaway inflation'], ['inflate (v)', 'inflationary (adj)']);
  VP('pollution', 'B2', 'Environment', 'adults', 'noun', '/pəˈluːʃn/', 'scene', 'Factory chimneys releasing smoke into the sky', 'The process of making air, water or land dirty and dangerous.', 'çirklənmə', 'Air pollution in big cities is a serious problem.', ['contamination'], [], ['air pollution', 'reduce pollution', 'pollution levels'], ['pollute (v)', 'pollutant (n)']);
  VP('artificial intelligence', 'C1', 'Technology', 'adults', 'noun', '/ˌɑːtɪfɪʃl ɪnˈtelɪdʒəns/', 'diagram', 'A glowing circuit network shaped like a brain', 'Computer systems that are able to perform tasks that normally need human intelligence.', 'süni intellekt', 'Artificial intelligence is changing how we work.', ['AI', 'machine intelligence'], [], ['artificial intelligence systems', 'powered by AI', 'AI technology'], ['intelligent (adj)', 'intelligence (n)']);
  VP('globalization', 'B2+', 'Globalization', 'adults', 'noun', '/ˌɡləʊbəlaɪˈzeɪʃn/', 'diagram', 'A globe connected by trade routes between continents', 'The process by which countries become connected through trade, culture and communication.', 'qloballaşma', 'Globalization has spread popular culture worldwide.', [], ['isolationism'], ['economic globalization', 'the effects of globalization', 'increasingly globalized'], ['global (adj)', 'globally (adv)']);
  VP('renewable energy', 'B2', 'Science', 'adults', 'noun', '/rɪˈnjuːəbl ˈenədʒi/', 'scene', 'Wind turbines and solar panels under the sun', 'Energy from sources that never run out, such as wind and sunlight.', 'bərpa olunan enerji', 'The country invests heavily in renewable energy.', ['clean energy', 'green energy'], ['fossil fuels'], ['renewable energy sources', 'invest in renewables', 'renewable capacity'], ['renew (v)', 'renewable (adj)']);
  /* ---------- Additional rich entries without artwork (expandable via Admin) ---------- */
  VP('happy', 'A1', 'Feelings', 'kids', 'adjective', '/ˈhæpi/', '', '', 'Feeling or showing pleasure.', 'xoşbəxt, şad', 'The children are happy today.', ['glad', 'cheerful'], ['sad', 'unhappy'], ['feel happy', 'happy news', 'happiness (n)'], ['happily (adv)', 'happiness (n)']);
  VP('big', 'A1', 'Character', 'kids', 'adjective', '/bɪɡ/', '', '', 'Large in size.', 'böyük', 'An elephant is a big animal.', ['large', 'huge'], ['small', 'little'], ['a big house', 'big city', 'bigger than'], ['bigger (adj)', 'biggest (adj)']);
  VP('mother', 'A1', 'Family', 'kids', 'noun', '/ˈmʌðə/', '', '', 'A female parent.', 'ana, nənə (mum)', 'My mother cooks dinner.', ['mum', 'mom'], ['father'], ['my mother', 'a mother of two', 'mother tongue'], ['motherly (adj)', 'motherhood (n)']);
  VP('water', 'A1', 'Food', 'kids', 'noun', '/ˈwɔːtə/', '', '', 'The clear liquid that falls as rain and we drink.', 'su', 'I drink water after sport.', [], [], ['drink water', 'a glass of water', 'water bottle'], ['watery (adj)']);
  VP('run', 'A1', 'Sports', 'kids', 'verb', '/rʌn/', '', '', 'To move quickly using your legs.', 'qaçmaq', 'I run in the park every morning.', ['jog', 'sprint'], ['walk'], ['run fast', 'run a race', 'go for a run'], ['runner (n)', 'running (n)']);
  VP('eat', 'A1', 'Food', 'kids', 'verb', '/iːt/', '', '', 'To put food in your mouth and swallow it.', 'yemək', 'We eat dinner at seven.', ['have'], [], ['eat lunch', 'eat out', 'eatable (adj)'], ['eater (n)']);
  VP('morning', 'A1', 'Time', 'kids', 'noun', '/ˈmɔːnɪŋ/', '', '', 'The early part of the day, from sunrise to noon.', 'səhər', 'I read in the morning.', [], ['evening'], ['every morning', 'in the morning', 'good morning'], ['mornings (adv)']);
  VP('rain', 'A1', 'Weather', 'kids', 'noun', '/reɪn/', '', '', 'Water that falls from clouds in the sky.', 'yağış', 'Take an umbrella — there is rain today.', ['rainfall'], ['drought'], ['heavy rain', 'in the rain', 'rainy day'], ['rainy (adj)', 'rainless (adj)']);
  VP('cold', 'A1', 'Weather', 'kids', 'adjective', '/kəʊld/', '', '', 'Having a low temperature.', 'soyuq', 'The water is too cold.', ['chilly', 'freezing'], ['hot', 'warm'], ['cold water', 'feel cold', 'catch a cold'], ['coldly (adv)', 'coldness (n)']);
  VP('shoes', 'A1', 'Shopping', 'kids', 'noun', '/ʃuːz/', '', '', 'Objects that you wear on your feet.', 'ayaqqabı', 'My new shoes are white.', ['footwear'], [], ['a pair of shoes', 'sports shoes', 'try on shoes'], ['shoemaker (n)']);
  VP('money', 'A1', 'Money', 'kids', 'noun', '/ˈmʌni/', '', '', 'Coins or notes used to buy things.', 'pul', 'I save money for a new bike.', ['cash', 'funds'], [], ['save money', 'spend money', 'pocket money'], ['monetary (adj)']);
  VP('phone', 'A1', 'Technology', 'teens', 'noun', '/fəʊn/', '', '', 'A device used to talk to people far away.', 'telefon', 'Call me on my phone.', ['mobile', 'telephone'], [], ['answer the phone', 'phone call', 'smartphone (n)'], ['phoning (n)']);
  VP('computer', 'A1', 'Technology', 'teens', 'noun', '/kəmˈpjuːtə/', '', '', 'An electronic machine that stores and processes information.', 'kompüter', 'She works on her computer.', [], [], ['use a computer', 'computer screen', 'computer skills'], ['compute (v)', 'computing (n)']);
  VP('city', 'A1', 'City', 'teens', 'noun', '/ˈsɪti/', '', '', 'A large and important town.', 'şəhər', 'Baku is a beautiful city.', ['town'], ['village'], ['city centre', 'a big city', 'city life'], ['citizen (n)', 'citizenship (n)']);
  VP('beach', 'A1', 'Nature', 'teens', 'noun', '/biːtʃ/', '', '', 'An area of sand or stones beside the sea.', 'çimərlik', 'We spent the day at the beach.', ['coast', 'seaside'], [], ['at the beach', 'sandy beach', 'beach holiday'], ['beachgoer (n)']);
  VP('holiday', 'A1', 'Travel', 'teens', 'noun', '/ˈhɒlədeɪ/', '', '', 'A time when you do not work or study and can rest or travel.', 'istirahət, tətil', 'We go to the seaside every holiday.', ['vacation', 'break'], [], ['go on holiday', 'public holiday', 'holidaymaker (n)'], ['holidaying (n)']);
  VP('friend', 'A1', 'People', 'kids', 'noun', '/frend/', '', '', 'A person you like and know well.', 'dost', 'My friend lives next door.', ['mate', 'pal'], ['enemy'], ['best friend', 'make friends', 'friendship (n)'], ['friendly (adj)', 'friendship (n)']);
  VP('teacher', 'A1', 'School', 'kids', 'noun', '/ˈtiːtʃə/', '', '', 'A person who helps students to learn.', 'müəllim', 'Our teacher explains grammar clearly.', ['instructor'], ['student'], ['an English teacher', 'teacher training', 'teaching (n)'], ['teach (v)', 'teaching (n)']);
  VP('health', 'B1', 'Health', 'adults', 'noun', '/helθ/', '', '', 'The condition of your body and mind; being well and without illness.', 'sağlamlıq', 'Regular exercise is good for your health.', ['wellbeing'], ['illness', 'disease'], ['good health', 'health service', 'healthy lifestyle'], ['healthy (adj)', 'healthcare (n)']);
  VP('benefit', 'B1', 'Academic Writing', 'adults', 'noun', '/ˈbenɪfɪt/', '', '', 'An advantage or profit gained from something.', 'fayda, mənfəət', 'Exercise has many health benefits.', ['advantage', 'gain'], ['drawback', 'disadvantage'], ['health benefits', 'benefit from', 'mutual benefit'], ['beneficial (adj)', 'beneficiary (n)']);
  VP('environment', 'B1', 'Environment', 'adults', 'noun', '/ɪnˈvaɪrənmənt/', '', '', 'The natural world of land, sea, plants and animals.', 'mühit', 'We must protect the environment.', ['surroundings', 'habitat'], [], ['protect the environment', 'environmental damage', 'eco-friendly'], ['environmental (adj)', 'environmentalist (n)']);
  VP('improve', 'B1', 'Academic Writing', 'adults', 'verb', '/ɪmˈpruːv/', '', '', 'To make or become better.', 'yaxşılaşdırmaq', 'Reading every day will improve your vocabulary.', ['enhance', 'upgrade'], ['worsen', 'damage'], ['improve skills', 'improve significantly', 'room for improvement'], ['improvement (n)', 'improved (adj)']);
  VP('behaviour', 'B1', 'Society', 'adults', 'noun', '/bɪˈheɪvjə/', '', '', 'The way that a person acts, especially towards others.', 'davranış', 'His behaviour at school improved last term.', ['conduct'], ['misconduct'], ['good behaviour', 'behaviour towards', 'behavioural change'], ['behave (v)', 'behavioural (adj)']);
  VP('opportunity', 'B1', 'Work', 'adults', 'noun', '/ˌɒpəˈtjuːnəti/', '', '', 'A chance to do something good or useful.', 'fürsət, imkan', 'Studying abroad is a great opportunity.', ['chance', 'opening'], [], ['a great opportunity', 'miss the opportunity', 'equal opportunities'], ['opportunistic (adj)']);
  VP('experience', 'B1', 'Work', 'adults', 'noun', '/ɪkˈspɪəriəns/', '', '', 'Knowledge or skill gained from doing a job or activity.', 'təcrübə', 'She has ten years of teaching experience.', ['expertise'], ['inexperience'], ['work experience', 'gain experience', 'hands-on experience'], ['experienced (adj)', 'inexperienced (adj)']);
  VP('achieve', 'B1', 'Academic Writing', 'adults', 'verb', '/əˈtʃiːv/', '', '', 'To succeed in doing or getting something after effort.', 'nail olmaq', 'The team achieved its sales target.', ['accomplish', 'attain'], ['fail'], ['achieve a goal', 'achieve success', 'achievable target'], ['achievement (n)', 'achievable (adj)']);
  VP('develop', 'B1', 'Academic Writing', 'adults', 'verb', '/dɪˈveləp/', '', '', 'To grow, change or improve over time; to create something new.', 'inkişaf etdirmək', 'The city developed a new transport plan.', ['grow', 'advance'], ['stagnate'], ['develop a plan', 'rapidly developing', 'developing country'], ['development (n)', 'developer (n)']);
  VP('knowledge', 'B1', 'Education', 'adults', 'noun', '/ˈnɒlɪdʒ/', '', '', 'The information and understanding that you have gained.', 'bilik', 'She has deep knowledge of history.', [], ['ignorance'], ['deep knowledge', 'knowledge of', 'background knowledge'], ['knowledgeable (adj)']);
  VP('culture', 'B1', 'Culture', 'adults', 'noun', '/ˈkʌltʃə/', '', '', 'The customs, art and way of life of a group of people.', 'mədəniyyət', 'Food is an important part of culture.', ['heritage'], [], ['local culture', 'cultural heritage', 'multicultural society'], ['cultural (adj)', 'culturally (adv)']);
  VP('significant', 'B2', 'Academic Writing', 'adults', 'adjective', '/sɪɡˈnɪfɪkənt/', '', '', 'Large or important enough to have a real effect.', 'əhəmiyyətli, mühüm', 'There was a significant increase in sales.', ['considerable', 'substantial'], ['insignificant', 'negligible'], ['significant increase', 'statistically significant', 'play a significant role'], ['significance (n)', 'significantly (adv)']);
  VP('decline', 'B2', 'Economy', 'adults', 'verb', '/dɪˈklaɪn/', '', '', 'To become smaller, weaker or less in quantity or quality.', 'azalmaq, düşmək', 'Sales declined sharply in winter.', ['decrease', 'diminish'], ['increase', 'rise'], ['decline sharply', 'a steady decline', 'declining population'], ['decline (n)', 'declining (adj)']);
  VP('consequence', 'B2', 'Academic Writing', 'adults', 'noun', '/ˈkɒnsɪkwəns/', '', '', 'A result or effect of an action or condition.', 'nəticə', 'Rising sea levels are a consequence of climate change.', ['result', 'outcome'], ['cause'], ['as a consequence', 'face the consequences', 'far-reaching consequences'], ['consequently (adv)', 'consequent (adj)']);
  VP('controversial', 'B2', 'Politics', 'adults', 'adjective', '/ˌkɒntrəˈvɜːʃl/', '', '', 'Causing a lot of public disagreement and discussion.', 'mübahisəli, narazılıq doğuran', 'The new law is highly controversial.', ['debatable', 'contentious'], ['uncontroversial'], ['a controversial decision', 'controversial issue', 'spark controversy'], ['controversy (n)', 'controversially (adv)']);
  VP('sustainable', 'B2', 'Environment', 'adults', 'adjective', '/səˈsteɪnəbl/', '', '', 'Able to continue for a long time without harming the environment.', 'davamlı', 'Cities need sustainable transport systems.', ['viable', 'eco-friendly'], ['unsustainable'], ['sustainable development', 'environmentally sustainable', 'sustainability goals'], ['sustainability (n)', 'sustain (v)']);
  VP('estimate', 'B2', 'Academic Writing', 'adults', 'verb', '/ˈestɪmeɪt/', '', '', 'To guess an amount or value using judgement and calculation.', 'təxmin etmək', 'Experts estimate the cost at two million.', ['approximate', 'calculate roughly'], [], ['estimate the cost', 'a rough estimate', 'estimated at'], ['estimation (n)', 'estimated (adj)']);
  VP('impact', 'B2', 'Academic Writing', 'adults', 'noun', '/ˈɪmpækt/', '', '', 'A strong effect that something has on a person or situation.', 'təsir', 'Tourism has a major impact on the local economy.', ['effect', 'influence'], [], ['a major impact', 'impact on society', 'positive impact'], ['impactful (adj)']);
  VP('policy', 'B2', 'Politics', 'adults', 'noun', '/ˈpɒləsi/', '', '', 'A set of ideas or a plan of what to do, decided by a government or organization.', 'siyasət, siyasət kursu', 'The government introduced a new housing policy.', ['strategy'], [], ['foreign policy', 'policy maker', 'fiscal policy'], ['policy-making (n)']);
  VP('resource', 'B2', 'Economy', 'adults', 'noun', '/rɪˈsɔːs/', '', '', 'A supply of money, materials or people that can be used when needed.', 'resurs', 'Natural resources must be managed carefully.', ['supply', 'asset'], [], ['natural resources', 'human resources', 'resource management'], ['resourceful (adj)']);
  VP('efficient', 'B2', 'Business', 'adults', 'adjective', '/ɪˈfɪʃnt/', '', '', 'Working well without wasting time, money or energy.', 'səmərəli', 'The new engine is more efficient.', ['effective', 'productive'], ['inefficient', 'wasteful'], ['fuel-efficient', 'highly efficient', 'energy efficiency'], ['efficiency (n)', 'efficiently (adv)']);
  VP('evidence', 'B2', 'Academic Writing', 'adults', 'noun', '/ˈevɪdəns/', '', '', 'Facts or information that show something is true.', 'dəlil, sübut', 'There is strong evidence that exercise improves mood.', ['proof', 'data'], [], ['strong evidence', 'gather evidence', 'evidence-based'], ['evident (adj)', 'evidently (adv)']);
  VP('trend', 'B2', 'Media', 'adults', 'noun', '/trend/', '', '', 'A general direction in which something is developing or changing.', 'meyl, tendensiya', 'Online shopping is a growing trend.', ['tendency'], [], ['a growing trend', 'follow the trend', 'trend analysis'], ['trendy (adj)']);
  VP('generate', 'B2', 'Academic Writing', 'adults', 'verb', '/ˈdʒenəreɪt/', '', '', 'To produce or create something.', 'yaratmaq, istehsal etmək', 'Wind turbines generate electricity.', ['produce', 'create'], [], ['generate electricity', 'generate income', 'generate interest'], ['generation (n)', 'generator (n)']);
  VP('community', 'B2', 'Society', 'adults', 'noun', '/kəˈmjuːnəti/', '', '', 'A group of people living in the same place or sharing interests.', 'icma, cəmiyyət', 'The local community supported the project.', ['society'], [], ['local community', 'community centre', 'community spirit'], ['communal (adj)']);
  VP('substantial', 'C1', 'Academic Writing', 'adults', 'adjective', '/səbˈstænʃl/', '', '', 'Large in amount, size or importance.', 'əhəmiyyətli, böyük həcmli', 'The project requires a substantial investment.', ['considerable', 'sizeable'], ['minimal', 'negligible'], ['substantial evidence', 'a substantial amount', 'substantial growth'], ['substantially (adv)', 'substance (n)']);
  VP('inevitable', 'C1', 'Academic Writing', 'adults', 'adjective', '/ɪnˈevɪtəbl/', '', '', 'Certain to happen and impossible to avoid.', 'qaçınılmaz', 'Some change is inevitable in a growing city.', ['unavoidable', 'certain'], ['avoidable'], ['seem inevitable', 'an inevitable result', 'inevitability of change'], ['inevitably (adv)', 'inevitability (n)']);
  VP('ambiguous', 'C1', 'Academic Writing', 'adults', 'adjective', '/æmˈbɪɡjuəs/', '', '', 'Having more than one possible meaning; unclear.', 'qeyri-müəyyən, ikimənalı', 'The question was ambiguous, so answers varied.', ['unclear', 'vague'], ['clear', 'unambiguous'], ['an ambiguous statement', 'deliberately ambiguous', 'ambiguity in wording'], ['ambiguity (n)', 'unambiguously (adv)']);
  VP('compelling', 'C1', 'Academic Writing', 'adults', 'adjective', '/kəmˈpelɪŋ/', '', '', 'So convincing or interesting that you must believe it or pay attention.', 'inandırıcı, diqqəti cəlbedici', 'She made a compelling argument for reform.', ['convincing', 'persuasive'], ['unconvincing'], ['a compelling argument', 'compelling evidence', 'compelling reasons'], ['compel (v)', 'compellingly (adv)']);
  VP('comprehensive', 'C1', 'Academic Writing', 'adults', 'adjective', '/ˌkɒmprɪˈhensɪv/', '', '', 'Including everything that is necessary; complete.', 'hərtərəfli, əhatəli', 'The report gives a comprehensive overview of the issue.', ['thorough', 'exhaustive'], ['partial', 'incomplete'], ['a comprehensive report', 'comprehensive coverage', 'comprehensively address'], ['comprehensively (adv)', 'comprehensiveness (n)']);
  VP('framework', 'C1', 'Academic Writing', 'adults', 'noun', '/ˈfreɪmwɜːk/', '', '', 'A set of ideas, rules or beliefs used as the basis for decisions.', 'çərçivə, struktur', 'The study uses a theoretical framework.', ['structure', 'system'], [], ['a theoretical framework', 'a legal framework', 'within the framework of'], []);
  VP('mitigate', 'C1', 'Environment', 'adults', 'verb', '/ˈmɪtɪɡeɪt/', '', '', 'To make something bad, such as harm or risk, less serious.', 'yüngülləşdirmək', 'Trees help mitigate the effects of heat.', ['reduce', 'alleviate'], ['worsen', 'aggravate'], ['mitigate risks', 'mitigate the effects', 'risk mitigation'], ['mitigation (n)']);
  VP('prevalent', 'C1', 'Academic Writing', 'adults', 'adjective', '/ˈprevələnt/', '', '', 'Common in a particular place or at a particular time.', 'geniş yayılmış', 'Remote work is increasingly prevalent.', ['widespread', 'common'], ['rare', 'uncommon'], ['increasingly prevalent', 'prevalent among', 'the prevalence of'], ['prevalence (n)', 'prevail (v)']);
  VP('robust', 'C1', 'Business', 'adults', 'adjective', '/rəʊˈbʌst/', '', '', 'Strong and unlikely to fail or break.', 'möhkəm, dayanıqlı', 'The economy remains robust despite the crisis.', ['strong', 'sturdy'], ['fragile', 'weak'], ['a robust economy', 'robust growth', 'robust evidence'], ['robustly (adv)', 'robustness (n)']);
  VP('sophisticated', 'C1', 'Technology', 'adults', 'adjective', '/səˈfɪstɪkeɪtɪd/', '', '', 'Advanced, complex and developed in a clever way.', 'mürəkkəb, zərif', 'The city uses a sophisticated traffic system.', ['advanced', 'complex'], ['simple', 'primitive'], ['sophisticated technology', 'a sophisticated approach', 'sophistication (n)'], ['sophistication (n)']);
  VP('undermine', 'C1', 'Academic Writing', 'adults', 'verb', '/ˌʌndəˈmaɪn/', '', '', 'To weaken something gradually, often secretly.', 'zəiflətmək, aşa salmaq', 'False news undermines public trust.', ['weaken', 'erode'], ['strengthen', 'support'], ['undermine trust', 'undermine efforts', 'undermine confidence'], ['undermining (n)']);
  VP('pervasive', 'C2', 'Academic Writing', 'adults', 'adjective', '/pəˈveɪsɪv/', '', '', 'Present or spreading everywhere in a place or situation.', 'hər yerdə olan, yayılmış', 'Digital technology has a pervasive influence on daily life.', ['widespread', 'pervading'], ['limited', 'confined'], ['a pervasive influence', 'pervasive in society', 'pervasiveness (n)'], ['pervasiveness (n)', 'pervade (v)']);
  VP('intrinsic', 'C2', 'Academic Writing', 'adults', 'adjective', '/ɪnˈtrɪnzɪk/', '', '', 'Belonging naturally to something; essential to its nature.', 'təbii, daxili', 'Curiosity is intrinsic to human learning.', ['inherent', 'essential'], ['extrinsic'], ['intrinsic value', 'intrinsic to', 'intrinsically linked'], ['intrinsically (adv)']);
  VP('conspicuous', 'C2', 'Academic Writing', 'adults', 'adjective', '/kənˈspɪkjuəs/', '', '', 'Very easy to notice; attracting attention.', 'gözə çarpan, nəzərə çarpan', 'There was a conspicuous lack of evidence.', ['noticeable', 'prominent'], ['inconspicuous', 'hidden'], ['conspicuous by its absence', 'a conspicuous example', 'conspicuous consumption'], ['conspicuously (adv)', 'inconspicuous (adj)']);
  VP('counterproductive', 'C2', 'Academic Writing', 'adults', 'adjective', '/ˌkaʊntəprəˈdʌktɪv/', '', '', 'Having the opposite effect to the one you wanted.', 'əks nəticə verən', 'Punishment can be counterproductive in the long run.', ['self-defeating'], ['effective', 'productive'], ['prove counterproductive', 'counterproductive measures'], ['productivity (n)']);
  VP('coherent', 'C1', 'Academic Writing', 'adults', 'adjective', '/kəʊˈhɪərənt/', '', '', 'Well organized, with all parts connected logically.', 'məntiqli, ardıcıl', 'Write a coherent essay with a clear plan.', ['logical', 'consistent'], ['incoherent', 'confused'], ['a coherent argument', 'coherent structure', 'cohesion and coherence'], ['coherence (n)', 'coherently (adv)']);
  VP('advocate', 'C1', 'Politics', 'adults', 'verb', '/ˈædvəkeɪt/', '', '', 'To publicly support or recommend an idea or policy.', 'tərəfdarı olmaq, müdafiə etmək', 'Experts advocate investing in public transport.', ['recommend', 'champion'], ['oppose', 'condemn'], ['advocate reform', 'strongly advocate', 'an advocate of'], ['advocacy (n)']);
  VP('disseminate', 'C2', 'Academic Writing', 'adults', 'verb', '/dɪˈsemɪneɪt/', '', '', 'To spread information or ideas to many people.', 'yaymaq', 'The findings were disseminated through journals.', ['spread', 'distribute'], ['withhold'], ['disseminate information', 'widely disseminated', 'dissemination of knowledge'], ['dissemination (n)']);
  /* ---------- Word-family showcase sets ---------- */
  VP('decide', 'A2', 'Academic Writing', 'teens', 'verb', '/dɪˈsaɪd/', '', '', 'To choose something after thinking about it.', 'qərar vermək', 'We decided to stay at home.', ['choose', 'determine'], ['hesitate'], ['decide to', 'decide on a plan', 'make a decision'], ['decision (n)', 'decisive (adj)', 'decisively (adv)']);
  VP('decision', 'A2', 'Academic Writing', 'teens', 'noun', '/dɪˈsɪʒn/', '', '', 'A choice that you make after thinking.', 'qərar', 'It was a difficult decision.', ['choice'], [], ['make a decision', 'a tough decision', 'decision-making'], ['decide (v)', 'decisive (adj)']);
  VP('decisive', 'B2', 'Character', 'adults', 'adjective', '/dɪˈsaɪsɪv/', '', '', 'Able to make choices quickly and confidently; strongly influencing a result.', 'qəti, həlledici', 'Her decisive action saved the project.', ['determined', 'resolute'], ['indecisive'], ['a decisive victory', 'play a decisive role', 'decisive action'], ['decide (v)', 'decision (n)', 'decisively (adv)']);
  VP('create', 'A2', 'Academic Writing', 'teens', 'verb', '/kriˈeɪt/', '', '', 'To make something new.', 'yaratmaq', 'The app was created by students.', ['make', 'produce'], ['destroy'], ['create jobs', 'create awareness', 'creatively designed'], ['creation (n)', 'creative (adj)', 'creatively (adv)']);
  VP('creative', 'B1', 'Character', 'teens', 'adjective', '/kriˈeɪtɪv/', '', '', 'Good at thinking of new and original ideas.', 'yaradıcı', 'She has creative solutions to problems.', ['inventive', 'imaginative'], ['unimaginative'], ['creative thinking', 'a creative approach', 'creativity (n)'], ['create (v)', 'creativity (n)', 'creatively (adv)']);
  VP('analyse', 'B2', 'Academic Writing', 'adults', 'verb', '/ˈænəlaɪz/', '', '', 'To examine something in detail to understand it better.', 'təhlil etmək', 'The report analyses spending patterns.', ['examine', 'study'], [], ['analyse data', 'analyse critically', 'detailed analysis'], ['analysis (n)', 'analytical (adj)']);
  VP('analysis', 'B2', 'Academic Writing', 'adults', 'noun', '/əˈnæləsɪs/', '', '', 'A detailed examination of something.', 'təhlil', 'His analysis of the data was convincing.', ['examination', 'review'], [], ['a detailed analysis', 'in the final analysis', 'data analysis'], ['analyse (v)', 'analytical (adj)']);
  VP('educate', 'B1', 'Education', 'adults', 'verb', '/ˈedʒukeɪt/', '', '', 'To teach someone, usually at a school or university.', 'təhsil vermək', 'The programme educates children about safety.', ['teach', 'train'], [], ['educate children', 'well-educated', 'educate people about'], ['education (n)', 'educational (adj)', 'educator (n)']);
  VP('education', 'A2', 'Education', 'teens', 'noun', '/ˌedʒuˈkeɪʃn/', '', '', 'The process of teaching and learning at schools and universities.', 'təhsil', 'Education opens many doors.', ['schooling', 'learning'], [], ['free education', 'higher education', 'educational system'], ['educate (v)', 'educational (adj)', 'educator (n)']);
  /* IELTS source tag helper: topic vocabulary that mirrors the IELTS section */
  VP('curriculum', 'B2', 'IELTS', 'adults', 'noun', '/kəˈrɪkjələm/', '', '', 'The subjects included in a course of study.', 'tədris proqramı', 'A balanced curriculum includes arts as well as sciences.', ['syllabus', 'programme of study'], [], ['national curriculum', 'curriculum design', 'core curriculum'], ['curricular (adj)']);
  VP('deforestation', 'B2', 'IELTS', 'adults', 'noun', '/ˌdiːˌfɒrɪˈsteɪʃn/', '', '', 'The cutting down of trees and forests over a large area.', 'meşələrin qırılması', 'Deforestation destroys the habitats of many species.', ['logging'], ['reforestation'], ['combat deforestation', 'widespread deforestation', 'deforestation rates'], ['forest (n)', 'reforestation (n)']);
})();
