/* Extra vocabulary — levels Pre-A1, A1, A2 */
window.LF_VOCAB_EXTRA = window.LF_VOCAB_EXTRA || {};
window.LF_VOCAB_EXTRA["Pre-A1"] = [
  { word: "boy", meaning: "a male child", example: "The boy is playing with his ball.", pic: "👦", pos: "n", ipa: "/bɔɪ/", cat: "People" },
  { word: "girl", meaning: "a female child", example: "The girl has a red dress.", pic: "👧", pos: "n", ipa: "/ɡɜːl/", cat: "People" },
  { word: "man", meaning: "an adult male person", example: "The man is reading a newspaper.", pic: "👨", pos: "n", ipa: "/mæn/", cat: "People" },
  { word: "woman", meaning: "an adult female person", example: "The woman is buying fruit.", pic: "👩", pos: "n", ipa: "/ˈwʊmən/", cat: "People" },
  { word: "baby", meaning: "a very young child", example: "The baby is sleeping.", pic: "👶", pos: "n", ipa: "/ˈbeɪbi/", cat: "People" },
  { word: "brother", meaning: "a boy who has the same parents as you", example: "My brother is ten years old.", pic: "👦", pos: "n", ipa: "/ˈbrʌðə/", cat: "Family" },
  { word: "sister", meaning: "a girl who has the same parents as you", example: "My sister likes music.", pic: "👧", pos: "n", ipa: "/ˈsɪstə/", cat: "Family" },
  { word: "grandmother", meaning: "the mother of your mother or father", example: "My grandmother makes great cake.", pic: "👵", pos: "n", ipa: "/ˈɡrænmʌðə/", cat: "Family" },
  { word: "grandfather", meaning: "the father of your mother or father", example: "My grandfather tells funny stories.", pic: "👴", pos: "n", ipa: "/ˈɡrænfɑːðə/", cat: "Family" },
  { word: "table", meaning: "a piece of furniture with a flat top and legs", example: "The food is on the table.", pic: "🪑", pos: "n", ipa: "/ˈteɪbl/", cat: "Home" },
  { word: "chair", meaning: "a seat for one person", example: "Please sit on this chair.", pic: "🪑", pos: "n", ipa: "/tʃeə/", cat: "Home" },
  { word: "door", meaning: "a thing you open to enter a room", example: "Close the door, please.", pic: "🚪", pos: "n", ipa: "/dɔː/", cat: "Home" },
  { word: "window", meaning: "an opening in a wall with glass", example: "Look out of the window.", pic: "🪟", pos: "n", ipa: "/ˈwɪndəʊ/", cat: "Home" },
  { word: "bed", meaning: "a thing you sleep on", example: "I go to bed at nine.", pic: "🛏️", pos: "n", ipa: "/bed/", cat: "Home" },
  { word: "room", meaning: "a space inside a building", example: "This is my room.", pic: "🚪", pos: "n", ipa: "/ruːm/", cat: "Home" },
  { word: "garden", meaning: "an area of land with plants next to a house", example: "We play in the garden.", pic: "🌳", pos: "n", ipa: "/ˈɡɑːdn/", cat: "Home" },
  { word: "ball", meaning: "a round thing you throw or kick", example: "The dog plays with the ball.", pic: "⚽", pos: "n", ipa: "/bɔːl/", cat: "Leisure" },
  { word: "doll", meaning: "a toy shaped like a small person", example: "The girl holds her doll.", pic: "🧸", pos: "n", ipa: "/dɒl/", cat: "Leisure" },
  { word: "toy", meaning: "a thing a child plays with", example: "The boy has a new toy.", pic: "🧸", pos: "n", ipa: "/tɔɪ/", cat: "Leisure" },
  { word: "tree", meaning: "a tall plant with a trunk and leaves", example: "A bird is in the tree.", pic: "🌳", pos: "n", ipa: "/triː/", cat: "Nature" },
  { word: "flower", meaning: "the coloured part of a plant", example: "This flower is red.", pic: "🌸", pos: "n", ipa: "/ˈflaʊə/", cat: "Nature" },
  { word: "bird", meaning: "an animal with wings that can fly", example: "The bird sings in the morning.", pic: "🐦", pos: "n", ipa: "/bɜːd/", cat: "Nature" },
  { word: "fish", meaning: "an animal that lives in water", example: "The fish is in the water.", pic: "🐟", pos: "n", ipa: "/fɪʃ/", cat: "Nature" },
  { word: "horse", meaning: "a big animal that people ride", example: "The horse runs fast.", pic: "🐴", pos: "n", ipa: "/hɔːs/", cat: "Nature" },
  { word: "milk", meaning: "a white drink from cows", example: "I drink milk with my breakfast.", pic: "🥛", pos: "n", ipa: "/mɪlk/", cat: "Food" },
  { word: "bread", meaning: "a food made from flour and water", example: "I eat bread and butter.", pic: "🍞", pos: "n", ipa: "/bred/", cat: "Food" },
  { word: "egg", meaning: "a food from a chicken", example: "I have an egg for breakfast.", pic: "🥚", pos: "n", ipa: "/eɡ/", cat: "Food" },
  { word: "cheese", meaning: "a food made from milk", example: "I like cheese on my bread.", pic: "🧀", pos: "n", ipa: "/tʃiːz/", cat: "Food" },
  { word: "banana", meaning: "a long yellow fruit", example: "The monkey eats a banana.", pic: "🍌", pos: "n", ipa: "/bəˈnɑːnə/", cat: "Food" },
  { word: "orange", meaning: "a round orange fruit", example: "I eat an orange every day.", pic: "🍊", pos: "n", ipa: "/ˈɒrɪndʒ/", cat: "Food" },
  { word: "tea", meaning: "a hot drink made with leaves and water", example: "She drinks tea in the morning.", pic: "🍵", pos: "n", ipa: "/tiː/", cat: "Food" },
  { word: "juice", meaning: "a drink made from fruit", example: "The children drink orange juice.", pic: "🧃", pos: "n", ipa: "/dʒuːs/", cat: "Food" },
  { word: "rice", meaning: "small white grains eaten with food", example: "We eat rice with chicken.", pic: "🍚", pos: "n", ipa: "/raɪs/", cat: "Food" },
  { word: "green", meaning: "the colour of grass", example: "The leaves are green.", pic: "💚", pos: "adj", ipa: "/ɡriːn/", cat: "Routine" },
  { word: "yellow", meaning: "the colour of the sun", example: "The sun is yellow.", pic: "💛", pos: "adj", ipa: "/ˈjeləʊ/", cat: "Routine" },
  { word: "black", meaning: "the darkest colour", example: "I have a black bag.", pic: "🖤", pos: "adj", ipa: "/blæk/", cat: "Routine" },
  { word: "white", meaning: "the colour of snow", example: "The cat is white.", pic: "🤍", pos: "adj", ipa: "/waɪt/", cat: "Routine" },
  { word: "three", meaning: "the number 3", example: "I have three pencils.", pic: "3️⃣", pos: "num", ipa: "/θriː/", cat: "Routine" },
  { word: "four", meaning: "the number 4", example: "There are four chairs.", pic: "4️⃣", pos: "num", ipa: "/fɔː/", cat: "Routine" },
  { word: "five", meaning: "the number 5", example: "I have five fingers.", pic: "5️⃣", pos: "num", ipa: "/faɪv/", cat: "Routine" },
  { word: "six", meaning: "the number 6", example: "The dog is six years old.", pic: "6️⃣", pos: "num", ipa: "/sɪks/", cat: "Routine" },
  { word: "seven", meaning: "the number 7", example: "I get up at seven.", pic: "7️⃣", pos: "num", ipa: "/ˈsevn/", cat: "Routine" },
  { word: "eight", meaning: "the number 8", example: "She has eight books.", pic: "8️⃣", pos: "num", ipa: "/eɪt/", cat: "Routine" },
  { word: "nine", meaning: "the number 9", example: "The bus is at nine.", pic: "9️⃣", pos: "num", ipa: "/naɪn/", cat: "Routine" },
  { word: "ten", meaning: "the number 10", example: "I can count to ten.", pic: "🔟", pos: "num", ipa: "/ten/", cat: "Routine" },
  { word: "sit", meaning: "to rest on a chair", example: "Please sit down.", pic: "🪑", pos: "v", ipa: "/sɪt/", cat: "Routine" },
  { word: "stand", meaning: "to be on your feet", example: "Stand up, please.", pic: "🧍", pos: "v", ipa: "/stænd/", cat: "Routine" },
  { word: "jump", meaning: "to go up into the air", example: "The cat can jump high.", pic: "🦘", pos: "v", ipa: "/dʒʌmp/", cat: "Routine" },
  { word: "swim", meaning: "to move in water", example: "Fish swim in the sea.", pic: "🏊", pos: "v", ipa: "/swɪm/", cat: "Leisure" },
  { word: "sing", meaning: "to make music with your voice", example: "She sings a happy song.", pic: "🎤", pos: "v", ipa: "/sɪŋ/", cat: "Leisure" },
  { word: "dance", meaning: "to move your body to music", example: "We dance at the party.", pic: "💃", pos: "v", ipa: "/dɑːns/", cat: "Leisure" },
  { word: "read", meaning: "to look at words and understand them", example: "I read a book at night.", pic: "📖", pos: "v", ipa: "/riːd/", cat: "School" },
  { word: "write", meaning: "to make letters and words", example: "Write your name here.", pic: "✍️", pos: "v", ipa: "/raɪt/", cat: "School" },
  { word: "draw", meaning: "to make a picture with a pen", example: "The boy draws a house.", pic: "🎨", pos: "v", ipa: "/drɔː/", cat: "School" },
  { word: "listen", meaning: "to hear and pay attention", example: "Listen to the teacher.", pic: "👂", pos: "v", ipa: "/ˈlɪsn/", cat: "School" },
  { word: "watch", meaning: "to look at something for a time", example: "We watch TV in the evening.", pic: "📺", pos: "v", ipa: "/wɒtʃ/", cat: "Leisure" },
  { word: "look", meaning: "to turn your eyes to see something", example: "Look at the blackboard.", pic: "👀", pos: "v", ipa: "/lʊk/", cat: "Routine" },
  { word: "see", meaning: "to notice with your eyes", example: "I can see a bird.", pic: "👀", pos: "v", ipa: "/siː/", cat: "Routine" },
  { word: "give", meaning: "to put something in someone's hand", example: "Give me the book, please.", pic: "🤲", pos: "v", ipa: "/ɡɪv/", cat: "Routine" },
  { word: "take", meaning: "to get something in your hand", example: "Take your bag and go.", pic: "🤲", pos: "v", ipa: "/teɪk/", cat: "Routine" },
  { word: "open", meaning: "to move a door or window so it is not closed", example: "Open the window, please.", pic: "🚪", pos: "v", ipa: "/ˈəʊpən/", cat: "Routine" },
  { word: "close", meaning: "to move a door so it is not open", example: "Close the door, please.", pic: "🚪", pos: "v", ipa: "/kləʊz/", cat: "Routine" },
  { word: "come", meaning: "to move towards someone", example: "Come here, please.", pic: "🏃", pos: "v", ipa: "/kʌm/", cat: "Routine" },
  { word: "go", meaning: "to move from one place to another", example: "I go to school by bus.", pic: "🏃", pos: "v", ipa: "/ɡəʊ/", cat: "Routine" },
  { word: "help", meaning: "to do something useful for someone", example: "Can you help me, please?", pic: "🤝", pos: "v", ipa: "/help/", cat: "Routine" },
  { word: "like", meaning: "to enjoy something", example: "I like ice cream.", pic: "😊", pos: "v", ipa: "/laɪk/", cat: "Talk" },
  { word: "love", meaning: "to like someone very much", example: "I love my family.", pic: "❤️", pos: "v", ipa: "/lʌv/", cat: "Talk" },
  { word: "want", meaning: "to wish to have something", example: "I want a new toy.", pic: "💭", pos: "v", ipa: "/wɒnt/", cat: "Talk" },
  { word: "have", meaning: "to own something", example: "I have a blue pen.", pic: "✋", pos: "v", ipa: "/hæv/", cat: "Routine" },
  { word: "wash", meaning: "to make something clean with water", example: "Wash your hands before eating.", pic: "🧼", pos: "v", ipa: "/wɒʃ/", cat: "Routine" },
  { word: "clean", meaning: "to make something not dirty", example: "I clean my room on Saturday.", pic: "🧹", pos: "v", ipa: "/kliːn/", cat: "Home" },
  { word: "cook", meaning: "to make food hot and ready to eat", example: "Mum cooks dinner at six.", pic: "🍳", pos: "v", ipa: "/kʊk/", cat: "Food" },
  { word: "buy", meaning: "to get something with money", example: "I buy bread at the shop.", pic: "🛒", pos: "v", ipa: "/baɪ/", cat: "Shopping" },
  { word: "wear", meaning: "to have clothes on your body", example: "I wear a red shirt.", pic: "👕", pos: "v", ipa: "/weə/", cat: "Routine" },
  { word: "good", meaning: "nice or of high quality", example: "This is a good book.", pic: "👍", pos: "adj", ipa: "/ɡʊd/", cat: "Talk" },
  { word: "bad", meaning: "not good", example: "The weather is bad today.", pic: "👎", pos: "adj", ipa: "/bæd/", cat: "Talk" },
  { word: "hot", meaning: "having a high temperature", example: "The soup is very hot.", pic: "🌡️", pos: "adj", ipa: "/hɒt/", cat: "Routine" },
  { word: "cold", meaning: "having a low temperature", example: "The water is cold.", pic: "🧊", pos: "adj", ipa: "/kəʊld/", cat: "Routine" },
  { word: "new", meaning: "not old; made recently", example: "I have a new bike.", pic: "✨", pos: "adj", ipa: "/njuː/", cat: "Talk" },
  { word: "old", meaning: "having lived or existed for many years", example: "My grandfather is old.", pic: "👴", pos: "adj", ipa: "/əʊld/", cat: "Talk" },
  { word: "young", meaning: "having lived for a short time", example: "She is young and happy.", pic: "👶", pos: "adj", ipa: "/jʌŋ/", cat: "People" },
  { word: "tall", meaning: "having great height", example: "The basketball player is tall.", pic: "📏", pos: "adj", ipa: "/tɔːl/", cat: "People" },
  { word: "short", meaning: "not long or tall", example: "The pencil is short.", pic: "✏️", pos: "adj", ipa: "/ʃɔːt/", cat: "Talk" },
  { word: "long", meaning: "measuring a great distance", example: "The river is very long.", pic: "📏", pos: "adj", ipa: "/lɒŋ/", cat: "Nature" },
  { word: "fast", meaning: "moving quickly", example: "The car is very fast.", pic: "🏎️", pos: "adj", ipa: "/fɑːst/", cat: "Travel" },
  { word: "slow", meaning: "not fast", example: "The turtle is slow.", pic: "🐢", pos: "adj", ipa: "/sləʊ/", cat: "Nature" },
  { word: "dirty", meaning: "not clean", example: "My shoes are dirty.", pic: "🩴", pos: "adj", ipa: "/ˈdɜːti/", cat: "Home" },
  { word: "full", meaning: "with no space left inside", example: "The glass is full of milk.", pic: "🥛", pos: "adj", ipa: "/fʊl/", cat: "Food" },
  { word: "empty", meaning: "with nothing inside", example: "The box is empty.", pic: "📦", pos: "adj", ipa: "/ˈempti/", cat: "Home" },
  { word: "quiet", meaning: "with little or no noise", example: "The library is quiet.", pic: "🤫", pos: "adj", ipa: "/ˈkwaɪət/", cat: "School" },
  { word: "easy", meaning: "not difficult", example: "This game is easy.", pic: "😌", pos: "adj", ipa: "/ˈiːzi/", cat: "School" },
  { word: "nice", meaning: "pleasant and kind", example: "She is a nice teacher.", pic: "😊", pos: "adj", ipa: "/naɪs/", cat: "People" },
  { word: "kind", meaning: "caring and friendly", example: "It is kind of you to help.", pic: "💖", pos: "adj", ipa: "/kaɪnd/", cat: "People" },
  { word: "funny", meaning: "making you laugh", example: "He tells funny jokes.", pic: "😄", pos: "adj", ipa: "/ˈfʌni/", cat: "Leisure" },
  { word: "head", meaning: "the top part of your body", example: "Put your hat on your head.", pic: "🙂", pos: "n", ipa: "/hed/", cat: "Health" },
  { word: "hand", meaning: "the part at the end of your arm", example: "Wash your hands, please.", pic: "✋", pos: "n", ipa: "/hænd/", cat: "Health" },
  { word: "foot", meaning: "the part at the end of your leg", example: "My foot hurts.", pic: "🦶", pos: "n", ipa: "/fʊt/", cat: "Health" },
  { word: "eye", meaning: "the part of your face you see with", example: "She has blue eyes.", pic: "👁️", pos: "n", ipa: "/aɪ/", cat: "Health" },
  { word: "ear", meaning: "the part of your head you hear with", example: "The rabbit has long ears.", pic: "👂", pos: "n", ipa: "/ɪə/", cat: "Health" },
  { word: "nose", meaning: "the part of your face you smell with", example: "The dog has a black nose.", pic: "👃", pos: "n", ipa: "/nəʊz/", cat: "Health" },
  { word: "mouth", meaning: "the part of your face you eat with", example: "Open your mouth, please.", pic: "👄", pos: "n", ipa: "/maʊθ/", cat: "Health" },
  { word: "hair", meaning: "the thin things that grow on your head", example: "Her hair is long and brown.", pic: "💇", pos: "n", ipa: "/heə/", cat: "Health" },
  { word: "shirt", meaning: "a piece of clothing for the top of your body", example: "He wears a white shirt.", pic: "👕", pos: "n", ipa: "/ʃɜːt/", cat: "Shopping" },
  { word: "shoe", meaning: "a thing you wear on your foot", example: "These shoes are new.", pic: "👟", pos: "n", ipa: "/ʃuː/", cat: "Shopping" },
  { word: "hat", meaning: "a thing you wear on your head", example: "She wears a hat in the sun.", pic: "🎩", pos: "n", ipa: "/hæt/", cat: "Shopping" },
  { word: "bag", meaning: "a thing you carry things in", example: "My bag is on the chair.", pic: "👜", pos: "n", ipa: "/bæɡ/", cat: "Shopping" },
  { word: "bike", meaning: "a vehicle with two wheels you pedal", example: "I ride my bike to the park.", pic: "🚲", pos: "n", ipa: "/baɪk/", cat: "Travel" },
  { word: "bus", meaning: "a big vehicle that carries many people", example: "The bus is late today.", pic: "🚌", pos: "n", ipa: "/bʌs/", cat: "Travel" },
  { word: "train", meaning: "a long vehicle that runs on tracks", example: "We go by train to the city.", pic: "🚆", pos: "n", ipa: "/treɪn/", cat: "Travel" },
  { word: "plane", meaning: "a vehicle that flies in the sky", example: "The plane is very high.", pic: "✈️", pos: "n", ipa: "/pleɪn/", cat: "Travel" },
  { word: "boat", meaning: "a small vehicle for water", example: "The boat is on the lake.", pic: "⛵", pos: "n", ipa: "/bəʊt/", cat: "Travel" },
  { word: "sun", meaning: "the bright thing in the sky in the day", example: "The sun is hot today.", pic: "☀️", pos: "n", ipa: "/sʌn/", cat: "Nature" },
  { word: "moon", meaning: "the bright thing in the sky at night", example: "The moon is round tonight.", pic: "🌙", pos: "n", ipa: "/muːn/", cat: "Nature" },
  { word: "star", meaning: "a small bright light in the night sky", example: "I see many stars at night.", pic: "⭐", pos: "n", ipa: "/stɑː/", cat: "Nature" },
  { word: "rain", meaning: "water that falls from the sky", example: "The rain is heavy today.", pic: "🌧️", pos: "n", ipa: "/reɪn/", cat: "Nature" },
  { word: "snow", meaning: "white soft water that falls from the sky in winter", example: "The snow is white and cold.", pic: "❄️", pos: "n", ipa: "/snəʊ/", cat: "Nature" },
  { word: "sea", meaning: "the big salt water that covers the earth", example: "We swim in the sea.", pic: "🌊", pos: "n", ipa: "/siː/", cat: "Nature" },
  { word: "river", meaning: "a long line of water", example: "The river is near my house.", pic: "🏞️", pos: "n", ipa: "/ˈrɪvə/", cat: "Nature" },
  { word: "hill", meaning: "an area of land higher than the land around it", example: "We walk up the hill.", pic: "⛰️", pos: "n", ipa: "/hɪl/", cat: "Nature" },
  { word: "park", meaning: "a green place in a town for people to play", example: "The children play in the park.", pic: "🌳", pos: "n", ipa: "/pɑːk/", cat: "Leisure" },
  { word: "zoo", meaning: "a place where animals live for people to see", example: "We see lions at the zoo.", pic: "🦁", pos: "n", ipa: "/zuː/", cat: "Leisure" },
  { word: "phone", meaning: "a thing you use to talk to people far away", example: "I call my friend on the phone.", pic: "📱", pos: "n", ipa: "/fəʊn/", cat: "Tech" },
  { word: "clock", meaning: "a thing that shows the time", example: "The clock says three o'clock.", pic: "🕒", pos: "n", ipa: "/klɒk/", cat: "Home" }
];
window.LF_VOCAB_EXTRA["A1"] = [
  { word: "apartment", meaning: "a set of rooms for living in a building", example: "They live in a small apartment.", pic: "🏢", pos: "n", ipa: "/əˈpɑːtmənt/", cat: "Home" },
  { word: "bathroom", meaning: "a room with a bath or shower", example: "The bathroom is next to my room.", pic: "🛁", pos: "n", ipa: "/ˈbɑːθruːm/", cat: "Home" },
  { word: "kitchen", meaning: "a room where you cook food", example: "Mum is in the kitchen.", pic: "🍳", pos: "n", ipa: "/ˈkɪtʃɪn/", cat: "Home" },
  { word: "fridge", meaning: "a machine that keeps food cold", example: "Put the milk in the fridge.", pic: "🧊", pos: "n", ipa: "/frɪdʒ/", cat: "Home" },
  { word: "cup", meaning: "a small container for drinking tea or coffee", example: "I drink tea from a cup.", pic: "☕", pos: "n", ipa: "/kʌp/", cat: "Food" },
  { word: "glass", meaning: "a container for drinking, made of glass", example: "A glass of water, please.", pic: "🥛", pos: "n", ipa: "/ɡlɑːs/", cat: "Food" },
  { word: "plate", meaning: "a flat dish for food", example: "The plate is full of rice.", pic: "🍽️", pos: "n", ipa: "/pleɪt/", cat: "Food" },
  { word: "knife", meaning: "a sharp thing for cutting food", example: "Cut the bread with a knife.", pic: "🔪", pos: "n", ipa: "/naɪf/", cat: "Food" },
  { word: "fork", meaning: "a thing with points for eating", example: "She eats salad with a fork.", pic: "🍴", pos: "n", ipa: "/fɔːk/", cat: "Food" },
  { word: "spoon", meaning: "a thing with a bowl shape for eating soup", example: "I eat soup with a spoon.", pic: "🥄", pos: "n", ipa: "/spuːn/", cat: "Food" },
  { word: "bottle", meaning: "a container for liquid", example: "This bottle is full of water.", pic: "🍾", pos: "n", ipa: "/ˈbɒtl/", cat: "Food" },
  { word: "chicken", meaning: "a bird people eat; its meat", example: "We have chicken for dinner.", pic: "🍗", pos: "n", ipa: "/ˈtʃɪkɪn/", cat: "Food" },
  { word: "meat", meaning: "the part of an animal people eat", example: "He does not eat meat.", pic: "🥩", pos: "n", ipa: "/miːt/", cat: "Food" },
  { word: "soup", meaning: "hot liquid food with vegetables or meat", example: "This soup is very good.", pic: "🍲", pos: "n", ipa: "/suːp/", cat: "Food" },
  { word: "cake", meaning: "a sweet food made from flour and sugar", example: "We eat cake at the party.", pic: "🍰", pos: "n", ipa: "/keɪk/", cat: "Food" },
  { word: "ice cream", meaning: "a cold sweet food", example: "I want ice cream in summer.", pic: "🍦", pos: "n", ipa: "/ˌaɪs ˈkriːm/", cat: "Food" },
  { word: "sandwich", meaning: "bread with food between two slices", example: "I have a sandwich for lunch.", pic: "🥪", pos: "n", ipa: "/ˈsænwɪtʃ/", cat: "Food" },
  { word: "salad", meaning: "a cold food with vegetables", example: "The salad has tomatoes.", pic: "🥗", pos: "n", ipa: "/ˈsæləd/", cat: "Food" },
  { word: "butter", meaning: "yellow food made from milk for bread", example: "I put butter on my bread.", pic: "🧈", pos: "n", ipa: "/ˈbʌtə/", cat: "Food" },
  { word: "clothes", meaning: "the things you wear", example: "These clothes are for winter.", pic: "👗", pos: "n", ipa: "/kləʊðz/", cat: "Shopping" },
  { word: "dress", meaning: "a piece of clothing for a woman or girl", example: "She wears a long dress.", pic: "👗", pos: "n", ipa: "/dres/", cat: "Shopping" },
  { word: "skirt", meaning: "a piece of clothing from the waist down for women", example: "Her skirt is blue.", pic: "👗", pos: "n", ipa: "/skɜːt/", cat: "Shopping" },
  { word: "trousers", meaning: "a piece of clothing for your legs", example: "These trousers are too long.", pic: "👖", pos: "n", ipa: "/ˈtraʊzəz/", cat: "Shopping" },
  { word: "jacket", meaning: "a short coat", example: "Put on your jacket, it is cold.", pic: "🧥", pos: "n", ipa: "/ˈdʒækɪt/", cat: "Shopping" },
  { word: "scarf", meaning: "a long thing you wear around your neck", example: "I wear a scarf in winter.", pic: "🧣", pos: "n", ipa: "/skɑːf/", cat: "Shopping" },
  { word: "gloves", meaning: "things you wear on your hands", example: "These gloves keep my hands warm.", pic: "🧤", pos: "n", ipa: "/ɡlʌvz/", cat: "Shopping" },
  { word: "socks", meaning: "things you wear on your feet inside shoes", example: "My socks are white.", pic: "🧦", pos: "n", ipa: "/sɒks/", cat: "Shopping" },
  { word: "wallet", meaning: "a small thing for money and cards", example: "My wallet is in my bag.", pic: "👛", pos: "n", ipa: "/ˈwɒlɪt/", cat: "Shopping" },
  { word: "map", meaning: "a drawing of a place", example: "Look at the map to find the station.", pic: "🗺️", pos: "n", ipa: "/mæp/", cat: "Travel" },
  { word: "museum", meaning: "a place where you see old and important things", example: "The museum has old paintings.", pic: "🏛️", pos: "n", ipa: "/mjuˈziːəm/", cat: "Culture" },
  { word: "theatre", meaning: "a place where you watch plays", example: "We watch a play at the theatre.", pic: "🎭", pos: "n", ipa: "/ˈθɪətə/", cat: "Culture" },
  { word: "cinema", meaning: "a place where you watch films", example: "Let's go to the cinema tonight.", pic: "🎬", pos: "n", ipa: "/ˈsɪnəmə/", cat: "Leisure" },
  { word: "village", meaning: "a small place in the country", example: "My grandmother lives in a village.", pic: "🏘️", pos: "n", ipa: "/ˈvɪlɪdʒ/", cat: "Travel" },
  { word: "town", meaning: "a place with many houses and shops", example: "The town is not very big.", pic: "🏘️", pos: "n", ipa: "/taʊn/", cat: "Travel" },
  { word: "corner", meaning: "the place where two walls or roads meet", example: "The shop is on the corner.", pic: "↩️", pos: "n", ipa: "/ˈkɔːnə/", cat: "Travel" },
  { word: "left", meaning: "the side that is not right", example: "Turn left at the bank.", pic: "⬅️", pos: "n", ipa: "/left/", cat: "Travel" },
  { word: "right", meaning: "the side that is not left", example: "The school is on the right.", pic: "➡️", pos: "n", ipa: "/raɪt/", cat: "Travel" },
  { word: "season", meaning: "one of the four parts of the year", example: "Winter is my favourite season.", pic: "🍂", pos: "n", ipa: "/ˈsiːzn/", cat: "Routine" },
  { word: "spring", meaning: "the season when flowers start to grow", example: "It is warm in spring.", pic: "🌱", pos: "n", ipa: "/sprɪŋ/", cat: "Nature" },
  { word: "summer", meaning: "the hottest season of the year", example: "We go to the beach in summer.", pic: "☀️", pos: "n", ipa: "/ˈsʌmə/", cat: "Nature" },
  { word: "autumn", meaning: "the season between summer and winter", example: "The leaves fall in autumn.", pic: "🍁", pos: "n", ipa: "/ˈɔːtəm/", cat: "Nature" },
  { word: "winter", meaning: "the coldest season of the year", example: "It snows in winter.", pic: "❄️", pos: "n", ipa: "/ˈwɪntə/", cat: "Nature" },
  { word: "talk", meaning: "to speak to someone", example: "Let's talk about your holiday.", pic: "💬", pos: "v", ipa: "/tɔːk/", cat: "Talk" },
  { word: "ask", meaning: "to say a question", example: "Ask the teacher for help.", pic: "❓", pos: "v", ipa: "/ɑːsk/", cat: "Talk" },
  { word: "answer", meaning: "to say something after a question", example: "Answer the question, please.", pic: "💬", pos: "v", ipa: "/ˈɑːnsə/", cat: "Talk" },
  { word: "say", meaning: "to speak words", example: "Say 'hello' to your teacher.", pic: "🗣️", pos: "v", ipa: "/seɪ/", cat: "Talk" },
  { word: "tell", meaning: "to say something to someone", example: "Tell me a story, please.", pic: "📖", pos: "v", ipa: "/tel/", cat: "Talk" },
  { word: "meet", meaning: "to see someone for the first time or by plan", example: "I meet my friends after school.", pic: "🤝", pos: "v", ipa: "/miːt/", cat: "People" },
  { word: "visit", meaning: "to go to see a person or a place", example: "We visit my aunt on Sundays.", pic: "🚪", pos: "v", ipa: "/ˈvɪzɪt/", cat: "Travel" },
  { word: "travel", meaning: "to go from one place to another", example: "They travel to Italy every year.", pic: "✈️", pos: "v", ipa: "/ˈtrævl/", cat: "Travel" },
  { word: "drive", meaning: "to make a car move", example: "My dad drives to work.", pic: "🚗", pos: "v", ipa: "/draɪv/", cat: "Travel" },
  { word: "fly", meaning: "to move in the air", example: "Birds fly in the sky.", pic: "🦅", pos: "v", ipa: "/flaɪ/", cat: "Nature" },
  { word: "ride", meaning: "to sit on a bike or horse and move", example: "I can ride a bike now.", pic: "🚲", pos: "v", ipa: "/raɪd/", cat: "Leisure" },
  { word: "leave", meaning: "to go away from a place", example: "The bus leaves at eight.", pic: "🚌", pos: "v", ipa: "/liːv/", cat: "Travel" },
  { word: "wait", meaning: "to stay until something happens", example: "Wait for me at the door.", pic: "⏳", pos: "v", ipa: "/weɪt/", cat: "Routine" },
  { word: "finish", meaning: "to come to the end of something", example: "I finish my homework at six.", pic: "🏁", pos: "v", ipa: "/ˈfɪnɪʃ/", cat: "School" },
  { word: "begin", meaning: "to start", example: "The film begins at seven.", pic: "🎬", pos: "v", ipa: "/bɪˈɡɪn/", cat: "Routine" },
  { word: "send", meaning: "to make something go to another person", example: "I send a card to my friend.", pic: "📨", pos: "v", ipa: "/send/", cat: "Tech" },
  { word: "receive", meaning: "to get something that someone sends", example: "Did you receive my message?", pic: "📥", pos: "v", ipa: "/rɪˈsiːv/", cat: "Tech" },
  { word: "call", meaning: "to phone someone", example: "Call me after dinner.", pic: "📞", pos: "v", ipa: "/kɔːl/", cat: "Tech" },
  { word: "cheap", meaning: "not costing much money", example: "The tickets are very cheap.", pic: "💸", pos: "adj", ipa: "/tʃiːp/", cat: "Shopping" },
  { word: "free", meaning: "with no cost", example: "The museum is free on Monday.", pic: "🆓", pos: "adj", ipa: "/friː/", cat: "Shopping" },
  { word: "late", meaning: "after the right time", example: "The train is late again.", pic: "⏰", pos: "adj", ipa: "/leɪt/", cat: "Routine" },
  { word: "near", meaning: "not far", example: "The park is near my house.", pic: "📍", pos: "adj", ipa: "/nɪə/", cat: "Travel" },
  { word: "far", meaning: "a long distance away", example: "The beach is far from here.", pic: "🗺️", pos: "adj", ipa: "/fɑː/", cat: "Travel" },
  { word: "famous", meaning: "known by many people", example: "She is a famous singer.", pic: "🌟", pos: "adj", ipa: "/ˈfeɪməs/", cat: "People" },
  { word: "friendly", meaning: "kind and nice to people", example: "The people here are very friendly.", pic: "😊", pos: "adj", ipa: "/ˈfrendli/", cat: "People" },
  { word: "noisy", meaning: "full of loud sound", example: "The street is noisy at night.", pic: "📢", pos: "adj", ipa: "/ˈnɔɪzi/", cat: "Routine" },
  { word: "safe", meaning: "with no danger", example: "This is a safe place to swim.", pic: "🛡️", pos: "adj", ipa: "/seɪf/", cat: "Health" },
  { word: "difficult", meaning: "not easy", example: "The test is very difficult.", pic: "😰", pos: "adj", ipa: "/ˈdɪfɪkəlt/", cat: "School" },
  { word: "boring", meaning: "not interesting", example: "The film is boring.", pic: "😴", pos: "adj", ipa: "/ˈbɔːrɪŋ/", cat: "Leisure" },
  { word: "exciting", meaning: "making you feel full of energy and interest", example: "The football match is exciting.", pic: "🤩", pos: "adj", ipa: "/ɪkˈsaɪtɪŋ/", cat: "Leisure" },
  { word: "interesting", meaning: "making you want to know more", example: "This book is very interesting.", pic: "🧐", pos: "adj", ipa: "/ˈɪntrəstɪŋ/", cat: "School" },
  { word: "favourite", meaning: "liked more than all others", example: "Blue is my favourite colour.", pic: "❤️", pos: "adj", ipa: "/ˈfeɪvərɪt/", cat: "Talk" },
  { word: "delicious", meaning: "very good to eat", example: "This pizza is delicious!", pic: "😋", pos: "adj", ipa: "/dɪˈlɪʃəs/", cat: "Food" },
  { word: "fresh", meaning: "new and not old", example: "I like fresh fruit.", pic: "🍏", pos: "adj", ipa: "/freʃ/", cat: "Food" },
  { word: "sweet", meaning: "tasting like sugar", example: "This cake is very sweet.", pic: "🍬", pos: "adj", ipa: "/swiːt/", cat: "Food" },
  { word: "dangerous", meaning: "with danger; not safe", example: "It is dangerous to swim here.", pic: "⚠️", pos: "adj", ipa: "/ˈdeɪndʒərəs/", cat: "Health" },
  { word: "clothes shop", meaning: "a shop that sells clothes", example: "She buys a dress at the clothes shop.", pic: "👗", pos: "n", ipa: "/ˈkləʊðz ʃɒp/", cat: "Shopping" },
  { word: "hospital", meaning: "a place where sick people get help", example: "The doctor works at the hospital.", pic: "🏥", pos: "n", ipa: "/ˈhɒspɪtl/", cat: "Health" },
  { word: "doctor", meaning: "a person who helps sick people", example: "The doctor is very kind.", pic: "👨‍⚕️", pos: "n", ipa: "/ˈdɒktə/", cat: "Health" },
  { word: "nurse", meaning: "a person who cares for sick people", example: "The nurse gives me medicine.", pic: "👩‍⚕️", pos: "n", ipa: "/nɜːs/", cat: "Health" },
  { word: "toothache", meaning: "pain in your tooth", example: "I have a toothache today.", pic: "🦷", pos: "n", ipa: "/ˈtuːθeɪk/", cat: "Health" },
  { word: "headache", meaning: "pain in your head", example: "I have a headache after the loud music.", pic: "🤕", pos: "n", ipa: "/ˈhedeɪk/", cat: "Health" },
  { word: "medicine", meaning: "a thing you take when you are sick", example: "Take this medicine after lunch.", pic: "💊", pos: "n", ipa: "/ˈmedsn/", cat: "Health" },
  { word: "exercise", meaning: "physical activity to stay healthy", example: "Exercise is good for you.", pic: "🏃", pos: "n", ipa: "/ˈeksəsaɪz/", cat: "Health" },
  { word: "mirror", meaning: "a glass where you can see yourself", example: "She looks in the mirror.", pic: "🪞", pos: "n", ipa: "/ˈmɪrə/", cat: "Home" },
  { word: "shower", meaning: "a place where you wash your body under water", example: "I take a shower in the morning.", pic: "🚿", pos: "n", ipa: "/ˈʃaʊə/", cat: "Home" },
  { word: "towel", meaning: "a cloth for drying your body", example: "My towel is wet.", pic: "🧻", pos: "n", ipa: "/ˈtaʊəl/", cat: "Home" },
  { word: "soap", meaning: "a thing you use to wash with", example: "Wash your hands with soap.", pic: "🧼", pos: "n", ipa: "/səʊp/", cat: "Home" },
  { word: "brush", meaning: "a thing with hairs for cleaning or painting", example: "I use a brush for my hair.", pic: "🪥", pos: "n", ipa: "/brʌʃ/", cat: "Home" },
  { word: "camera", meaning: "a thing for taking photos", example: "She takes photos with her camera.", pic: "📷", pos: "n", ipa: "/ˈkæmrə/", cat: "Tech" },
  { word: "computer", meaning: "a machine for working on the internet", example: "I do my homework on the computer.", pic: "💻", pos: "n", ipa: "/kəmˈpjuːtə/", cat: "Tech" },
  { word: "keyboard", meaning: "the part of a computer with letters", example: "Type your name on the keyboard.", pic: "⌨️", pos: "n", ipa: "/ˈkiːbɔːd/", cat: "Tech" },
  { word: "mouse", meaning: "a small thing you move on a computer", example: "Move the mouse to the icon.", pic: "🖱️", pos: "n", ipa: "/maʊs/", cat: "Tech" },
  { word: "screen", meaning: "the flat part of a computer or TV", example: "The screen is too bright.", pic: "🖥️", pos: "n", ipa: "/skriːn/", cat: "Tech" },
  { word: "letter", meaning: "a message you write and send", example: "I write a letter to my cousin.", pic: "✉️", pos: "n", ipa: "/ˈletə/", cat: "Talk" },
  { word: "email", meaning: "a message you send on the internet", example: "Send me an email tonight.", pic: "📧", pos: "n", ipa: "/ˈiːmeɪl/", cat: "Tech" },
  { word: "world", meaning: "the earth with all its countries", example: "I want to travel around the world.", pic: "🌍", pos: "n", ipa: "/wɜːld/", cat: "Travel" },
  { word: "holiday", meaning: "a time when you do not work or study", example: "We go to the sea on holiday.", pic: "🏖️", pos: "n", ipa: "/ˈhɒlədeɪ/", cat: "Leisure" },
  { word: "party", meaning: "a meeting of people to have fun", example: "The party starts at eight.", pic: "🎉", pos: "n", ipa: "/ˈpɑːti/", cat: "Leisure" },
  { word: "game", meaning: "an activity you play with rules", example: "Let's play a game.", pic: "🎮", pos: "n", ipa: "/ɡeɪm/", cat: "Leisure" },
  { word: "music", meaning: "sounds that people sing or play", example: "I listen to music on the bus.", pic: "🎵", pos: "n", ipa: "/ˈmjuːzɪk/", cat: "Culture" },
  { word: "song", meaning: "words with music", example: "This is my favourite song.", pic: "🎶", pos: "n", ipa: "/sɒŋ/", cat: "Culture" },
  { word: "picture", meaning: "a drawing, painting or photo", example: "The picture is on the wall.", pic: "🖼️", pos: "n", ipa: "/ˈpɪktʃə/", cat: "Culture" },
  { word: "photo", meaning: "a picture you take with a camera", example: "This photo is from my holiday.", pic: "📸", pos: "n", ipa: "/ˈfəʊtəʊ/", cat: "Culture" },
  { word: "gift", meaning: "a present for someone", example: "This gift is for your birthday.", pic: "🎁", pos: "n", ipa: "/ɡɪft/", cat: "Shopping" },
  { word: "sweet (n)", meaning: "a small thing made of sugar", example: "The child eats a sweet.", pic: "🍬", pos: "n", ipa: "/swiːt/", cat: "Food" },
  { word: "vegetable", meaning: "a plant you eat, like a carrot", example: "Eat vegetables every day.", pic: "🥦", pos: "n", ipa: "/ˈvedʒtəbl/", cat: "Food" },
  { word: "fruit", meaning: "sweet food from plants, like apples", example: "Fruit is good for you.", pic: "🍎", pos: "n", ipa: "/fruːt/", cat: "Food" },
  { word: "lunchtime", meaning: "the time when you eat lunch", example: "See you at lunchtime.", pic: "🕛", pos: "n", ipa: "/ˈlʌntʃtaɪm/", cat: "Routine" },
  { word: "student (a1 alt)", meaning: "a person who studies at school or college", example: "She is a new student here.", pic: "🧑‍🎓", pos: "n", ipa: "/ˈstjuːdnt/", cat: "School" },
  { word: "always", meaning: "every time; at all times", example: "I always walk to school.", pic: "🔁", pos: "adv", ipa: "/ˈɔːlweɪz/", cat: "Routine" },
  { word: "often", meaning: "many times", example: "We often play football.", pic: "🔄", pos: "adv", ipa: "/ˈɒfn/", cat: "Routine" },
  { word: "never", meaning: "not at any time", example: "I never drink coffee at night.", pic: "🚫", pos: "adv", ipa: "/ˈnevə/", cat: "Routine" },
  { word: "now", meaning: "at this time", example: "We are at school now.", pic: "⏱️", pos: "adv", ipa: "/naʊ/", cat: "Routine" },
  { word: "today", meaning: "this day", example: "Today is Monday.", pic: "📅", pos: "adv", ipa: "/təˈdeɪ/", cat: "Routine" },
  { word: "tomorrow", meaning: "the day after today", example: "Tomorrow is my birthday.", pic: "📅", pos: "adv", ipa: "/təˈmɒrəʊ/", cat: "Routine" },
  { word: "yesterday", meaning: "the day before today", example: "Yesterday was very hot.", pic: "📅", pos: "adv", ipa: "/ˈjestədeɪ/", cat: "Routine" }
];
window.LF_VOCAB_EXTRA["A2"] = [
  { word: "advice", meaning: "an idea about what someone should do", example: "My teacher gives me good advice.", pic: "💡", pos: "n", ipa: "/ədˈvaɪs/", cat: "Talk" },
  { word: "agreement", meaning: "when people have the same opinion", example: "We have an agreement about the plan.", pic: "🤝", pos: "n", ipa: "/əˈɡriːmənt/", cat: "Talk" },
  { word: "argument", meaning: "a discussion where people do not agree", example: "They had an argument about money.", pic: "😠", pos: "n", ipa: "/ˈɑːɡjumənt/", cat: "Talk" },
  { word: "attention", meaning: "care and thought about something", example: "Pay attention to the teacher.", pic: "👀", pos: "n", ipa: "/əˈtenʃn/", cat: "School" },
  { word: "autumn (a2 alt)", meaning: "the season of leaves falling", example: "Autumn is my favourite season.", pic: "🍂", pos: "n", ipa: "/ˈɔːtəm/", cat: "Nature" },
  { word: "basket", meaning: "a container for carrying things", example: "Put the fruit in the basket.", pic: "🧺", pos: "n", ipa: "/ˈbɑːskɪt/", cat: "Home" },
  { word: "battery", meaning: "a thing that gives power to toys and phones", example: "The toy needs a new battery.", pic: "🔋", pos: "n", ipa: "/ˈbætri/", cat: "Tech" },
  { word: "belt", meaning: "a thing you wear around your waist", example: "This belt is brown.", pic: "🩹", pos: "n", ipa: "/belt/", cat: "Shopping" },
  { word: "blanket", meaning: "a warm thing you sleep under", example: "The blanket is soft.", pic: "🛏️", pos: "n", ipa: "/ˈblæŋkɪt/", cat: "Home" },
  { word: "boots", meaning: "shoes that cover your ankle", example: "I wear boots in the snow.", pic: "🥾", pos: "n", ipa: "/buːts/", cat: "Shopping" },
  { word: "bowl", meaning: "a round deep dish", example: "The soup is in a bowl.", pic: "🥣", pos: "n", ipa: "/bəʊl/", cat: "Food" },
  { word: "bridge", meaning: "a thing over a river for crossing", example: "The bridge is very old.", pic: "🌉", pos: "n", ipa: "/brɪdʒ/", cat: "Travel" },
  { word: "brilliant", meaning: "very clever or very good", example: "That is a brilliant idea!", pic: "💎", pos: "adj", ipa: "/ˈbrɪliənt/", cat: "Talk" },
  { word: "broke", meaning: "having no money", example: "I am broke this week.", pic: "💸", pos: "adj", ipa: "/brəʊk/", cat: "Shopping" },
  { word: "café", meaning: "a small restaurant for coffee and food", example: "We meet at the café at four.", pic: "☕", pos: "n", ipa: "/ˈkæfeɪ/", cat: "Food" },
  { word: "calendar", meaning: "a thing that shows the days and months", example: "Look at the calendar for the date.", pic: "📅", pos: "n", ipa: "/ˈkælɪndə/", cat: "Routine" },
  { word: "castle", meaning: "a big old building with walls", example: "The castle is on the hill.", pic: "🏰", pos: "n", ipa: "/ˈkɑːsl/", cat: "Travel" },
  { word: "cause", meaning: "the reason something happens", example: "The cause of the fire is not known.", pic: "🔍", pos: "n", ipa: "/kɔːz/", cat: "Talk" },
  { word: "celebrate", meaning: "to have a party for something good", example: "We celebrate my birthday in May.", pic: "🎉", pos: "v", ipa: "/ˈselɪbreɪt/", cat: "Leisure" },
  { word: "century", meaning: "a period of one hundred years", example: "This building is from the 19th century.", pic: "🏛️", pos: "n", ipa: "/ˈsentʃəri/", cat: "Culture" },
  { word: "certain", meaning: "sure about something", example: "I am certain the train is at nine.", pic: "✅", pos: "adj", ipa: "/ˈsɜːtn/", cat: "Talk" },
  { word: "chance", meaning: "a possibility or opportunity", example: "Give me a chance to explain.", pic: "🎲", pos: "n", ipa: "/tʃɑːns/", cat: "Goals" },
  { word: "choice", meaning: "the thing you choose", example: "This is a good choice.", pic: "🤔", pos: "n", ipa: "/tʃɔɪs/", cat: "Goals" },
  { word: "circle", meaning: "a round shape", example: "Draw a circle on the paper.", pic: "⭕", pos: "n", ipa: "/ˈsɜːkl/", cat: "School" },
  { word: "clever", meaning: "quick at learning and thinking", example: "She is a clever student.", pic: "🧠", pos: "adj", ipa: "/ˈklevə/", cat: "School" },
  { word: "climate", meaning: "the usual weather of a place", example: "The climate here is warm.", pic: "🌦️", pos: "n", ipa: "/ˈklaɪmət/", cat: "Environment" },
  { word: "collect", meaning: "to bring things together", example: "I collect old stamps.", pic: "🗃️", pos: "v", ipa: "/kəˈlekt/", cat: "Leisure" },
  { word: "college", meaning: "a place for study after school", example: "She studies art at college.", pic: "🎓", pos: "n", ipa: "/ˈkɒlɪdʒ/", cat: "School" },
  { word: "comfortable", meaning: "making you feel relaxed", example: "This chair is very comfortable.", pic: "🛋️", pos: "adj", ipa: "/ˈkʌmftəbl/", cat: "Home" },
  { word: "company", meaning: "a business that makes or sells things", example: "He works for a big company.", pic: "🏢", pos: "n", ipa: "/ˈkʌmpəni/", cat: "Work" },
  { word: "compare", meaning: "to look at how things are the same or different", example: "Compare the two photos.", pic: "⚖️", pos: "v", ipa: "/kəmˈpeə/", cat: "Talk" },
  { word: "complain", meaning: "to say you are not happy about something", example: "The customer complains about the food.", pic: "😤", pos: "v", ipa: "/kəmˈpleɪn/", cat: "Talk" },
  { word: "complete", meaning: "to finish something", example: "Complete the exercise on page five.", pic: "✔️", pos: "v", ipa: "/kəmˈpliːt/", cat: "School" },
  { word: "conversation", meaning: "a talk between people", example: "We have a conversation in English.", pic: "💬", pos: "n", ipa: "/ˌkɒnvəˈseɪʃn/", cat: "Talk" },
  { word: "cook (a2 alt)", meaning: "a person who makes food", example: "The cook makes great pasta.", pic: "👨‍🍳", pos: "n", ipa: "/kʊk/", cat: "Food" },
  { word: "correct", meaning: "right; with no mistakes", example: "Your answer is correct.", pic: "✅", pos: "adj", ipa: "/kəˈrekt/", cat: "School" },
  { word: "cost", meaning: "the money you pay for something", example: "The cost of the ticket is ten pounds.", pic: "💷", pos: "n", ipa: "/kɒst/", cat: "Shopping" },
  { word: "courage", meaning: "the strength to do something difficult", example: "It takes courage to speak in public.", pic: "🦁", pos: "n", ipa: "/ˈkʌrɪdʒ/", cat: "Goals" },
  { word: "course", meaning: "a set of lessons about a subject", example: "I take a course in English.", pic: "📚", pos: "n", ipa: "/kɔːs/", cat: "School" },
  { word: "cry", meaning: "to have water come from your eyes", example: "The baby starts to cry.", pic: "😢", pos: "v", ipa: "/kraɪ/", cat: "Emotions" },
  { word: "culture", meaning: "the way of life of a group of people", example: "I learn about Japanese culture.", pic: "🏯", pos: "n", ipa: "/ˈkʌltʃə/", cat: "Culture" },
  { word: "damage", meaning: "harm to something", example: "The storm did a lot of damage.", pic: "💥", pos: "n", ipa: "/ˈdæmɪdʒ/", cat: "Environment" },
  { word: "deliver", meaning: "to bring something to a place", example: "They deliver pizza to my home.", pic: "📦", pos: "v", ipa: "/dɪˈlɪvə/", cat: "Shopping" },
  { word: "describe", meaning: "to say what something is like", example: "Describe your room to me.", pic: "🗣️", pos: "v", ipa: "/dɪˈskraɪb/", cat: "Talk" },
  { word: "desert", meaning: "a very dry place with little rain", example: "It is very hot in the desert.", pic: "🏜️", pos: "n", ipa: "/ˈdezət/", cat: "Nature" },
  { word: "direction", meaning: "the way to go somewhere", example: "Which direction is the station?", pic: "🧭", pos: "n", ipa: "/dəˈrekʃn/", cat: "Travel" },
  { word: "discover", meaning: "to find something new", example: "We discover a new café today.", pic: "🔎", pos: "v", ipa: "/dɪˈskʌvə/", cat: "Science" },
  { word: "discussion", meaning: "a talk about something important", example: "We have a discussion about the film.", pic: "💬", pos: "n", ipa: "/dɪˈskʌʃn/", cat: "Talk" },
  { word: "double", meaning: "two times as much", example: "A double room for two people, please.", pic: "2️⃣", pos: "adj", ipa: "/ˈdʌbl/", cat: "Routine" },
  { word: "dream", meaning: "the pictures in your head when you sleep", example: "I have a strange dream last night.", pic: "💭", pos: "n", ipa: "/driːm/", cat: "Goals" },
  { word: "each", meaning: "every one of two or more", example: "Each student has a book.", pic: "🔢", pos: "det", ipa: "/iːtʃ/", cat: "School" },
  { word: "earn", meaning: "to get money for your work", example: "She earns a good salary.", pic: "💰", pos: "v", ipa: "/ɜːn/", cat: "Work" },
  { word: "earth", meaning: "the planet we live on", example: "The earth is round.", pic: "🌍", pos: "n", ipa: "/ɜːθ/", cat: "Environment" },
  { word: "education", meaning: "the teaching and learning of knowledge", example: "Education is important for children.", pic: "🎓", pos: "n", ipa: "/ˌedʒuˈkeɪʃn/", cat: "School" },
  { word: "electric", meaning: "using electricity", example: "This is an electric car.", pic: "⚡", pos: "adj", ipa: "/ɪˈlektrɪk/", cat: "Tech" },
  { word: "energy", meaning: "the power from electricity, food, or the sun", example: "Solar energy is clean.", pic: "⚡", pos: "n", ipa: "/ˈenədʒi/", cat: "Science" },
  { word: "enjoy", meaning: "to like doing something", example: "I enjoy reading books.", pic: "😃", pos: "v", ipa: "/ɪnˈdʒɔɪ/", cat: "Leisure" },
  { word: "enough", meaning: "as much as you need", example: "We have enough food for everyone.", pic: "🙆", pos: "det", ipa: "/ɪˈnʌf/", cat: "Talk" },
  { word: "entrance", meaning: "the place where you go in", example: "The entrance is on the right.", pic: "🚪", pos: "n", ipa: "/ˈentrəns/", cat: "Travel" },
  { word: "environment", meaning: "the natural world around us", example: "We must protect the environment.", pic: "🌿", pos: "n", ipa: "/ɪnˈvaɪrənmənt/", cat: "Environment" },
  { word: "equipment", meaning: "the things you need for an activity", example: "The gym has new equipment.", pic: "🏋️", pos: "n", ipa: "/ɪˈkwɪpmənt/", cat: "Health" },
  { word: "example", meaning: "a thing that shows how something works", example: "Give me an example of this word.", pic: "📝", pos: "n", ipa: "/ɪɡˈzɑːmpl/", cat: "School" },
  { word: "fact", meaning: "something that is true", example: "It is a fact that water is wet.", pic: "📌", pos: "n", ipa: "/fækt/", cat: "Talk" },
  { word: "fail", meaning: "to not succeed", example: "Do not be afraid to fail and try again.", pic: "❌", pos: "v", ipa: "/feɪl/", cat: "Goals" },
  { word: "fair", meaning: "right and good for everyone", example: "The teacher is always fair.", pic: "⚖️", pos: "adj", ipa: "/feə/", cat: "Talk" },
  { word: "favourite (a2 alt)", meaning: "the one you like most", example: "What is your favourite food?", pic: "💖", pos: "adj", ipa: "/ˈfeɪvərɪt/", cat: "Talk" },
  { word: "feed", meaning: "to give food to a person or animal", example: "I feed the cat every morning.", pic: "🍖", pos: "v", ipa: "/fiːd/", cat: "Routine" },
  { word: "fight", meaning: "to use your body against someone", example: "The boys fight over the ball.", pic: "🥊", pos: "v", ipa: "/faɪt/", cat: "People" },
  { word: "fill", meaning: "to make something full", example: "Fill the glass with water.", pic: "🫗", pos: "v", ipa: "/fɪl/", cat: "Home" },
  { word: "foreign", meaning: "from another country", example: "She speaks two foreign languages.", pic: "🌐", pos: "adj", ipa: "/ˈfɒrən/", cat: "Travel" },
  { word: "future", meaning: "the time that is coming", example: "In the future, cars will fly.", pic: "🔮", pos: "n", ipa: "/ˈfjuːtʃə/", cat: "Goals" },
  { word: "government", meaning: "the people who rule a country", example: "The government makes new laws.", pic: "🏛️", pos: "n", ipa: "/ˈɡʌvənmənt/", cat: "Culture" },
  { word: "guest", meaning: "a person who visits or stays with you", example: "We have a guest for dinner.", pic: "🧑‍🤝‍🧑", pos: "n", ipa: "/ɡest/", cat: "People" },
  { word: "health", meaning: "the state of your body", example: "Good food is good for your health.", pic: "💪", pos: "n", ipa: "/helθ/", cat: "Health" },
  { word: "heavy", meaning: "with a lot of weight", example: "This bag is very heavy.", pic: "🏋️", pos: "adj", ipa: "/ˈhevi/", cat: "Home" },
  { word: "honest", meaning: "always telling the truth", example: "She is honest with her friends.", pic: "🤝", pos: "adj", ipa: "/ˈɒnɪst/", cat: "People" },
  { word: "hope", meaning: "to want something good to happen", example: "I hope you feel better soon.", pic: "🙏", pos: "v", ipa: "/həʊp/", cat: "Goals" },
  { word: "hungry", meaning: "wanting to eat", example: "I am hungry after school.", pic: "🍽️", pos: "adj", ipa: "/ˈhʌŋɡri/", cat: "Health" },
  { word: "imagine", meaning: "to make a picture in your head", example: "Imagine a world without war.", pic: "💭", pos: "v", ipa: "/ɪˈmædʒɪn/", cat: "Goals" },
  { word: "important", meaning: "having great value or meaning", example: "This is an important day.", pic: "⭐", pos: "adj", ipa: "/ɪmˈpɔːtnt/", cat: "Talk" },
  { word: "information", meaning: "facts about something", example: "The website has useful information.", pic: "ℹ️", pos: "n", ipa: "/ˌɪnfəˈmeɪʃn/", cat: "Tech" },
  { word: "island", meaning: "land with water all around it", example: "We live on a small island.", pic: "🏝️", pos: "n", ipa: "/ˈaɪlənd/", cat: "Nature" },
  { word: "journey (a2 alt)", meaning: "a trip from one place to another", example: "The journey takes two hours.", pic: "🚗", pos: "n", ipa: "/ˈdʒɜːni/", cat: "Travel" },
  { word: "lake", meaning: "a big area of water with land around it", example: "We swim in the lake in summer.", pic: "🏞️", pos: "n", ipa: "/leɪk/", cat: "Nature" },
  { word: "language", meaning: "the words people speak in a country", example: "English is a world language.", pic: "🗣️", pos: "n", ipa: "/ˈlæŋɡwɪdʒ/", cat: "Talk" },
  { word: "laugh", meaning: "to make a sound when something is funny", example: "The children laugh at the joke.", pic: "😂", pos: "v", ipa: "/lɑːf/", cat: "Emotions" },
  { word: "library", meaning: "a place with many books to read", example: "I borrow books from the library.", pic: "📚", pos: "n", ipa: "/ˈlaɪbrəri/", cat: "School" },
  { word: "lose", meaning: "to not find something", example: "Do not lose your keys!", pic: "🔍", pos: "v", ipa: "/luːz/", cat: "Routine" },
  { word: "luck", meaning: "when good things happen by chance", example: "Good luck in your test!", pic: "🍀", pos: "n", ipa: "/lʌk/", cat: "Goals" },
  { word: "machine", meaning: "a thing with parts that does work", example: "The washing machine is new.", pic: "⚙️", pos: "n", ipa: "/məˈʃiːn/", cat: "Tech" },
  { word: "magazine", meaning: "a thin book with stories and photos", example: "She reads a fashion magazine.", pic: "📰", pos: "n", ipa: "/ˌmæɡəˈziːn/", cat: "Culture" },
  { word: "main", meaning: "the most important", example: "The main door is at the front.", pic: "🎯", pos: "adj", ipa: "/meɪn/", cat: "Talk" },
  { word: "measure", meaning: "to find the size or amount of something", example: "Measure the table with a ruler.", pic: "📏", pos: "v", ipa: "/ˈmeʒə/", cat: "School" },
  { word: "menu", meaning: "the list of food in a restaurant", example: "Can I see the menu, please?", pic: "📋", pos: "n", ipa: "/ˈmenjuː/", cat: "Food" },
  { word: "message (a2 alt)", meaning: "words you send to someone", example: "I leave a message for you.", pic: "💬", pos: "n", ipa: "/ˈmesɪdʒ/", cat: "Talk" },
  { word: "notice", meaning: "to see and become aware of something", example: "I notice a mistake in the text.", pic: "👁️", pos: "v", ipa: "/ˈnəʊtɪs/", cat: "Talk" },
  { word: "offer", meaning: "to say you will give or do something", example: "He offers to help me.", pic: "🙋", pos: "v", ipa: "/ˈɒfə/", cat: "Talk" },
  { word: "order", meaning: "to ask for food or goods", example: "We order pizza for dinner.", pic: "🛎️", pos: "v", ipa: "/ˈɔːdə/", cat: "Food" },
  { word: "owe", meaning: "to need to pay money to someone", example: "I owe you ten pounds.", pic: "💷", pos: "v", ipa: "/əʊ/", cat: "Shopping" },
  { word: "pack", meaning: "to put things in a bag or box", example: "Pack your clothes for the trip.", pic: "🧳", pos: "v", ipa: "/pæk/", cat: "Travel" },
  { word: "passenger", meaning: "a person travelling in a vehicle", example: "The bus has twenty passengers.", pic: "🚌", pos: "n", ipa: "/ˈpæsɪndʒə/", cat: "Travel" },
  { word: "pattern", meaning: "a design of lines or shapes that repeats", example: "The shirt has a nice pattern.", pic: "🔷", pos: "n", ipa: "/ˈpætn/", cat: "Culture" },
  { word: "perform", meaning: "to act, sing or dance for people", example: "The band performs on Friday.", pic: "🎤", pos: "v", ipa: "/pəˈfɔːm/", cat: "Leisure" },
  { word: "personality", meaning: "the kind of person you are", example: "She has a friendly personality.", pic: "🧑", pos: "n", ipa: "/ˌpɜːsəˈnæləti/", cat: "People" },
  { word: "pick", meaning: "to choose or take something", example: "Pick a card from the box.", pic: "🃏", pos: "v", ipa: "/pɪk/", cat: "Routine" },
  { word: "piece", meaning: "a part of something", example: "I want a piece of cake.", pic: "🍰", pos: "n", ipa: "/piːs/", cat: "Food" },
  { word: "planet", meaning: "a big thing that goes around the sun", example: "Mars is a red planet.", pic: "🪐", pos: "n", ipa: "/ˈplænɪt/", cat: "Science" },
  { word: "pollution", meaning: "dirt in the air, water or land", example: "Pollution is bad for our health.", pic: "🏭", pos: "n", ipa: "/pəˈluːʃn/", cat: "Environment" },
  { word: "population", meaning: "the number of people in a place", example: "The population of the city is big.", pic: "👥", pos: "n", ipa: "/ˌpɒpjuˈleɪʃn/", cat: "Culture" },
  { word: "possibility", meaning: "a chance that something can happen", example: "There is a possibility of rain.", pic: "🌧️", pos: "n", ipa: "/ˌpɒsəˈbɪləti/", cat: "Talk" },
  { word: "practical", meaning: "useful for real situations", example: "This course is very practical.", pic: "🛠️", pos: "adj", ipa: "/ˈpræktɪkl/", cat: "School" },
  { word: "predict", meaning: "to say what will happen", example: "Experts predict more rain.", pic: "🔮", pos: "v", ipa: "/prɪˈdɪkt/", cat: "Science" },
  { word: "prepare (a2 alt)", meaning: "to make something ready", example: "I prepare my bag for school.", pic: "🎒", pos: "v", ipa: "/prɪˈpeə/", cat: "Routine" },
  { word: "price", meaning: "the money you pay for something", example: "The price of the book is low.", pic: "🏷️", pos: "n", ipa: "/praɪs/", cat: "Shopping" },
  { word: "protect", meaning: "to keep someone or something safe", example: "We protect the animals in the park.", pic: "🛡️", pos: "v", ipa: "/prəˈtekt/", cat: "Environment" },
  { word: "public", meaning: "for all people", example: "The park is a public place.", pic: "🏞️", pos: "adj", ipa: "/ˈpʌblɪk/", cat: "Culture" },
  { word: "purpose", meaning: "the reason for doing something", example: "The purpose of the trip is to learn.", pic: "🎯", pos: "n", ipa: "/ˈpɜːpəs/", cat: "Goals" },
  { word: "refuse", meaning: "to say no to something", example: "He refuses to eat the soup.", pic: "🙅", pos: "v", ipa: "/rɪˈfjuːz/", cat: "Talk" },
  { word: "regret", meaning: "to feel sad about something you did", example: "I regret buying that phone.", pic: "😔", pos: "v", ipa: "/rɪˈɡret/", cat: "Emotions" },
  { word: "repeat", meaning: "to say or do something again", example: "Repeat the word after me.", pic: "🔁", pos: "v", ipa: "/rɪˈpiːt/", cat: "School" },
  { word: "report", meaning: "a piece of writing with information", example: "I write a report about my project.", pic: "📄", pos: "n", ipa: "/rɪˈpɔːt/", cat: "School" },
  { word: "responsible", meaning: "having the duty to care for something", example: "You are responsible for your homework.", pic: "🤝", pos: "adj", ipa: "/rɪˈspɒnsəbl/", cat: "Goals" },
  { word: "result", meaning: "the thing that happens because of something", example: "The result of the test is good.", pic: "🏆", pos: "n", ipa: "/rɪˈzʌlt/", cat: "School" },
  { word: "save", meaning: "to keep money or something for later", example: "I save money for a new bike.", pic: "🏦", pos: "v", ipa: "/seɪv/", cat: "Goals" },
  { word: "secret", meaning: "something only you know", example: "Keep it a secret, please.", pic: "🤫", pos: "n", ipa: "/ˈsiːkrət/", cat: "Talk" },
  { word: "share", meaning: "to use something with other people", example: "We share the pizza.", pic: "🤲", pos: "v", ipa: "/ʃeə/", cat: "People" },
  { word: "signal", meaning: "a light or sound that gives a message", example: "The green light is a signal to go.", pic: "🚦", pos: "n", ipa: "/ˈsɪɡnəl/", cat: "Travel" },
  { word: "silence", meaning: "no sound", example: "The classroom is in silence.", pic: "🤐", pos: "n", ipa: "/ˈsaɪləns/", cat: "School" },
  { word: "skill", meaning: "the ability to do something well", example: "Cooking is a useful skill.", pic: "🎯", pos: "n", ipa: "/skɪl/", cat: "Goals" },
  { word: "smell", meaning: "to notice something with your nose", example: "I smell fresh bread.", pic: "👃", pos: "v", ipa: "/smel/", cat: "Health" },
  { word: "society", meaning: "people living together in a place", example: "He helps the society with his ideas.", pic: "🏘️", pos: "n", ipa: "/səˈsaɪəti/", cat: "Culture" },
  { word: "spend", meaning: "to use money or time", example: "I spend my money on books.", pic: "💸", pos: "v", ipa: "/spend/", cat: "Shopping" },
  { word: "stadium", meaning: "a big place for sport", example: "The match is at the stadium.", pic: "🏟️", pos: "n", ipa: "/ˈsteɪdiəm/", cat: "Leisure" },
  { word: "strange", meaning: "unusual and surprising", example: "I hear a strange sound.", pic: "😲", pos: "adj", ipa: "/streɪndʒ/", cat: "Talk" },
  { word: "success", meaning: "when you do well at something", example: "Her success makes us proud.", pic: "🏅", pos: "n", ipa: "/səkˈses/", cat: "Goals" },
  { word: "suddenly", meaning: "quickly and without warning", example: "Suddenly, it starts to rain.", pic: "⚡", pos: "adv", ipa: "/ˈsʌdənli/", cat: "Routine" },
  { word: "suggest (a2 alt)", meaning: "to give an idea for someone", example: "I suggest we go by train.", pic: "💡", pos: "v", ipa: "/səˈdʒest/", cat: "Talk" },
  { word: "suppose", meaning: "to think something is true", example: "I suppose you are right.", pic: "🤔", pos: "v", ipa: "/səˈpəʊz/", cat: "Talk" },
  { word: "surprise", meaning: "an unexpected thing", example: "The party is a surprise for her.", pic: "🎁", pos: "n", ipa: "/səˈpraɪz/", cat: "Emotions" },
  { word: "taste", meaning: "the flavour of food", example: "The soup has a good taste.", pic: "👅", pos: "n", ipa: "/teɪst/", cat: "Food" },
  { word: "team", meaning: "a group of people who play or work together", example: "Our team wins the game.", pic: "👥", pos: "n", ipa: "/tiːm/", cat: "Leisure" },
  { word: "temperature", meaning: "how hot or cold something is", example: "The temperature is thirty degrees.", pic: "🌡️", pos: "n", ipa: "/ˈtemprətʃə/", cat: "Health" },
  { word: "thirsty", meaning: "wanting to drink", example: "I am thirsty after the run.", pic: "🥤", pos: "adj", ipa: "/ˈθɜːsti/", cat: "Health" },
  { word: "tourist", meaning: "a person who visits a place for holiday", example: "The city is full of tourists.", pic: "🧳", pos: "n", ipa: "/ˈtʊərɪst/", cat: "Travel" },
  { word: "traffic", meaning: "the cars and buses on the road", example: "The traffic is heavy today.", pic: "🚗", pos: "n", ipa: "/ˈtræfɪk/", cat: "Travel" },
  { word: "translate", meaning: "to change words from one language to another", example: "Translate this sentence to English.", pic: "🔤", pos: "v", ipa: "/trænzˈleɪt/", cat: "Talk" },
  { word: "truth", meaning: "the true facts", example: "Tell me the truth, please.", pic: "💯", pos: "n", ipa: "/truːθ/", cat: "Talk" },
  { word: "valuable", meaning: "worth a lot of money or very useful", example: "This ring is very valuable.", pic: "💎", pos: "adj", ipa: "/ˈvæljuəbl/", cat: "Shopping" },
  { word: "view", meaning: "what you can see from a place", example: "The view from the hill is beautiful.", pic: "🌄", pos: "n", ipa: "/vjuː/", cat: "Nature" },
  { word: "voice", meaning: "the sound you make when you speak", example: "She has a lovely voice.", pic: "🗣️", pos: "n", ipa: "/vɔɪs/", cat: "Talk" },
  { word: "win", meaning: "to be the best in a game or race", example: "Our team wins the match.", pic: "🏆", pos: "v", ipa: "/wɪn/", cat: "Leisure" },
  { word: "without", meaning: "not having something", example: "I drink tea without sugar.", pic: "🚫", pos: "prep", ipa: "/wɪˈðaʊt/", cat: "Food" },
  { word: "worry", meaning: "to feel bad about something", example: "Do not worry about the test.", pic: "😟", pos: "v", ipa: "/ˈwʌri/", cat: "Emotions" },
  { word: "wrong", meaning: "not right", example: "This answer is wrong.", pic: "❌", pos: "adj", ipa: "/rɒŋ/", cat: "School" }
];
