/* Lingua Forge Academy — Oxford-style vocabulary data
   Word lists arranged by CEFR level; each entry carries a picture (emoji),
   part of speech, phonemic transcription and topic category for visual learning.
   Keys kept for app compatibility: word · meaning · example (+ pic, pos, ipa, cat) */
window.LF_VOCAB = {
  "Pre-A1": [
    { word: "hello",   meaning: "a word you say when you meet someone", example: "Hello! My name is Sam.", pic: "👋", pos: "excl", ipa: "/həˈləʊ/", cat: "People" },
    { word: "name",    meaning: "the word people call you", example: "What is your name?", pic: "🏷️", pos: "n", ipa: "/neɪm/", cat: "People" },
    { word: "friend",  meaning: "a person you like and know well", example: "My friend is happy.", pic: "🧑‍🤝‍🧑", pos: "n", ipa: "/frend/", cat: "People" },
    { word: "mother",  meaning: "your mum", example: "My mother is at home.", pic: "👩", pos: "n", ipa: "/ˈmʌðə(r)/", cat: "Family" },
    { word: "father",  meaning: "your dad", example: "My father has a car.", pic: "👨", pos: "n", ipa: "/ˈfɑːðə(r)/", cat: "Family" },
    { word: "cat",     meaning: "a small animal that says 'meow'", example: "The cat is black.", pic: "🐱", pos: "n", ipa: "/kæt/", cat: "Nature" },
    { word: "dog",     meaning: "an animal that says 'woof'", example: "The dog is big.", pic: "🐶", pos: "n", ipa: "/dɒɡ/", cat: "Nature" },
    { word: "book",    meaning: "something you read", example: "I read a book.", pic: "📖", pos: "n", ipa: "/bʊk/", cat: "School" },
    { word: "pen",     meaning: "something you write with", example: "This is my pen.", pic: "🖊️", pos: "n", ipa: "/pen/", cat: "School" },
    { word: "school",  meaning: "a place where you learn", example: "I go to school.", pic: "🏫", pos: "n", ipa: "/skuːl/", cat: "School" },
    { word: "red",     meaning: "the colour of an apple", example: "My pen is red.", pic: "🔴", pos: "adj", ipa: "/red/", cat: "Routine" },
    { word: "blue",    meaning: "the colour of the sky", example: "The sky is blue.", pic: "🔵", pos: "adj", ipa: "/bluː/", cat: "Routine" },
    { word: "one",     meaning: "the number 1", example: "I have one cat.", pic: "1️⃣", pos: "n", ipa: "/wʌn/", cat: "Routine" },
    { word: "two",     meaning: "the number 2", example: "I have two hands.", pic: "2️⃣", pos: "n", ipa: "/tuː/", cat: "Routine" },
    { word: "happy",   meaning: "feeling good", example: "I am happy.", pic: "😊", pos: "adj", ipa: "/ˈhæpi/", cat: "People" },
    { word: "sad",     meaning: "feeling not good", example: "The film is sad.", pic: "😢", pos: "adj", ipa: "/sæd/", cat: "People" },
    { word: "big",     meaning: "large", example: "The elephant is big.", pic: "🐘", pos: "adj", ipa: "/bɪɡ/", cat: "Routine" },
    { word: "small",   meaning: "little", example: "The mouse is small.", pic: "🐭", pos: "adj", ipa: "/smɔːl/", cat: "Routine" },
    { word: "eat",     meaning: "to put food in your mouth", example: "I eat bread.", pic: "🍽️", pos: "v", ipa: "/iːt/", cat: "Food" },
    { word: "drink",   meaning: "to take water into your mouth", example: "I drink milk.", pic: "🥛", pos: "v", ipa: "/drɪŋk/", cat: "Food" },
    { word: "water",   meaning: "the clear liquid we drink", example: "The water is cold.", pic: "💧", pos: "n", ipa: "/ˈwɔːtə(r)/", cat: "Food" },
    { word: "apple",   meaning: "a round red or green fruit", example: "She eats an apple.", pic: "🍎", pos: "n", ipa: "/ˈæpl/", cat: "Food" },
    { word: "house",   meaning: "a building where people live", example: "My house is white.", pic: "🏠", pos: "n", ipa: "/haʊs/", cat: "Home" },
    { word: "car",     meaning: "a machine with four wheels that takes you places", example: "The car is fast.", pic: "🚗", pos: "n", ipa: "/kɑː(r)/", cat: "Travel" },
    { word: "run",     meaning: "to move very fast on your feet", example: "I run to school.", pic: "🏃", pos: "v", ipa: "/rʌn/", cat: "Routine" },
    { word: "walk",    meaning: "to move on your feet", example: "We walk to the park.", pic: "🚶", pos: "v", ipa: "/wɔːk/", cat: "Routine" },
    { word: "sleep",   meaning: "to rest with your eyes closed", example: "The baby sleeps.", pic: "😴", pos: "v", ipa: "/sliːp/", cat: "Routine" },
    { word: "play",    meaning: "to do something fun", example: "The children play.", pic: "🎈", pos: "v", ipa: "/pleɪ/", cat: "Leisure" },
    { word: "morning", meaning: "the early part of the day", example: "Good morning!", pic: "🌅", pos: "n", ipa: "/ˈmɔːnɪŋ/", cat: "Routine" },
    { word: "night",   meaning: "the dark part of the day", example: "Good night!", pic: "🌙", pos: "n", ipa: "/naɪt/", cat: "Routine" }
  ],
  "A1": [
    { word: "address",   meaning: "the number and street of your home", example: "Please write your address on the form.", pic: "📮", pos: "n", ipa: "/əˈdres/", cat: "Home" },
    { word: "age",       meaning: "how old you are", example: "My age is ten.", pic: "🎂", pos: "n", ipa: "/eɪdʒ/", cat: "People" },
    { word: "country",   meaning: "a land with its own people and rules, like Spain", example: "Japan is a big country.", pic: "🗺️", pos: "n", ipa: "/ˈkʌntri/", cat: "Travel" },
    { word: "city",      meaning: "a very big town", example: "London is a famous city.", pic: "🏙️", pos: "n", ipa: "/ˈsɪti/", cat: "Home" },
    { word: "family",    meaning: "your mother, father, brothers and sisters", example: "My family is small.", pic: "👨‍👩‍👧‍👦", pos: "n", ipa: "/ˈfæməli/", cat: "Family" },
    { word: "job",       meaning: "work that you do for money", example: "She has a new job.", pic: "💼", pos: "n", ipa: "/dʒɒb/", cat: "Work" },
    { word: "teacher",   meaning: "a person who helps you learn", example: "My teacher is kind.", pic: "👩‍🏫", pos: "n", ipa: "/ˈtiːtʃə(r)/", cat: "School" },
    { word: "student",   meaning: "a person who learns at school", example: "The student asks questions.", pic: "🧑‍🎓", pos: "n", ipa: "/ˈstjuːdnt/", cat: "School" },
    { word: "breakfast", meaning: "the first meal of the day", example: "I eat eggs for breakfast.", pic: "🍳", pos: "n", ipa: "/ˈbrekfəst/", cat: "Food" },
    { word: "lunch",     meaning: "the meal you eat in the middle of the day", example: "We have lunch at school.", pic: "🥪", pos: "n", ipa: "/lʌntʃ/", cat: "Food" },
    { word: "usually",   meaning: "most of the time", example: "I usually get up at seven.", pic: "⏰", pos: "adv", ipa: "/ˈjuːʒuəli/", cat: "Routine" },
    { word: "sometimes", meaning: "not every time, not never", example: "We sometimes go to the park.", pic: "🎲", pos: "adv", ipa: "/ˈsʌmtaɪmz/", cat: "Routine" },
    { word: "market",    meaning: "a place where people buy and sell things", example: "My mother buys fruit at the market.", pic: "🧺", pos: "n", ipa: "/ˈmɑːkɪt/", cat: "Shopping" },
    { word: "shop",      meaning: "a place where you buy things", example: "The shop opens at nine.", pic: "🛍️", pos: "n", ipa: "/ʃɒp/", cat: "Shopping" },
    { word: "ticket",    meaning: "a paper that lets you travel or enter", example: "I have a ticket for the train.", pic: "🎫", pos: "n", ipa: "/ˈtɪkɪt/", cat: "Travel" },
    { word: "weather",   meaning: "hot, cold, rain or sun outside", example: "The weather is nice today.", pic: "🌦️", pos: "n", ipa: "/ˈweðə(r)/", cat: "Nature" },
    { word: "weekend",   meaning: "Saturday and Sunday", example: "What do you do at the weekend?", pic: "🏖️", pos: "n", ipa: "/ˌwiːkˈend/", cat: "Leisure" },
    { word: "hobby",     meaning: "something you like doing in your free time", example: "My hobby is drawing.", pic: "🎨", pos: "n", ipa: "/ˈhɒbi/", cat: "Leisure" },
    { word: "beautiful", meaning: "very nice to look at", example: "What a beautiful garden!", pic: "🌸", pos: "adj", ipa: "/ˈbjuːtɪfl/", cat: "Routine" },
    { word: "expensive", meaning: "costing a lot of money", example: "This phone is expensive.", pic: "💸", pos: "adj", ipa: "/ɪkˈspensɪv/", cat: "Shopping" },
    { word: "healthy",   meaning: "good for your body", example: "Fruit is healthy food.", pic: "🥗", pos: "adj", ipa: "/ˈhelθi/", cat: "Food" },
    { word: "tired",     meaning: "wanting to sleep or rest", example: "I am tired after school.", pic: "😪", pos: "adj", ipa: "/ˈtaɪəd/", cat: "People" },
    { word: "hospital",  meaning: "a place where doctors help sick people", example: "The hospital is near the station.", pic: "🏥", pos: "n", ipa: "/ˈhɒspɪtl/", cat: "Home" },
    { word: "station",   meaning: "a place where trains stop", example: "Meet me at the station.", pic: "🚉", pos: "n", ipa: "/ˈsteɪʃn/", cat: "Travel" },
    { word: "airport",   meaning: "a place where planes take off and land", example: "We arrived at the airport early.", pic: "✈️", pos: "n", ipa: "/ˈeəpɔːt/", cat: "Travel" },
    { word: "beach",     meaning: "sand next to the sea", example: "The beach is full of shells.", pic: "🏖️", pos: "n", ipa: "/biːtʃ/", cat: "Nature" },
    { word: "mountain",  meaning: "a very high hill", example: "The mountain is covered in snow.", pic: "⛰️", pos: "n", ipa: "/ˈmaʊntən/", cat: "Nature" },
    { word: "money",     meaning: "coins and paper we use to buy things", example: "I need money for the ticket.", pic: "💰", pos: "n", ipa: "/ˈmʌni/", cat: "Shopping" },
    { word: "busy",      meaning: "having a lot to do", example: "She is busy today.", pic: "📅", pos: "adj", ipa: "/ˈbɪzi/", cat: "Routine" },
    { word: "early",     meaning: "before the usual time", example: "We arrived early.", pic: "🌄", pos: "adv", ipa: "/ˈɜːli/", cat: "Routine" }
  ],
  "A2": [
    { word: "appointment", meaning: "a time fixed to meet someone", example: "I have a dentist's appointment at three.", pic: "🗓️", pos: "n", ipa: "/əˈpɔɪntmənt/", cat: "Routine" },
    { word: "neighbour",   meaning: "a person who lives near you", example: "My neighbour is very friendly.", pic: "🏡", pos: "n", ipa: "/ˈneɪbə(r)/", cat: "Family" },
    { word: "journey",     meaning: "travelling from one place to another", example: "The journey to the coast takes two hours.", pic: "🧳", pos: "n", ipa: "/ˈdʒɜːni/", cat: "Travel" },
    { word: "crowded",     meaning: "full of people", example: "The train was crowded this morning.", pic: "🚇", pos: "adj", ipa: "/ˈkraʊdɪd/", cat: "Travel" },
    { word: "customer",    meaning: "a person who buys something", example: "The customer asked for a refund.", pic: "🧑‍💼", pos: "n", ipa: "/ˈkʌstəmə(r)/", cat: "Shopping" },
    { word: "recipe",      meaning: "instructions for cooking a dish", example: "This recipe uses fresh tomatoes.", pic: "📜", pos: "n", ipa: "/ˈresəpi/", cat: "Food" },
    { word: "habit",       meaning: "something you do often without thinking", example: "Reading before bed is a good habit.", pic: "🔁", pos: "n", ipa: "/ˈhæbɪt/", cat: "Routine" },
    { word: "message",     meaning: "a short piece of information for someone", example: "I left a message for the manager.", pic: "💬", pos: "n", ipa: "/ˈmesɪdʒ/", cat: "Talk" },
    { word: "invitation",  meaning: "a request to come to an event", example: "She sent me an invitation to her party.", pic: "💌", pos: "n", ipa: "/ˌɪnvɪˈteɪʃn/", cat: "Talk" },
    { word: "experience",  meaning: "knowledge gained by doing something", example: "He has teaching experience.", pic: "🎯", pos: "n", ipa: "/ɪkˈspɪəriəns/", cat: "Work" },
    { word: "comfortable", meaning: "feeling relaxed and at ease", example: "This chair is very comfortable.", pic: "🛋️", pos: "adj", ipa: "/ˈkʌmftəbl/", cat: "Home" },
    { word: "careful",     meaning: "giving attention to avoid mistakes or danger", example: "Be careful when you cross the road.", pic: "⚠️", pos: "adj", ipa: "/ˈkeəfl/", cat: "Routine" },
    { word: "decide",      meaning: "to choose after thinking", example: "We decided to travel by train.", pic: "🤔", pos: "v", ipa: "/dɪˈsaɪd/", cat: "Goals" },
    { word: "explain",     meaning: "to make something clear", example: "Can you explain the rules, please?", pic: "🗣️", pos: "v", ipa: "/ɪkˈspleɪn/", cat: "Talk" },
    { word: "improve",     meaning: "to make or become better", example: "I want to improve my speaking.", pic: "📈", pos: "v", ipa: "/ɪmˈpruːv/", cat: "Goals" },
    { word: "prepare",     meaning: "to get something ready", example: "She prepared dinner early.", pic: "🧑‍🍳", pos: "v", ipa: "/prɪˈpeə(r)/", cat: "Routine" },
    { word: "borrow",      meaning: "to take something and give it back later", example: "Can I borrow your pen?", pic: "🤝", pos: "v", ipa: "/ˈbɒrəʊ/", cat: "School" },
    { word: "return",      meaning: "to give something back", example: "Please return the books on Friday.", pic: "↩️", pos: "v", ipa: "/rɪˈtɜːn/", cat: "School" },
    { word: "promise",     meaning: "to say you will do something", example: "I promise to help you.", pic: "🤞", pos: "v", ipa: "/ˈprɒmɪs/", cat: "Talk" },
    { word: "suggest",     meaning: "to offer an idea", example: "He suggested a new route.", pic: "💡", pos: "v", ipa: "/səˈdʒest/", cat: "Talk" },
    { word: "arrive",      meaning: "to get to a place", example: "The bus arrives at six.", pic: "🚌", pos: "v", ipa: "/əˈraɪv/", cat: "Travel" },
    { word: "forget",      meaning: "to not remember", example: "Don't forget your keys!", pic: "🧠", pos: "v", ipa: "/fəˈɡet/", cat: "School" },
    { word: "remember",    meaning: "to keep something in your mind", example: "I remember my first day at school.", pic: "💭", pos: "v", ipa: "/rɪˈmembə(r)/", cat: "School" },
    { word: "belong",      meaning: "to be in the right place", example: "This bag belongs to me.", pic: "🧷", pos: "v", ipa: "/bɪˈlɒŋ/", cat: "Home" },
    { word: "umbrella",    meaning: "a thing you hold over your head in the rain", example: "Take an umbrella — it's raining.", pic: "☂️", pos: "n", ipa: "/ʌmˈbrelə/", cat: "Nature" },
    { word: "envelope",    meaning: "a paper cover for a letter", example: "She put the letter in an envelope.", pic: "✉️", pos: "n", ipa: "/ˈenvələʊp/", cat: "Talk" },
    { word: "pocket",      meaning: "a small bag in your clothes", example: "The key is in my pocket.", pic: "👖", pos: "n", ipa: "/ˈpɒkɪt/", cat: "Home" },
    { word: "sharp",       meaning: "able to cut easily", example: "This knife is very sharp.", pic: "🔪", pos: "adj", ipa: "/ʃɑːp/", cat: "Home" },
    { word: "neat",        meaning: "tidy and clean", example: "Her handwriting is very neat.", pic: "✨", pos: "adj", ipa: "/niːt/", cat: "School" },
    { word: "polite",      meaning: "behaving with good manners", example: "It's polite to say thank you.", pic: "🙇", pos: "adj", ipa: "/pəˈlaɪt/", cat: "People" }
  ],
  "B1": [
    { word: "achievement", meaning: "something good you succeed in doing", example: "Passing the exam was a great achievement.", pic: "🏆", pos: "n", ipa: "/əˈtʃiːvmənt/", cat: "Goals" },
    { word: "opportunity", meaning: "a chance to do something", example: "This job is a good opportunity.", pic: "🚪", pos: "n", ipa: "/ˌɒpəˈtjuːnəti/", cat: "Work" },
    { word: "challenge",   meaning: "something difficult that tests you", example: "Learning a language is a challenge.", pic: "🧗", pos: "n", ipa: "/ˈtʃælɪndʒ/", cat: "Goals" },
    { word: "environment", meaning: "the world around us — air, land and water", example: "We must protect the environment.", pic: "🌍", pos: "n", ipa: "/ɪnˈvaɪrənmənt/", cat: "Nature" },
    { word: "relationship",meaning: "the way people know and feel about each other", example: "They have a strong relationship.", pic: "💞", pos: "n", ipa: "/rɪˈleɪʃnʃɪp/", cat: "Family" },
    { word: "education",   meaning: "teaching and learning", example: "Education opens many doors.", pic: "🎓", pos: "n", ipa: "/ˌedʒuˈkeɪʃn/", cat: "School" },
    { word: "community",   meaning: "people who live or work in the same area", example: "The local community helped the school.", pic: "🏘️", pos: "n", ipa: "/kəˈmjuːnəti/", cat: "Home" },
    { word: "decision",    meaning: "a choice you make", example: "It was a difficult decision.", pic: "⚖️", pos: "n", ipa: "/dɪˈsɪʒn/", cat: "Goals" },
    { word: "advantage",   meaning: "something good about a choice", example: "One advantage of cycling is fitness.", pic: "👍", pos: "n", ipa: "/ədˈvɑːntɪdʒ/", cat: "Goals" },
    { word: "disadvantage",meaning: "something bad about a choice", example: "The main disadvantage is the cost.", pic: "👎", pos: "n", ipa: "/ˌdɪsədˈvɑːntɪdʒ/", cat: "Goals" },
    { word: "reliable",    meaning: "able to be trusted", example: "She is a reliable colleague.", pic: "🛡️", pos: "adj", ipa: "/rɪˈlaɪəbl/", cat: "Work" },
    { word: "confident",   meaning: "sure about yourself or your abilities", example: "He felt confident before the interview.", pic: "💪", pos: "adj", ipa: "/ˈkɒnfɪdənt/", cat: "People" },
    { word: "effective",   meaning: "working well and producing results", example: "This is an effective study method.", pic: "🎯", pos: "adj", ipa: "/ɪˈfektɪv/", cat: "Goals" },
    { word: "responsible", meaning: "having a duty to look after something", example: "You are responsible for your own progress.", pic: "🧑‍💼", pos: "adj", ipa: "/rɪˈspɒnsəbl/", cat: "Work" },
    { word: "avoid",       meaning: "to stay away from something", example: "Avoid making the same mistake twice.", pic: "🚫", pos: "v", ipa: "/əˈvɔɪd/", cat: "Routine" },
    { word: "encourage",   meaning: "to give someone support or confidence", example: "Teachers encourage students to ask questions.", pic: "🎉", pos: "v", ipa: "/ɪnˈkʌrɪdʒ/", cat: "People" },
    { word: "manage",      meaning: "to succeed in doing something, often with effort", example: "She managed to finish on time.", pic: "🦸", pos: "v", ipa: "/ˈmænɪdʒ/", cat: "Work" },
    { word: "recommend",   meaning: "to say that something is good", example: "I recommend this book to my students.", pic: "⭐", pos: "v", ipa: "/ˌrekəˈmend/", cat: "Talk" },
    { word: "realise",     meaning: "to understand something clearly", example: "I realised I had forgotten my keys.", pic: "💡", pos: "v", ipa: "/ˈrɪəlaɪz/", cat: "School" },
    { word: "opinion",     meaning: "what you think about something", example: "In my opinion, this is the best option.", pic: "🗨️", pos: "n", ipa: "/əˈpɪnjən/", cat: "Talk" },
    { word: "contribute",  meaning: "to give your part to something", example: "Everyone can contribute ideas.", pic: "🤲", pos: "v", ipa: "/kənˈtrɪbjuːt/", cat: "Work" },
    { word: "develop",     meaning: "to grow or improve over time", example: "Sport helps children develop confidence.", pic: "🌱", pos: "v", ipa: "/dɪˈveləp/", cat: "Goals" },
    { word: "reduce",      meaning: "to make smaller or less", example: "We need to reduce plastic waste.", pic: "📉", pos: "v", ipa: "/rɪˈdjuːs/", cat: "Nature" },
    { word: "increase",    meaning: "to make or become bigger or more", example: "Prices increase every year.", pic: "📈", pos: "v", ipa: "/ɪnˈkriːs/", cat: "Shopping" },
    { word: "behaviour",   meaning: "the way you act", example: "Good behaviour is rewarded.", pic: "🎭", pos: "n", ipa: "/bɪˈheɪvjə(r)/", cat: "People" },
    { word: "available",   meaning: "able to be used or got", example: "The new model is available now.", pic: "🛒", pos: "adj", ipa: "/əˈveɪləbl/", cat: "Shopping" },
    { word: "essential",   meaning: "completely necessary", example: "Water is essential for life.", pic: "💧", pos: "adj", ipa: "/ɪˈsenʃl/", cat: "Nature" },
    { word: "however",     meaning: "but; used to introduce a contrast", example: "It's cheap. However, the quality is poor.", pic: "🔄", pos: "adv", ipa: "/haʊˈevə(r)/", cat: "Talk" },
    { word: "therefore",   meaning: "for that reason", example: "It was late; therefore, we left.", pic: "➡️", pos: "adv", ipa: "/ˈðeəfɔː(r)/", cat: "Talk" },
    { word: "although",    meaning: "despite the fact that", example: "Although it rained, we went out.", pic: "🌂", pos: "conj", ipa: "/ɔːlˈðəʊ/", cat: "Talk" }
  ],
  "B2": [
    { word: "perspective", meaning: "a way of seeing or thinking about something", example: "Travel gives you a new perspective.", pic: "🖼️", pos: "n", ipa: "/pəˈspektɪv/", cat: "Culture" },
    { word: "consequence", meaning: "a result that follows an action", example: "Every decision has consequences.", pic: "⛓️", pos: "n", ipa: "/ˈkɒnsɪkwəns/", cat: "Goals" },
    { word: "controversy", meaning: "strong public disagreement", example: "The policy caused controversy.", pic: "⚡", pos: "n", ipa: "/ˈkɒntrəvɜːsi/", cat: "Talk" },
    { word: "sustainable", meaning: "able to continue without harming the future", example: "We need sustainable energy.", pic: "♻️", pos: "adj", ipa: "/səˈsteɪnəbl/", cat: "Nature" },
    { word: "innovation",  meaning: "a new idea or way of doing things", example: "The app is a real innovation.", pic: "🚀", pos: "n", ipa: "/ˌɪnəˈveɪʃn/", cat: "Science" },
    { word: "inequality",  meaning: "unfair difference between people", example: "The report highlights income inequality.", pic: "⚖️", pos: "n", ipa: "/ˌɪnɪˈkwɒləti/", cat: "Culture" },
    { word: "assumption",  meaning: "something you believe without proof", example: "Don't make assumptions about people.", pic: "🧩", pos: "n", ipa: "/əˈsʌmpʃn/", cat: "Talk" },
    { word: "evidence",    meaning: "facts that show something is true", example: "There is strong evidence for this theory.", pic: "🔍", pos: "n", ipa: "/ˈevɪdəns/", cat: "Science" },
    { word: "priority",    meaning: "the thing that matters most", example: "Health is my top priority.", pic: "🥇", pos: "n", ipa: "/praɪˈɒrəti/", cat: "Goals" },
    { word: "alternative", meaning: "another possible choice", example: "We need an alternative plan.", pic: "🔄", pos: "n", ipa: "/ɔːlˈtɜːnətɪv/", cat: "Goals" },
    { word: "significant", meaning: "important or large enough to matter", example: "There was a significant change.", pic: "🔆", pos: "adj", ipa: "/sɪɡˈnɪfɪkənt/", cat: "Science" },
    { word: "efficient",   meaning: "working without wasting time or energy", example: "This method is more efficient.", pic: "⚙️", pos: "adj", ipa: "/ɪˈfɪʃnt/", cat: "Work" },
    { word: "accurate",    meaning: "exactly correct", example: "The figures are accurate.", pic: "🎯", pos: "adj", ipa: "/ˈækjərət/", cat: "School" },
    { word: "flexible",    meaning: "able to change easily", example: "My work hours are flexible.", pic: "🤸", pos: "adj", ipa: "/ˈfleksəbl/", cat: "Work" },
    { word: "relevant",    meaning: "connected to the subject", example: "Include only relevant details.", pic: "📎", pos: "adj", ipa: "/ˈreləvənt/", cat: "Talk" },
    { word: "negotiate",   meaning: "to discuss to reach an agreement", example: "They negotiated a fair price.", pic: "🤝", pos: "v", ipa: "/nɪˈɡəʊʃieɪt/", cat: "Work" },
    { word: "evaluate",    meaning: "to judge the value or quality of something", example: "Evaluate the advantages first.", pic: "🧭", pos: "v", ipa: "/ɪˈvæljueɪt/", cat: "Science" },
    { word: "justify",     meaning: "to give good reasons for something", example: "Can you justify your choice?", pic: "🗝️", pos: "v", ipa: "/ˈdʒʌstɪfaɪ/", cat: "Talk" },
    { word: "distinguish", meaning: "to see the difference between things", example: "It's hard to distinguish the two sounds.", pic: "🔬", pos: "v", ipa: "/dɪˈstɪŋɡwɪʃ/", cat: "School" },
    { word: "interpret",   meaning: "to explain the meaning of something", example: "How do you interpret this data?", pic: "📊", pos: "v", ipa: "/ɪnˈtɜːprɪt/", cat: "Science" },
    { word: "acknowledge", meaning: "to accept that something is true", example: "She acknowledged her mistake.", pic: "🙋", pos: "v", ipa: "/əkˈnɒlɪdʒ/", cat: "Talk" },
    { word: "adapt",       meaning: "to change to suit a new situation", example: "Animals adapt to their environment.", pic: "🦎", pos: "v", ipa: "/əˈdæpt/", cat: "Nature" },
    { word: "benefit",     meaning: "a good effect or advantage", example: "Exercise has many benefits.", pic: "🌟", pos: "n", ipa: "/ˈbenɪfɪt/", cat: "Health" },
    { word: "commit",      meaning: "to promise to do something", example: "She committed to a healthier lifestyle.", pic: "🤜", pos: "v", ipa: "/kəˈmɪt/", cat: "Goals" },
    { word: "expand",      meaning: "to become bigger", example: "The company plans to expand abroad.", pic: "🌐", pos: "v", ipa: "/ɪkˈspænd/", cat: "Work" },
    { word: "generate",    meaning: "to produce something", example: "Wind farms generate electricity.", pic: "🌬️", pos: "v", ipa: "/ˈdʒenəreɪt/", cat: "Science" },
    { word: "impact",      meaning: "a strong effect", example: "Social media has a huge impact on teenagers.", pic: "🎳", pos: "n", ipa: "/ˈɪmpækt/", cat: "Tech" },
    { word: "insight",     meaning: "a deep understanding", example: "The book offers real insight into history.", pic: "🧠", pos: "n", ipa: "/ˈɪnsaɪt/", cat: "Culture" },
    { word: "perceive",    meaning: "to see or understand in a particular way", example: "People perceive risks differently.", pic: "👀", pos: "v", ipa: "/pəˈsiːv/", cat: "Talk" },
    { word: "refine",      meaning: "to improve by making small changes", example: "The design was refined over months.", pic: "💎", pos: "v", ipa: "/rɪˈfaɪn/", cat: "Science" }
  ],
  "C1": [
    { word: "ambiguity",   meaning: "when something has more than one meaning", example: "The sentence is full of ambiguity.", pic: "🌫️", pos: "n", ipa: "/ˌæmbɪˈɡjuːəti/", cat: "Talk" },
    { word: "coherence",   meaning: "logical connection between ideas", example: "Her essay has clear coherence.", pic: "🧵", pos: "n", ipa: "/kəʊˈhɪərəns/", cat: "School" },
    { word: "concession",  meaning: "something you admit or give up in an argument", example: "He made a concession to reach agreement.", pic: "🎁", pos: "n", ipa: "/kənˈseʃn/", cat: "Talk" },
    { word: "discourse",   meaning: "written or spoken communication", example: "Academic discourse has its own rules.", pic: "📚", pos: "n", ipa: "/ˈdɪskɔːs/", cat: "School" },
    { word: "implication", meaning: "a suggested meaning or result", example: "What are the implications of this finding?", pic: "🧨", pos: "n", ipa: "/ˌɪmplɪˈkeɪʃn/", cat: "Science" },
    { word: "rationale",   meaning: "the reason behind a decision", example: "Explain the rationale for your choice.", pic: "🧮", pos: "n", ipa: "/ˌræʃəˈnɑːl/", cat: "Goals" },
    { word: "constraint",  meaning: "something that limits you", example: "Time is the main constraint.", pic: "🔒", pos: "n", ipa: "/kənˈstreɪnt/", cat: "Work" },
    { word: "hypothesis",  meaning: "an idea you test with evidence", example: "The experiment tested our hypothesis.", pic: "🧪", pos: "n", ipa: "/haɪˈpɒθəsɪs/", cat: "Science" },
    { word: "phenomenon",  meaning: "a fact or event you can observe", example: "Climate change is a global phenomenon.", pic: "🌪️", pos: "n", ipa: "/fəˈnɒmɪnən/", cat: "Nature" },
    { word: "competence",  meaning: "the ability to do something well", example: "She showed great competence.", pic: "🏅", pos: "n", ipa: "/ˈkɒmpɪtəns/", cat: "Work" },
    { word: "subtle",      meaning: "small and difficult to notice", example: "There is a subtle difference.", pic: "🕵️", pos: "adj", ipa: "/ˈsʌtl/", cat: "Talk" },
    { word: "compelling",  meaning: "very convincing or interesting", example: "The evidence is compelling.", pic: "🧲", pos: "adj", ipa: "/kəmˈpelɪŋ/", cat: "Science" },
    { word: "inevitable",  meaning: "certain to happen", example: "Change is inevitable.", pic: "⏳", pos: "adj", ipa: "/ɪnˈevɪtəbl/", cat: "Goals" },
    { word: "predominant", meaning: "most common or strongest", example: "English is the predominant language here.", pic: "🏔️", pos: "adj", ipa: "/prɪˈdɒmɪnənt/", cat: "Culture" },
    { word: "valid",       meaning: "based on good reasons or facts", example: "That is a valid argument.", pic: "✅", pos: "adj", ipa: "/ˈvælɪd/", cat: "Talk" },
    { word: "articulate",  meaning: "to express ideas clearly", example: "She articulated her views well.", pic: "🎙️", pos: "v", ipa: "/ɑːˈtɪkjuleɪt/", cat: "Talk" },
    { word: "scrutinise",  meaning: "to examine very carefully", example: "The committee scrutinised the data.", pic: "🔎", pos: "v", ipa: "/ˈskruːtənaɪz/", cat: "Science" },
    { word: "facilitate",  meaning: "to make something easier", example: "Group work facilitates learning.", pic: "🛝", pos: "v", ipa: "/fəˈsɪlɪteɪt/", cat: "Work" },
    { word: "implement",   meaning: "to put a plan into action", example: "The school implemented a new policy.", pic: "🛠️", pos: "v", ipa: "/ˈɪmplɪment/", cat: "Work" },
    { word: "infer",       meaning: "to work out from evidence", example: "We can infer the writer's attitude.", pic: "🧠", pos: "v", ipa: "/ɪnˈfɜː(r)/", cat: "School" },
    { word: "advocate",    meaning: "to support a cause publicly", example: "They advocate for cleaner transport.", pic: "📣", pos: "v", ipa: "/ˈædvəkeɪt/", cat: "Culture" },
    { word: "coherent",    meaning: "clear and logical", example: "Her speech was coherent and persuasive.", pic: "🧩", pos: "adj", ipa: "/kəʊˈhɪərənt/", cat: "Talk" },
    { word: "disparity",   meaning: "a great difference", example: "There is a disparity in salaries.", pic: "📏", pos: "n", ipa: "/dɪˈspærəti/", cat: "Culture" },
    { word: "empirical",   meaning: "based on observation or experiment", example: "The claim lacks empirical support.", pic: "🔭", pos: "adj", ipa: "/ɪmˈpɪrɪkl/", cat: "Science" },
    { word: "encompass",   meaning: "to include a wide range of things", example: "The course encompasses all four skills.", pic: "⭕", pos: "v", ipa: "/ɪnˈkʌmpəs/", cat: "School" },
    { word: "foster",      meaning: "to help something develop", example: "Reading fosters imagination.", pic: "🌿", pos: "v", ipa: "/ˈfɒstə(r)/", cat: "Goals" },
    { word: "implicit",    meaning: "suggested without being said directly", example: "There was an implicit warning in his words.", pic: "🫥", pos: "adj", ipa: "/ɪmˈplɪsɪt/", cat: "Talk" },
    { word: "notion",      meaning: "an idea or belief", example: "The notion of fairness is universal.", pic: "💭", pos: "n", ipa: "/ˈnəʊʃn/", cat: "Culture" },
    { word: "purport",     meaning: "to claim to be or do something", example: "The document purports to prove the theory.", pic: "📜", pos: "v", ipa: "/pəˈpɔːt/", cat: "Science" },
    { word: "robust",      meaning: "strong and effective", example: "The study used robust methods.", pic: "🏋️", pos: "adj", ipa: "/rəʊˈbʌst/", cat: "Science" }
  ],
  "C2": [
    { word: "nuance",        meaning: "a small, fine detail of meaning", example: "The poem is full of nuance.", pic: "🎭", pos: "n", ipa: "/ˈnjuːɑːns/", cat: "Talk" },
    { word: "paradigm",      meaning: "a typical model or way of thinking", example: "The discovery created a new paradigm.", pic: "🧿", pos: "n", ipa: "/ˈpærədaɪm/", cat: "Science" },
    { word: "epistemic",     meaning: "relating to knowledge", example: "They discussed epistemic questions.", pic: "📖", pos: "adj", ipa: "/ˌepɪˈstiːmɪk/", cat: "Science" },
    { word: "idiosyncratic", meaning: "unusual and individual", example: "He has an idiosyncratic writing style.", pic: "🎲", pos: "adj", ipa: "/ˌɪdiəsɪŋˈkrætɪk/", cat: "Culture" },
    { word: "conundrum",     meaning: "a confusing problem", example: "The team faced a real conundrum.", pic: "🌀", pos: "n", ipa: "/kəˈnʌndrəm/", cat: "Talk" },
    { word: "corollary",     meaning: "a result that naturally follows", example: "Higher prices are a corollary of demand.", pic: "🧧", pos: "n", ipa: "/kəˈrɒləri/", cat: "Science" },
    { word: "dichotomy",     meaning: "a division into two opposite parts", example: "The essay explores the dichotomy between freedom and order.", pic: "☯️", pos: "n", ipa: "/daɪˈkɒtəmi/", cat: "Culture" },
    { word: "fallacy",       meaning: "a false belief or wrong argument", example: "It is a fallacy that money buys happiness.", pic: "🪤", pos: "n", ipa: "/ˈfæləsi/", cat: "Talk" },
    { word: "proposition",   meaning: "a statement or suggested plan", example: "The proposition was debated for hours.", pic: "🧾", pos: "n", ipa: "/ˌprɒpəˈzɪʃn/", cat: "Science" },
    { word: "premise",       meaning: "an idea an argument is based on", example: "The argument rests on a false premise.", pic: "🏗️", pos: "n", ipa: "/ˈpremɪs/", cat: "Talk" },
    { word: "intrinsic",     meaning: "belonging naturally to something", example: "Learning has intrinsic value.", pic: "💠", pos: "adj", ipa: "/ɪnˈtrɪnsɪk/", cat: "Science" },
    { word: "pervasive",     meaning: "present everywhere", example: "Technology is pervasive in modern life.", pic: "🌊", pos: "adj", ipa: "/pəˈveɪsɪv/", cat: "Tech" },
    { word: "tentative",     meaning: "not certain; provisional", example: "They made a tentative agreement.", pic: "✏️", pos: "adj", ipa: "/ˈtentətɪv/", cat: "Goals" },
    { word: "unprecedented", meaning: "never done before", example: "The change was unprecedented.", pic: "🆕", pos: "adj", ipa: "/ʌnˈpresɪdentɪd/", cat: "Science" },
    { word: "meticulous",    meaning: "very careful and exact", example: "She keeps meticulous notes.", pic: "🔬", pos: "adj", ipa: "/məˈtɪkjələs/", cat: "School" },
    { word: "corroborate",   meaning: "to support with evidence", example: "The witness corroborated his story.", pic: "🧱", pos: "v", ipa: "/kəˈrɒbəreɪt/", cat: "Science" },
    { word: "extrapolate",   meaning: "to guess beyond known facts", example: "We can extrapolate future trends.", pic: "📈", pos: "v", ipa: "/ɪkˈstræpəleɪt/", cat: "Science" },
    { word: "reconcile",     meaning: "to make two ideas agree", example: "How do you reconcile these two views?", pic: "🤝", pos: "v", ipa: "/ˈrekənsaɪl/", cat: "Talk" },
    { word: "substantiate",  meaning: "to prove with evidence", example: "He could not substantiate his claim.", pic: "🧨", pos: "v", ipa: "/səbˈstænʃieɪt/", cat: "Talk" },
    { word: "differentiate", meaning: "to show or see the difference", example: "Learners must differentiate formal and informal register.", pic: "🧮", pos: "v", ipa: "/ˌdɪfəˈrenʃieɪt/", cat: "School" },
    { word: "cogent",        meaning: "clear, logical and convincing", example: "She presented a cogent argument.", pic: "💬", pos: "adj", ipa: "/ˈkəʊdʒənt/", cat: "Talk" },
    { word: "delineate",     meaning: "to describe or mark out clearly", example: "The report delineates the main stages.", pic: "📏", pos: "v", ipa: "/dɪˈlɪnieɪt/", cat: "Science" },
    { word: "eschew",        meaning: "to deliberately avoid something", example: "The author eschews technical jargon.", pic: "🙅", pos: "v", ipa: "/ɪsˈtʃuː/", cat: "Talk" },
    { word: "felicitous",    meaning: "perfectly chosen or appropriate", example: "The title is a felicitous choice.", pic: "🎯", pos: "adj", ipa: "/fəˈlɪsɪtəs/", cat: "Culture" },
    { word: "germane",       meaning: "directly relevant to the matter", example: "Keep your comments germane to the topic.", pic: "🌾", pos: "adj", ipa: "/ˈdʒɜːmeɪn/", cat: "Talk" },
    { word: "harbinger",     meaning: "a sign that something is coming", example: "The strike was a harbinger of change.", pic: "🔔", pos: "n", ipa: "/ˈhɑːbɪndʒə(r)/", cat: "Culture" },
    { word: "lacuna",        meaning: "a gap where something is missing", example: "The study fills a lacuna in the research.", pic: "🕳️", pos: "n", ipa: "/ləˈkjuːnə/", cat: "Science" },
    { word: "malleable",     meaning: "easily shaped or influenced", example: "Young minds are highly malleable.", pic: "🧱", pos: "adj", ipa: "/ˈmæliəbl/", cat: "Science" },
    { word: "obfuscate",     meaning: "to make something unclear on purpose", example: "Politicians often obfuscate the truth.", pic: "🌫️", pos: "v", ipa: "/ˈɒbfʌskeɪt/", cat: "Talk" },
    { word: "quintessential",meaning: "being the most perfect example", example: "She is the quintessential teacher.", pic: "💎", pos: "adj", ipa: "/ˌkwɪntɪˈsenʃl/", cat: "Culture" }
  ]
};
